### ISSUE TITLE
LWM2M Security DDF

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#10]
The XML document for the LWM2M Security Object has a typo in the name field: "LWM2M  Server URI" with two spaces

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by jpradocueva** [comment]
New Change Request #38 will address this and other problems in the XML file.

**Comment by Megan-OMA** [comment]
Issue closed per Joaquin's comment above this is addressed in issue 38
