### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160407-C, 8.2.4, figure 21, DELETE, wrong response

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#100]
Figure 21 shows "Success" as response for DELETE.
Table 23 defines "2.02 Deleted" for that.
Please correct the figure.

**Comment by ThGarnier** [comment]
Fixed for the May release

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20160509-D.
