### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160407-C, 8.2.4, figure 21, CREATE with instance ID

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#101]
Figure 21 contains a example `POST /2/4,` response `2.01 created`.
Using instance ID is deprecated.
Please remove example.

**Comment by ThGarnier** [comment]
Fixed for the May release

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20160509-D
