### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160407-C, 8.3, figure 24, update registration wrong

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#102]
Figure 24, 
update registration `PUT /rd/5a3f` should be `POST`
response `2.05 Content` should be `2.04 Changed`

**Comment by ThGarnier** [comment]
Fixed for the May release

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20160509-D
