### ISSUE TITLE
Observe operations on multi-instance objects

### ISSUE THREAD

**Issue by alex-ellwein** [OpenMobileAlliance/OMA_LwM2M_for_Developers#105]
I need some clarification regarding observe operations on multi-instance objects.
Given that a multi-instance object is observed (using **/objectID** path), and as current specification stating

> When “Observe” operation contains only Object ID, the “Notify” operation MUST be done per Object Instance

Following questions are arising from that scenario:
1. Does the response (not the notify) to the Observe operation have to contain **all** the object instances of the observed object initially?
2. If a Notify operation contains only one Object Instance reported, are we still here conform to the CoAP RFC?
3. If it is perfectly valid to notify with a single instance of an object, don't we have to resolve issue #86 first?

Thank you!

**Comment by jvermillard** [comment]
related to #76 ?

**Comment by alex-ellwein** [comment]
@jvermillard i think it is a kind of related on topic of "partial notifies"

**Comment by ThGarnier** [comment]
Yes the spec on Observe/Notify  has clearly to be improved on that points (#86 & #105) :-)  thanks
3) proposal should be to specify as mandatory Object Instance TLV when an Object  has several instances (to remove ambiguity about which is the notified instance) and in the same way to specify as mandatory Multi Instance TLV when an Instance is multi)  
2) is there - in the rfc 7641 -, something which explicitly prevents this  (only one Object Instance reported) ? 
1) I could have a proposal for this, but it depends on the answer regarding your point 2)  :-)

**Comment by jvermillard** [comment]
So for the spirit of the RFC:
https://tools.ietf.org/html/rfc7641#section-3.2

> Notifications are additional responses sent by the server in reply
> the single extended GET request that created the registration.  Each
> notification includes the token specified by the client in the
> request.  The only difference between a notification and a normal
> response is the presence of the Observe Option.

So it's clear the CoAP observe expect you to produce a notification like you produce a GET response.

But yes it's not really efficient for our usage.

**Comment by dnav** [comment]
In the current 1.0.1 TS, text was modified to:
> It has to be noted that an “Observe” operation containing only Object ID, will produce the report of all Object Instances information.
