### ISSUE TITLE
OMA-SUP-XML_LWM2M_Firmware_Update-V1_0-20160407-C, missing (optional) resources 6 and 7

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#107]
OMA-SUP-XML_LWM2M_Firmware_Update-V1_0-20160407-C doesn't contain the resources for ID 6 and 7 as defined in OMA-TS-LightweightM2M-V1_0-20160407-C.

**Comment by boaks** [comment]
The `<RangeEnumeration>1-3</RangeEnumeration>` for state (resource ID 3) is deprecated.
Should be `<RangeEnumeration>0-3</RangeEnumeration>`.

**Comment by boaks** [comment]
The `<RangeEnumeration>0-6</RangeEnumeration>` for update result (resource ID 5) is deprecated.
Should be `<RangeEnumeration>0-8</RangeEnumeration>`.

**Comment by jpradocueva** [comment]
Change Request #37 has been created to address this problem.

**Comment by boaks** [comment]
Thanks,

http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0037-CR_Firmware_Update_Changes.zip

will fix it.

**Comment by jpradocueva** [comment]
This problem will be resolved in the next release.
