### ISSUE TITLE
Object ID 15:  Device Capability Managment

### ISSUE THREAD

**Issue by subhashnairp** [OpenMobileAlliance/OMA_LwM2M_for_Developers#108]
Regarding object id 15,  Suppose there are Capability Called Sensor , NAVIGATION  in a device. 

        It can be modelled as Instance 0  of Object ID is Sensor . And Instance 1 of object id 15 is NAVIGATION  .
And  suppose in Sensor there are Luminosity,Temperature,Pressure  .This is will be list in property arrtribute of  the object id 15.      Hope my understanding is correct.
    Can we do enable/disable  operations on  individual sensors? or is the enbale/disbale feature is for the entire sensor group?

Thanks
Subhash

**Comment by ThGarnier** [comment]
So depending what you nee, you can used the Device Capability Object either to manage the various sensors individually or not.
1) if you create a list of sensors using the Property resource, all these sensors will be managed together; so the enable/disable feature is for all the elements of that list.
2) if you want to manage these sensors all individually, you need to create a DevCapability Instance per sensor : so /15/0 is SENSOR luminosity, /15/1 is SENSOR Temperature, /15/2 is SENSOR Pressure, /15/3 is   NAVIGATION GPS ... 
Th

**Comment by subhashnairp** [comment]
The Property  Field of object ID 15 is a  list .  And if an instance is created for the entire sensor  , the property will contain a list of different sensors.
    But if we are creating an instance for each sensors  then what will the the content of the Mandatory field Property .

**Comment by ThGarnier** [comment]
In any case, the property list will contain (as long as SENSOR category is selected) what kind of sensor is concerned.
1) a Device Capability Instance gathering the 3 sensors : the property list will be  /15/0/0 = "0,2,4"  
2) if the 3 sensors (luminosity, Temperature,Pressure) use a instance each we will have
     /15/1/0 = "0"       /15/2/0 = "2"   /15/3/0 = "4"

**Comment by hannestschofenig** [comment]
Here is my view: if you have a device that happens to have 3 sensors, namely luminosity, Temperature, Pressure, then each of these would be represented as an independent object. 

As a first step, you should look at the already registered objects, which can be found at this OMA website: http://technical.openmobilealliance.org/Technical/technical-information/omna/lightweight-m2m-lwm2m-object-registry

This website will tell you that there are objects already defined for 
* Illuminance Sensor (Object ID = 3301)
* Temperature Sensor (Object ID = 3303) 
* Pressure Sensor (Object ID = 3323)

That OMA website also provides you the details of these object definitions (in XML format). 

The Device Capability Management object is IMHO under-specified to be useful.

So, I believe it depends what you are trying to do. There are typically certain events that trigger your device to take certain actions. For example, if you want to get a temperature sensor reading your application context may tell you that you need to read the temperature very 15 min; in other cases the temperature reading will only happen on demand -- if you want to retrieve the value with your smart phone app. All this can be done by just using the above-mentioned objects alone (without the Device Capability Management object).

**Comment by subhashnairp** [comment]
Hi,
   In terms of device managemnt point of view , it is important that the DM
server should be able to Enable/ disable an attached device capability (
may be sensors, external memory etc) or check if it attached/ detached .
   So object ID 15 probably fit that requirements . I guess object ID 15
should export to server all the sensors attached in device .And DM server
can implement disabling or enabling it remotely
Thanks
Subhash

**Comment by ThGarnier** [comment]
Hi Subhash, if my 2 comments on 19-April are OK for you, that issue could be closed. could it ?

**Comment by subhashnairp** [comment]
Hi dear Thierry ,

    Sure .please close it.


Thanks
Subhash
