### ISSUE TITLE
OMA DM Server with LwM2M Client

### ISSUE THREAD

**Issue by trmck** [OpenMobileAlliance/OMA_LwM2M_for_Developers#109]
Hello all,

Two scenarios I'm looking at are:

1) Using an existing OMA DM server to manage LwM2M devices that are able to connect directly to a management server but have a LwM2M client to conserve data.

2) Having a device that has a OMA DM client installed but is able to accept LwM2M messages in order to conserve data.

I would like to know if it is possible for an OMA DM server to speak directly to a LwM2M client without the need for a GwMO. If this is not possible then would it be possible to install a GwMO on a OMA DM Server or client to convert OMA DM to LwM2M. 

Thanks

**Comment by ThGarnier** [comment]
No, there is no specification yet to directly bridge OMA DM and LWM2M worlds.

**Comment by hannestschofenig** [comment]
OMA DM and LWM2M are two different protocols and there is no backwards compatibility assumed. 

Hence, you only have two choices: 

1) You can use a gateway that translates between two protocols. 
2) You implement the two protocols on the server-side to support devices that either use OMA DM or OMA LWM2M. 

I hope that this answers your question.

**Comment by Megan-OMA** [comment]
Issue closed per comments above from Thierry and Hannes
