### ISSUE TITLE
Issue #72, part 1

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#110]
```
Subject : OMA-TS-leightweightM2M-V1_0-20141126C

1.) page 57 - doesn't handle the mapping of Discovery operation to CoAP

```

```
1,) so it is but since all the other mappings are described in a line or paragraph
 I thought it odd that Discover should be left unexplained
```

OMA-TS-LightweightM2M-V1_0-20160407-C, 8.2.4, page 66/67, the textual part still doesn't cover "Discover" as requested by issue #72. (It does contain "Discover" in the table, but the issue was, that it was not on the textual description.)

**Comment by ThGarnier** [comment]
covered in Oct 16 TS => to be closed

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20161007-D fixes it.
