### ISSUE TITLE
Queue mode downstream & Leshan

### ISSUE THREAD

**Issue by msnyder415** [OpenMobileAlliance/OMA_LwM2M_for_Developers#113]
Hi OMA

I have been testing queue mode with Leshan for a few days now, and I am seeing an inconsistency in the Leshan implementation vs the OMA spec @ http://dev_devtoolkit.openmobilealliance.org/IoT/LWM2M10/doc/TS/index.html#!Documents/queuemodeoperation.htm

> Spec defines in Section 8.3 "Each request is sent serially to the LWM2M Client, waiting for request to be Acknowledged before sending the next request"

In the Leshan web console, if I click more than one 'read' button, eg /3/0/1, /3/0/2, and /3/0/3, I receive all 3 commands in a single payload from my modem.  I have even seen up to 5 coap requests downstream.

I am using an LTE modem with a UDP socket. I cannot access the raw UDP payloads unfortunately to see if the 3 GET commands are actually in separate packets. Despite this detail, according to the OMA queue mode spec, I should be receiving no more than 1 downstream request at a time. 

I do not speak a word of java, so I did not dive in to the Leshan code. However, my next move is to file the same issue there. 

For example, here are 5 requests that have been concatenated - 

> read 93 bytes      rx:44 1 58 de b9 6b 2d e6 b1 33 1 30 1 31 43 1 58 df 28 9d 24 b1 33 1 30 1 32 47 1 58 e0 e8 9f 67 18 59 8a e7 b1 33 1 30 1 30 44 1 58 de b9 6b 2d e6 b1 33 1 30 1 31 43 1 58 df 28 9d 24 b1 33 1 30 1 32 47 1 58 e0 e8 9f 67 18 59 8a e7 b1 33 1 30 1 30 60 44 2c b3 c0

**Comment by boaks** [comment]
May be there is a missunderstanding:
Though there is a PR (https://github.com/eclipse/leshan/pull/126) to introduce the queue mode into leshan, which branch did you use?

**Comment by boaks** [comment]
And not only the queue mode ensure, that the request are sent sequentially. Also CoAP RFC7252, 4.7 Congestion Control, would do so with NSTART at the default value of 1.

**Comment by msnyder415** [comment]
Thanks @boaks, I did not see that branch / pull request. I got a similar answer from @sophokles73 on the eclipse/leshan issue page. That explains it!
