### ISSUE TITLE
OMA-DM-LightweightM2M-2016-0050-CR_Firmware_Update_MI, Idle with Res5 = 8?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#114]
Figure 26 shows for valid values of `Res5` in `Idle` the values {0, 1, 2, 3, 4, 5, 6, 7, 8}.

The only case, where `Res5` gets 8 seems to be the failing update, but that ends in state `Downloaded`.
To change from `Downloaded` to `Idle` (re-)sets the value of `Res5` to 0. 

So, how could `Res5` get the value 8 in `Idle`?

Also, the values for `Res5` in `Downloaded` should contain 8 so it should be {0, 8}.

**Comment by ThGarnier** [comment]
good eyes :-)  thanks
