### ISSUE TITLE
Definition of Resource ID '5501' in urn:oma:lwm2m: ext:3342 invalid

### ISSUE THREAD

**Issue by laverman** [OpenMobileAlliance/OMA_LwM2M_for_Developers#116]
I noticed that the tags `Name` and `Description` of Resource 5501 in object urn:oma:lwm2m: ext:3342 do not correspond to the specification give by *IPSO SmartObject Guideline* (21. Sep. 2014).

**In Specification: Resource 5501**
*Name*: Digital Input Couter
*Description*: The cumulative value of active state detected.

**In [urn:oma:lwm2m: ext:3342](http://technical.openmobilealliance.org/tech/profiles/IPSO/3342.xml)**
*Name*: Digital Input State
*Description*: The number of times the input transitions from 0 to 1.

**Note:** This can be an issue in this case, because the `Digital Input State (ID 5500)` is also referenced.

**Comment by jpradocueva** [comment]
@jaimejim it appears that IPSO has an incorrect definition of resources 5501 inside of object 3342, (on/off switch)  **In [urn:oma:lwm2m: ext:3342](http://technical.openmobilealliance.org/tech/profiles/IPSO/3342.xml)**
Object 5501 is duplicated (see 5500).
Please advice

**Comment by laverman** [comment]
_May I add some further information to help clarifying the issue:_
The definition of the IPSO Resources 5500 and 5501 within the IPSO SmartObject Guidline from 21. Sep. 2014 (PDF) seem to be coherent, since they do not overlap in their specification (name / description). 

However, the XML file provided by the OMA seems to not coher with this specification. 
Have this XMLs been provided by the IPSO Alliance?

**Comment by boaks** [comment]
I don't understand the labels. "To be Closed" without a CR?

So let me try to explain what my colleague found:
OMA xml for 3342:

```
<Resources>
<Item ID="5500">
<Name>Digital Input State</Name>
...
<Description>The current state of a digital input.</Description>
</Item>
<Item ID="5501">
<Name>Digital Input State</Name>
...
<Description>The number of times the input transitions from 0 to 1.</Description>
</Item>

```
So the content of the element `Name` (`Digital Input State`) of `Item `5501 seems to be a copy paste error.
The IPSO PDF (IPSO-Smart-Objects-Expansion-Pack, 27 October, 2015) contains 
`Digital Input Counter` as resource name.

So I would expect, that the content of the element `Name `for the `Item `5501 is changed to 
`Digital Input Counter`.

**Comment by ThGarnier** [comment]
Hum !  a CR is a change request for document managed by OMA DM group. In this particular case, everything is under the control of IPSO (spec / xml), so a request to IPSO is the appropriate corrective action.  To check if OMA even includes a service for testing imported specification consistency (xml)

**Comment by boaks** [comment]
Ah, so the xml, using the LWM2M DDF schema, is a contribution from IPSO?
We thought, the xml was generated by the OMA.

**Comment by boaks** [comment]
Move to

https://github.com/IPSO-Alliance/pub/issues/2

**Comment by boaks** [comment]
But I would feel better, if this is closed, when IPSO changed the xml and the xml provided by the OMA is corrected one.

**Comment by jpradocueva** [comment]
The object is defined by IPSO but registered in the OMA registry (OMNA). The issued was reported to IPSO a while ago.
We will close the Issue once IPSO has addressed the problem and we have updated the OMNA register.

**Comment by jaimejim** [comment]
there has been two minor updates to fix [https://github.com/IPSO-Alliance/pub/issues/2](https://github.com/IPSO-Alliance/pub/issues/2) . 
I I believe that the XML on the [IPSO Registry](https://github.com/IPSO-Alliance/pub/tree/master/reg/xml) should be now correct and can be used to update the XML on OMNA. Please note that the Resource ID for "Off Time" has also changed to 5854 as its was overlapping with "Multi-state Output".

**Comment by jpradocueva** [comment]
OMA Registry has been updated after IPSO updates.
The OMA Registry is a collection of objects that are registered by different organizations. The objects submitted here will be reviewed by OMA working group to ensure consistency and also to avoid duplication. The system that will allow these reviews will be finalized this year.

**Comment by Megan-OMA** [comment]
Issue closed per Joaquin's comment above this has been updated by IPSO and OMA 11-Oct-2016
