### ISSUE TITLE
Technical summary attachment is a blank page

### ISSUE THREAD

**Issue by amorenoc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#117]
See OMA_LwM2M_for_Developers/images/admin/Technical_Summary_lwm2m.pdf

**Comment by amorenoc** [comment]
it's an interactive pdf file, as the updated README states.

**Comment by github-oma** [comment]
@amorenoc . We are having some problems with the interactive pdf but my colleague John has resolved the issue by providing two options to view the document.
Thanks for reporting the problem.
