### ISSUE TITLE
xsd for Execute Arguments?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#119]
LWM2M TS 20160531, Appendix D describes additional tables for execute arguments.

Is there a xsd reflecting those additional information?

**Comment by jpradocueva** [comment]
The current [lwm2m.xml](http://www.openmobilealliance.org/tech/profiles/LWM2M.xsd) schema doesn't have any arguments to reflect this additional information. 
Now, the group needs to decide if these extra arguments should be defined as part of the schema.

**Comment by jaimejim** [comment]
@boaks The Schema will need new updates, if only with new Data Types.
I think this is something we will need to fix. If you have a proposal for a new xsd file please feel free to submit it.

**Comment by jpradocueva** [comment]
@boaks I would like to clarify the above comment.
Unfortunately, OMA cannot accept any technical suggestion, from non-OMA members, on how to change OMA specifications. 
OMA IPR Policy can be seen here: [OMA IPR Policy](http://openmobilealliance.org/about-oma/policies-and-terms-of-use).

**Comment by hannestschofenig** [comment]
Jaime, can this issue be closed based on the updated schema in v1.1?

**Comment by hannestschofenig** [comment]
If this issue is still valid, please re-issue it against the LwM2M v1.1 release.
