### ISSUE TITLE
registration format

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA_LwM2M_for_Developers#120]
> If the LWM2M Client supports the JSON data format for all the Objects it SHOULD inform the LWM2M Server by including the content type in the root path link using the ct= link attribute. 

So if the device only support json for some object (the negation of the "if") what are we supposed to do? 

My interpretation is to have a ct=xxx for each link object

**Comment by ThGarnier** [comment]
hum ! do you think if a LWM2M Client can support the JSON format, it could really limit this capability to few objects only ? ?  it seems to me it is a functionality attached to the Client, whatever the object it has to handle. Other perception ?

**Comment by jvermillard** [comment]
My use case is more to be able to specify which object support the store notification feature (object 1 resource 6: Notification storing when disabled or offline) which is only supported by the senml/json format. This make sense to have the client support only for some object, like applicative sensor object and not for everything (for instance we don't want to support observing object 3 with senml/json and have to store time change notification..).
Let's close it and think about that for 1.1
