### ISSUE TITLE
Using SMS for downstream instead of queue mode

### ISSUE THREAD

**Issue by msnyder415** [OpenMobileAlliance/OMA_LwM2M_for_Developers#121]
Hi OMA. 

I've been keeping tabs on the queue mode implementation progress, and as a result, I would like to start looking into using SMS for downstream messages in an environment where the 'thing' is behind a NAT. 

I've looked in both the Leshan source, and the Wakaama source, and references to SMS are far and few between. Is this feature implemented in any of the LWM2M servers?

Thanks!

**Comment by hannestschofenig** [comment]
To our knowledge there are no LWM2M servers that currently support SMS. (Reflects only the limited views of a few OMA DM participants. We have not done a market survey.) Note that the SMS binding is optional to implement for the LWM2M client and the LWM2M server.  

We would need further clarification regarding your question. Which binding mode are you looking to support? SQ or UQS mode?

**Comment by msnyder415** [comment]
Thanks for the info @hannestschofenig . 

I was looking for an alternative to UQ mode, since the implementations I have seen are not up to date with the spec. 
Ideally, UQ would be the best route for my research. 
SMS doesn't seem very lightweight, and feels like a workaround. 

Leshan does send downstream requests when polled in UQ mode. 
However, it will concatenate and send more than one packet, rather than each request serially. 
Given the lack of a 'length' field in that header, it makes the parsing a bit difficult. 

I asked the Leshan maintainers about plans for an implementation closer to the spec, and was pointed to a pull request that had the same behavior. 

I also looked at the wakaama implementation, however I have not tried it yet. I poked around the source a bit, and did not see much happening with the binding.

**Comment by boaks** [comment]
Hi, if I remember it correctly, your "main" problem was a modem, which concats UDP packages, which makes it impossible/very hard to separat the messages again. 

https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/113

Are you really sure, that modem reports the UDP packages concated and that there is no setup/configuration to disable that concatenation?

**Comment by msnyder415** [comment]
@boaks Thank you for the excellent suggestion. I will follow up on monday, when I have access to the hardware again. I know exactly what to check now.

**Comment by msnyder415** [comment]
@boaks , you were absolutely right. Leshan is able to serially send the payloads downstream. My LTE modems are doing the concatenation. I am going to dive into some of the receive buffering settings to see if I can make this work a bit better. You all have my full apologies for blaming Leshan!
