### ISSUE TITLE
LWM2M Connectivity Statistics Object issue

### ISSUE THREAD

**Issue by boria8** [OpenMobileAlliance/OMA_LwM2M_for_Developers#122]
Since OMA-TS-LightweightM2M-V1_0-20160531 document, Connectivity Statistics Object contains duplicate resource 7:
Collection Duration and Stop.

Also, what is the difference between Collection Period(resource 8) and Collection Duration(resource 7)?

**Comment by ThGarnier** [comment]
To my understanding, the Collection Duration has been replaced by Collection Period and should not exist any more (remaining scories) : so it removing Collection Duration from the spec, should resolve your 2 raised issues  :-) 
Confirmation of Sierra who did the change with CR05 in 2016 ?

**Comment by jpradocueva** [comment]
It appears that the CR05R01 in 2016, indeed it added "Collection Period" but it didn't remove "Collection Duration". Another CR is needed to remove "Collection Duration". 
@ThGarnier,  do you want us to prepare the CR?

**Comment by ThGarnier** [comment]
Not really, thanks! I prepared  a simple one (CR114) collecting few typos and very very simple modifs.
Regarding Collection Duration, I just asked Sierra on Github (issue #122) if it corroborates my understanding
Its intention was to remove Collection Duration; if yes I will proceed ☺
Thierry

**Comment by dnav** [comment]
Fixed in TS 1.0.1
