### ISSUE TITLE
Why is a reboot mandated for firmware updates?

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#123]
The Firmware Update section in Appendix E says: 

"
A reboot of the device MUST occur for taking into account the new successfully installed firmware.
After reboot of the device:
• the “State” Resource must be at Downloaded state (2) if the “Package” Resource contains a valid Package which has not been successfully installed yet, or at Idle state (0) otherwise.
• After Device reboot, the Update Result Resource MUST contain the value it had just before Device reboot occurred
"

While many devices require a device to be rebooted when starting a new firmware image but there are other devices that allow "hitless" updates where no restart is required. Why does the specification need to mandate a reboot?

**Comment by boaks** [comment]
From my perspective this "reboot" is just no "issue" of the LWM2M protocol!

There is simply no "message exchange" bound to it. The expectation may be, that a device requires a "registration/update registration" after the update, but this is not mentioned explicitly.
So testing the `MUST` with the means of the protocol will fail and therefore, in my opinion, it's missplaced.

**Comment by hannestschofenig** [comment]
Here is the CR to fix this issue, as discussed at the interim meeting in Paris: 
http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0118-CR_device_reboot.zip

**Comment by ThGarnier** [comment]
In the TS now => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above this is now included in the TS
