### ISSUE TITLE
Deletion of Object Instances after a firmware update 

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#124]
The 'Firmware Update Consideration' section in Appendix E says:

"
If some Objects are not supported after firmware update, the LWM2M Client MUST delete all the Object Instances of the Objects that are not supported.
"

If a device indeed restarted it is quite likely that it does not know anything about its previous firmware version and consequently about the previously supported objects. Hence, how is that device supposed to delete object instances that are not supported.

Is there any indication that this is a practical requirement? What use cases is it supposed to be solving?

**Comment by boaks** [comment]
let me distinguish between:
- static compiled in instances
- dynamically created instances

So for static instances it's easy, they are just gone with the update.
For the dynamic instances I would assume, that there is some "persistent storage" which hold such instances. After the update (or on any (re-)start) the device should check for all dynamic and persisted instances, if the object of that instances (indicated by the object ID) is still supported by the firmware.

**Comment by ThGarnier** [comment]
so the original sentence is kept in TS  up => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above
