### ISSUE TITLE
Can OMA LWM2M use Github for storing the XML of the Objects?

### ISSUE THREAD

**Issue by jaimejim** [OpenMobileAlliance/OMA_LwM2M_for_Developers#127]
At the moment the XML is at http://technical.openmobilealliance.org/tech/profiles/<path>/<object_id>.xml

For me it would be useful to have the XML on Github directly. It is easier to track changes, modifications and new resources, as well as using the Issue tracker to fix typos and inconsistencies.

- Does OMA have a plan on doing that? Maybe its done and I am not aware.

In IPSO we do use Github: <https://github.com/IPSO-Alliance/pub/tree/master/reg/xml> with somewhat good results.

**Comment by jpradocueva** [comment]
OMA is currently updating its LwM2M registry. 
The new system will allow to download the xml files, to call the LwM2M editor, submit Pull Request to register new objects, we are also looking how to expose the registry to Vorto, (Eclipse project). 

Unfortunately, according to OMA rules the xml files need to be stored in a FTP server administered by OMA. However, if IPSO updates its repository we just need a notification and we will mimic the changes in our repository. 
Please note that Object version is about to be introduced. Changes to the existing objects may need to be handle different after this functionality is introduced.

**Comment by Megan-OMA** [comment]
Issue closed per Joaquin's comment on OMA's plans
