### ISSUE TITLE
Errata for SCR B.2.2 LWM2M Server - "Client Registration"

### ISSUE THREAD

**Issue by alex-ellwein** [OpenMobileAlliance/OMA_LwM2M_for_Developers#128]
The cases  "Support of “Update” operation" and "Support of “De-register” operation" have the same items (LWM2M-CR-001-S-M) as the "Support of “Register” operation" case.
Should be maybe LWM2M-CR-008-S-M and LWM2M-CR-009-S-M?

**Comment by ThGarnier** [comment]
Thanks, the fix has been done and will be present in the TS 1.0 of Sept 2016

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment
