### ISSUE TITLE
Errata for E.8 0-6 LWM2M Object: Connectivity Statistics

### ISSUE THREAD

**Issue by alex-ellwein** [OpenMobileAlliance/OMA_LwM2M_for_Developers#129]
The Object with ID 7 contains two resources with Resource ID 7:
Stop (E) - ID 7
and Collection Duration (RW) - ID 7.

**Comment by ThGarnier** [comment]
duplicate #122

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment this is being addressed in Issue 122
