### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160802-D, 6.2.3, a), b), c), d), e): typos?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#130]
`
•	LWM2M Client Registration operation: ep=nodename,</1/0>,<1/1>,</3/0>,</44>;ver= “2.2”,</44/0>
`

The examples contains `<1/1>`, shouldn't it be `</1/1>`?
(This typo seems to be in all five examples.)

**Comment by ThGarnier** [comment]
Yes ! Typos - good eyes !! many thanks!

**Comment by ThGarnier** [comment]
Thanks, the fix has been done and will be present in the TS 1.0 of Sept 2016

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comments
