### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160802-D, 6.2.3, d) implicit object version?

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#131]
`lwm2m=“2.0”,ep=nodename,</1/0>,<1/1>,</3/0>,</4/0>`

Does `lwm2m=“2.0”` then imply `</4>;ver="3.1"`?

**Comment by ThGarnier** [comment]
Yes, as the Object 4 (Connectivity Monitoring) is fully part of the Core Spec , the Server supporting the version "2.0" of the Enabler, exactly knows the status of the 8 basic objects; that's why it is not useful to specify their Object version during registration.

**Comment by boaks** [comment]
Thanks!
