### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160802-D, 6.2.3, Object versioning and Bootstrap

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#132]
How is the bootstrap intented to work with the "object versions"?

5.2.2.3 Client initiated bootstrap
- 8.2.2 extension of the Botostrap Request with lwm2m version?
 
5.2.2.4 Server initiated bootstrap
- Add "implementation specific" knowledge of the version?

**Comment by ThGarnier** [comment]
Regarding the Object Versioning, a simple CR is on going for covering that point whatever the bootstrap mode. Thank's

Regarding the Enabler version (lwm2m), to my knowledge there is no work in that direction. The server is only aware of the LWM2M enabler version supported by the Client after getting that information from the registration phase.
Having a Client requesting for a specific LWM2M enabler version in the bootstrap phase (request) is something which could be considered (discussed)  .. in next LWM2M enabler releases. For the moment, - as usual - as  nothing is specified,  the initial version (1.0) is implicitly considered (backward compatibility position)

**Comment by ThGarnier** [comment]
Fixed in TS1.0 20160914 => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
