### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160802-D, 6.2.3, should "register update" be also comply to that

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#133]
Just to confirm, is it considered, that:
- the "version" information is only sent with "register"
  or
- should the "update registration" also be changed?

**Comment by ThGarnier** [comment]
we have to be clear about version :-) 
In the register command there is a lwm2m={version} which must be specified if the LWM2M enabler is > 1.0  (part of the TS for many years :-) already) . As the ep, it is only part of the Register command and not the Update one
Regarding the Objects themself, for the ones which must be reported in the Update command,  versioning can be  required (6.2.3) as for the Register Command .

**Comment by boaks** [comment]
Thanks for clarification.
Would it be possible to add examples for the "update registration" just to make the clarification obvious to all readers?
