### ISSUE TITLE
DTLS credentials for CoAP Firmware Download Server used for /5/0/1

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#139]
Hi, I still think we need to define, how /5/0/1 coudl be used with coaps. The credentials may be stored in the security object, but right now, this is only possible for BootStrap or LWM2M Server (because the /0/x/1 is only boolean and therefore only able to distinguish between Bootstrap and  LWM2M Server).

May be extend this to enumaration or add another resource.

**Comment by ThGarnier** [comment]
According the WG discussion in Oct16 ( Singapore F2F) it is agreed in that in TS 1.0  there no way to store credential for firmware update in a specific  Security Object Instance  . New req (future release)  could consider this => To be closed

**Comment by boaks** [comment]
OK
