### ISSUE TITLE
Resource lifecycle ambiguity

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#140]
While discussing issue #135, it occured that there are some ambiguities and misunderstandings regarding the lifecycle of Resources within the data model.

As we are currently creating a client-side implementation, my comments will be written from the perspective of the LWM2M Client.
1. As already mentioned in #135, there are some discrepancies regarding the **supported** and **implemented** terms. These should probably be clarified.
2. Is it an expected scenario for different Object Instances of a given Object within a single device to have differing sets of **present** resources? In what case it might occur?
3. Can a Write operation "create" a Resource? I.e., is a following flow possible?
   - Read /1/2/3 -> 4.04 Not Found
   - Write /1/2/3 (some content) -> 2.04 Changed
   - Read /1/2/3 -> 2.05 Content (some content)
   
   (Object and Resource IDs are used figuratively and are NOT meant to represent to their registered meanings)
4. What exactly are the semantics of Optional (i.e., non-Mandatory) Resources? There are several possible interpretations for that matter, including:
   1. The optionality refers only to the fact that the code necessary to handle the Resource may or may not be present within a specific client-side implementation. This would mean that a Resource will either be present in all Object Instances, or will not be present in any - depending on whether it is implemented or not. This would also require that all writeable Optional Resources shall have a well-defined default value, used in case it is not passed by the server in the Create operation - which is not the case in the published Object definitions. Should a default value for String Resources be an empty string? Or zero instances for a Multiple Resource? What about numeric types? Should it be 0 if not explicitly specified in Object definition?
      - In this interpretation, the meaning of the Replace case of the Write operation performed on a whole Object Instance is somewhat unclear. What should happen to the Resources that are present in the Instance, but not mentioned within the Write payload? Should they be reset to default values? The specification seems to suggest that they shall be effectively _removed_, which would contradict this interpretation.
      - On the other hand, @dnav's comment on #135 saying that "there is no concept of _possibly-present_ in LWM2M" seems to suggest that this is the correct interpretation.
   2. The optionality refers to both the fact that the code necessary to handle the Resource may or may not be implemented, and to the fact that the Resource may or may not be present in different Object Instances within a single endpoint. For example, a writeable Optional Resource will initially be present or not based on whether it was passed in the payload of the Create operation that created the Object Instance that contains it. It would then mean that the default values, when present in the specification, are never directly substituted _within_ the data model, but are only to be used by higher-level logic. It would also be logically in line with the definition of the Replace case of the Write operation performed on a whole Object Instance.
5. The definition of the Bootstrap Write operation says that:
   
   > the LWM2M Client MUST write the value included in the payload regardless of an existence of the targeting Object Instance(s) or Resource(s)
   
   How does it relate to Optional Resources? If a specific Resource is not _implemented_ (i.e. there is no code in the implementation present to handle the semantics of such Resource), then the device has no means to comply with this requirement, even though it is specified as a hard "MUST".
   - Or is it expected so that a Resource with just a value and no semantics shall be created in this case? What about its type? Which operations shall be possible to invoke on it?
6. There is a particularly confusing case regarding the Lifetime resource within the LWM2M Server Object (i.e. `/1/*/1`). Table 6 in section 5.3.1 (Register) says that:
   
   > If Lifetime Resource does not exist in a LWM2M Server Object Instance (see Appendix D.1), the Client MUST NOT send this parameter and the Server MUST regard lifetime of the Client as 86400 seconds.
   
   However, section E.2 (E.2 LWM2M Object: LWM2M Server) specifies the Lifetime Resource as Mandatory, which seems to contradict the above statement. Or is it possible for a Mandatory Resource to be absent from an Object Instance? In which circumstances it might occur?

Resolving these ambiguities is necessary for proper interoperability, and also for establishing a common ground necessary to resolve issue #135.

**Comment by dnav** [comment]
My point of view:
2. it is an open point OMA DM WG has to clarify.
3. this is not possible.
4. Optional for me means the Client is not required to implement the resource. ou are raising some valid questions the group needs to adress.
5. This requires clarification in the TS. The Client should ignore optional resources in the payload it does not support.
6. This is a TS error the group needs to fix. A mandatory resource is always present.

**Comment by ThGarnier** [comment]
Please just one issue .. per issue :  hard to answer otherwise, despite you do a really great Job.
Please look at the Nov16 TS 1.0 when available :-)  after OMA Singapore meeting : hope few (many :-) ) of your questions will have an answer . many thanks

**Comment by ThGarnier** [comment]
If still pending issue after Nov16 TS 1.0 => please register individual issues => To be Closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above, re: November 2016 TS
