### ISSUE TITLE
LightweightM2M-1.0-int-105 test (Initial Registration to Bootstrap Server) confusion

### ISSUE THREAD

**Issue by dextero** [OpenMobileAlliance/OMA_LwM2M_for_Developers#141]
While reading the Enabler Test Specification (last publicly available update from 2015-12-08, [link at the bottom of this page](http://technical.openmobilealliance.org/Technical/technical-information/release-program/current-releases/oma-lightweightm2m-v1-0)), test case 105: Initial Registration to Bootstrap Server confused me quite a bit.

From what I understood until now, LWM2M Client can only register to LWM2M Servers and not LWM2M Bootstrap Servers. In [E.2 "LWM2M Object: LWM2M Server"] the description says:

> A Bootstrap Server has no such an [Server] Object Instance associated to it.

[5.3.1 "Register"] requires that:

> After the LWM2M Device is turned on and the bootstrap procedure has been completed, the LWM2M Client MUST perform a “Register” operation **to each LWM2M Server that the LWM2M Client has a Server Object Instance.**

Which does not mention the Bootstrap Server case at all.

That seems to imply the client does not use Registration Interface operations with a LWM2M Bootstrap Server, but test 105 contradicts that. It even explicitly requires an Server Object Instance for the LWM2M Bootstrap Server to be present, which is the opposite of what LWM2M spec says.
1. Does the LWM2M Bootstrap Server support other LWM2M Interfaces besides the Bootstrap Interface? I.e., is the LWM2M Bootstrap Server a "regular" LWM2M Server too, despite not having an associated LWM2M Server Object Instance?
2. Does the client have to Register to the LWM2M Bootstrap Server, or is test 105 invalid?

**Comment by dnav** [comment]
The test 105 is invalid. Actually the ETS needs to be updated.

Regards,

**Comment by dnav** [comment]
Fixed in current ETS.
