### ISSUE TITLE
Bug in Observe with pmin example

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#142]
Section 8.2.4 says: 

"
c)  Write Attributes /3/0?pmin=10 means that all Resources of Instance 0 of the Object ‘Device (ID:3)’ will be notified to the Server with a minimum interval of 1 sec; this value is set at the Object Instance level.
"

Should this be 10sec?

**Comment by ThGarnier** [comment]
yes :-)

**Comment by Echo-xubei** [comment]
I think the section number should be 8.2.5.
This bug has been fixed in the LightweightM2M/V1_0_1-20170704-A.
