### ISSUE TITLE
DTLS SMS Reference Outdated

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#143]
I noticed that the [DTLS-SMS] reference is outdated and still refers to an individual draft. 

For this reason I have proposed to replace the reference to the individual draft with a reference to RFC 7925. Here is the contribution: http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2016/OMA-DM-LightweightM2M-2016-0129-CR_dtls_sms_reference.zip

**Comment by ThGarnier** [comment]
CR is not included in the TS

**Comment by ThGarnier** [comment]
CR is now included in the TS :)  -(Sorry  :-)  )

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above it's now included in the TS
