### ISSUE TITLE
5.2.2.3 Client Initiated Bootstrap when "Register" failed 

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#145]
According 5.2.2.3, a client initiated bootstrap is triggered by

> attempts to perform the “Register” operation with LWM2M Servers have failed.

Does this consider communication situations, where the LWM2M server is temporary not reachable?
Say for "mobile" solutions? If not, this may casue more bootstraps then intendend (I would guess, a LOT more).

**Comment by dnav** [comment]
How can the Client determines if the failure is temporary or not ?
My understanding is that the Client Initiated Bootstrap is required every time the “Register” operation with all LWM2M Servers has failed.
In a mobile context, the Client can decide if a registration failure should be considered temporary or not but this is the implementation responsability.

**Comment by boaks** [comment]
`How can the Client determines if the failure is temporary or not ?`

I don't know :-).

My point is, I expect much more bootstraps caused by "communication problems" then by changed "LWM2M Server Bootstrap Information".

**Comment by hannestschofenig** [comment]
Question: What happens when there are connectivity problems between the LwM2M client and the LwM2M server? 

Answer: This is implementation-dependent. Most likely the LwM2M will re-try at a later time. How much later depends on the implementation preferences. 

I believe there is nothing else the device can do.

**Comment by boaks** [comment]
> attempts to perform the “Register” operation with LWM2M Servers have failed.

OMA-TS-LightweightM2M-V1_0-20170208-A, 5.2.3.3, still contains that definition to trigger a client initiated bootstrap. And my concern is still, that this will cause a LOT more bootstraps than intended.
