### ISSUE TITLE
Client Registration Interface and Bootstrap Interface with SMS Binding

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#146]
When the Binding Resource of the LWM2M Server Object is set to "S", "SQ", "US" or "UQS", the specification does not say anything about how should the SMS Binding be used with regard to the Client Registration Interface.

It is obvious that when the current Binding is "U" or "UQ", the Register message shall be transmitted via UDP.

When the current Binding is "S" or "SQ", it would seem natural that the Register message shall be transmitted via SMS. However, the specification seems to contradict this assumption with the following clause:

> [5.3.1 Register, paragraph 3]
> Upon receiving a “Register” operation from the LWM2M Client, the LWM2M Server records the IP address and port from the IP packet of the registration message and uses this information for all future interactions with that LWM2M Client.

For a message sent over the SMS Binding, there is no IP packet nor IP address, so it would be impossible to record it. Additionally, the "SMS Number" Registration parameter would then be partially superfluous, as the server could just record the originating phone number of the message.

Matters are even further complicated when the current Binding is "US" or "UQS". In such case, the Client has two independent channels over which it can potentially send the Register message. Considering the clause quoted above, it would seem natural to send the Register message over UDP, to let the Server record the IP endpoint information - it would also provide a natural meaning for the "SMS Number" Registration parameter. However, it is not explicitly said anywhere in the specification. It may even sound plausible to send two Register packets, one over each transport.

What is the correct way to send Register messages when current Binding is set to "S", "SQ", "US" or "UQS"?

Similar concerns may be raised about the Update message - should it be transmitted over the same binding that the Register message has been? Or is there any case when the Update message may be transmitted over a different transport in different circumstances?

Also, assuming that the Register message shall be sent over SMS for Binding modes "S" and "SQ" - how should a change of Binding e.g. from "U" to "S" be handled? Should the device just send the Update message over SMS, even though all the previous updates were sent over UDP?

Finally, can SMS Binding be used with the Bootstrap Interface? Client Initiated Bootstrap and Server Initiated Bootstrap require a Bootstrap Server Account - which is an instance of the Security object. There is no way to specify a binding mode there. Is it, however, still possible for the Bootstrap Server to perform Server Initiated Bootstrap over SMS if the Bootstrap Server Account contains its MSISDN and the Client is reachable via telephone network? Client Initiated Bootstrap over SMS doesn't seem possible at all - is it intentional?

I believe all of these issues need explicit clarification in the document.

**Comment by HAli786** [comment]
I agree with you. The server initiated bootstrap should allow MSISDN because SMS is the only trigger available to reach out to the UE in the field if UE fails to register or bootstrap on its own.

**Comment by dnav** [comment]
The Binding Mode is an indication of the Client capabilities to the Server.
A Server account contains only one URI which is either using UDP or SMS. Thus the Client can only contact a Server through one channel.
 

> [5.3.1 Register, paragraph 3]
Upon receiving a “Register” operation from the LWM2M Client, the LWM2M Server records the IP address and port from the IP packet of the registration message and uses this information for all future interactions with that LWM2M Client.

This will be updated in the next TS.

**Comment by kFYatek** [comment]
So, does that mean that the "US" and "UQS" bindings are being removed?

**Comment by dnav** [comment]
Not at all. It is useful in a multi-server set-up.

**Comment by kFYatek** [comment]
So, what does your statement that "A Server account contains only one URI which is either using UDP or SMS" mean? What is the format for an SMS "URI"? And how does it work given the requirement in the specification that it has to be a `coaps://` or (`coap://` for NoSec) URI?

**Comment by dnav** [comment]
So let's consider a Client with a Bootstrap Server Account and a LWM2M Server Account. Both with UDP based URI.
The Client registers to the Server with an "US" binding.
The LWM2M Server can say to Bootstrap Server: "Look, this Client has an SMS binding, please provision the SMS LWM2M Server account to him."
The Bootstrap Server complies and the Client is then registered to two Servers: one over UDP and one over SMS.

**Comment by jpradocueva** [comment]
Wojciech will provide some recommendations based on Pittsburgh feedback.

**Comment by jpradocueva** [comment]
**DM provided the following comment:**
What is the correct way to send Register messages when current Binding is set to "S", "SQ", "US" or "UQS"?
It is clear that "S" and "SQ" always uses SMS.
"US" and "UQS" the client can select UDP or SMS.

Similar concerns may be raised about the Update message - should it be transmitted over the same binding that the Register message has been?
That must use the same binding as the Register message.

Also, assuming that the Register message shall be sent over SMS for Binding modes "S" and "SQ" - how should a change of Binding e.g. from "U" to "S" be handled?
Change of binding is not possible for the same session.

Finally, can SMS Binding be used with the Bootstrap Interface?
Bootstrap is independent of the binding as bootstrap is not session related.

The group answered the questions found in the comment; if there is any additional question please clarify in a new issue.

**Comment by kFYatek** [comment]
> Change of binding is not possible for the same session.
What action should the Client take after a Write to the /1/*/7 (Binding) Resource? That Resource is defined as writeable and "S" may indeed by written there when the current value is "U".

**Comment by jpradocueva** [comment]
**DM provided the following comment:**

* This is implementation dependent and not included in the specification, but the logical behavior (assuming the write was successful - i.e. the binding mode was supported by the client) is that the client will tear down any existing session and establish any new session using the new binding mode.

**Comment by kFYatek** [comment]
> the client will tear down any existing session and establish any new session using the new binding mode

Just to be sure, this essentially means a De-register followed by a new Register message, right?

**Comment by MDadas** [comment]
You are right but please note that De-registration is optional.
