### ISSUE TITLE
Exact meaning of "MSISDN"

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#148]
With regard to the SMS Binding, the specification refers to the term "MSISDN" numerous times, notably in section 5.3.1 (the "SMS Number" Registration parameter) and section E.1 (LWM2M Object: LWM2M Security, Resource 9 "LWM2M Server SMS Number").

The specification makes no reference to a normative source for the term.

It would seem natural to assume the definition introduced in 3GPP TS 23.003, section 3.3 "Structure of MS international PSTN/ISDN number (MSISDN)", which defines an MSISDN as basically an international phone number without neither any international dialing prefix nor the "+" sign.

However, the term does not have a universally accepted strict meaning, and some sources and specifications out "in the wild"<sup>[[1]](#kfy-ticket-ftnote-1)[[2]](#kfy-ticket-ftnote-2)</sup> seem to use the term MSISDN to refer to a number starting with the "+" sign, or to just a phone number in common usage in general - such interpretation would make some sense, as it would allow using national numbers for LWM2M SMS Binding.

I believe this is worth specifying precisely - adding a normative reference for the "MSISDN" term and perhaps adding an example that would demonstrate its correct format.

Footnotes:
- <a name="kfy-ticket-ftnote-1">1</a>: [MobAd Technical Specification - Core Specification](http://technical.openmobilealliance.org/Technical/release_program/docs/MobAd/V1_0-20100408-C/OMA-TS-MobAd_Core-V1_0-20100408-C.pdf)
- <a name="kfy-ticket-ftnote-2">2</a>: [RESTful Network API for 
  Anonymous Customer Reference Management](http://technical.openmobilealliance.org/Technical/release_program/docs/REST_NetAPI_ACR/V1_0-20130625-C/OMA-TS-REST_NetAPI_ACR-V1_0-20130625-C.pdf)

**Comment by kFYatek** [comment]
Just a little update: I just spotted that Figure 25 (under section 8.4 "Update Trigger Mechanism") shows an example message flow displaying `SMS=%2B12345678` in the Registration message query string, which would suggest that the proper syntax of "MSISDN" as used in LWM2M includes the "+" sign.

I'm not sure whether such relatively obscure example diagram can be interpreted as normative, but it seems to be the only reference throughout the entire TS. I haven't previously found it, as, being a bitmap image, it's not searchable when browsing through the document.

**Comment by fdur** [comment]
From my point of view, this resource is in string format. the "+" sign could be considered as mandatory because it's the international prefix. This prefix is an international one. Else, each countre can have a diffrent prefix. In France "+" = 00. but in the US, if I don't make any mistake, "+" = 001

**Comment by FredRodermund** [comment]
Since SMS was designed by SMG/3GPP we might better stick with their definition of MSISDN as defined in TS 23.003 (which doesn't include the "+").
Any reason why we shouldn't clarify the LWM2M TS in that direction?

**Comment by jpradocueva** [comment]
DM to create a Change Request.
Figure 25 (under section 8.4 "Update Trigger Mechanism")
Remove + in the example
Do not use leading "00"

**Comment by jpradocueva** [comment]
Note has been added in section 8.2.4 that MSISDN must follow 3GPP TS23.003

Ticket to be closed
