### ISSUE TITLE
LWM2M Server Instances require LWM2M Security Instances

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#15]
A Device Management server is allowed to add new LWM2M Server Instances, for instance, to allow access to Service Enablement Resources for applications. However, LWM2M Security Instances can only be created/written through the Bootstrap Interface.

How should the Device Management server configure the security settings for new LWM2M Server Instances?

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
During the OMA Interim meeting (Sept 2016) this point has been discussed and the WG confirmed
that in TS 1.0 only the bootstrap Server has the capability to configure the security settings of a Server Instance.  In the  LWM2M 1.1 timeframe, this point could be reconsidered, especially if a strong use case is identified; please, could you create a  "LWM2M new requirement issue" for this ?  . many thanks

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 
Label "LWM2M new required" created and added 11-Oct-2016
