### ISSUE TITLE
Reporting errors during bootstrap

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#153]
Section 5.2.5 of the current TS 1.0 draft uses a lot of wording including the keyword MUST, essentially not considering any invalid or erroneous requests from the Bootstrap Server.

However, there are numerous cases when errors may happen and need to be handled, including:
- What should happen if the Bootstrap Server attempts to call BOOTSTRAP WRITE on an object or resource that is not implemented in any way in a given Client?
  - I have already talked about this problem in issue #140, and I have mentioned possible interpretations there.
- What happens if a BOOTSTRAP WRITE is issued that would create a new Instance of some Object, but does not specify some (or all) of that Object's Mandatory Resources?
  - Should it be allowed, leaving an object with an invalid state in the data model?
  - Should it be temporarily allowed, letting the Bootstrap Server to issue another BOOTSTRAP WRITE, creating the missing resources? If it fails to do so, it would then be handled in a transaction-like fashion, returning an error code upon receiving BOOTSTRAP FINISH.
  - Should it be rejected right away with an error code response to BOOTSTRAP WRITE?

**Comment by dnav** [comment]
Hi,

In both cases, the Client returns a 4.00 Bad Request error to the BOOTSTRAP WRITE command.
The second case Bootstrap Server does not comply with the LWM2M standard.

Regards

**Comment by ThGarnier** [comment]
In the final Bootstrap stage the inconsistent  configuration can now (Nov16 Release) be rejected 
by the Client (4.06 error code) with the Bootstrap Finish. Some "improvment" still coming :-)

**Comment by jpradocueva** [comment]
Agreed with DM Working Group to close.
