### ISSUE TITLE
Access Control configuration during Bootstrap

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#154]
The current revision of the TS 1.0 draft, section 7.3, defines an Access Control mechanism that is applicable when the LWM2M Client is configured to communicate with more than one LWM2M Server. Section 7.3.1.1 defines some rules for initial creation of the Access Control Object instances:

> - During the Bootstrap Phase, an Access Control Object Instance MUST be assigned per Object, for identifying which Server will be authorized to instantiate this Object later. The Bootstrap Server is the owner of these Access Control Object Instances created during this phase.
> - A unique Access Control Object Instance MUST be assigned per Object Instance (see Figure 16), for registering which operations can be performed by a given LWM2M Server on this associated Object Instance.

The specification does not, however, explicitly tell _when exactly_ during the Bootstrap Phase those instances need to be created, and whose responsibility it is. This is especially confusing when the bootstrap procedure is performed by the Bootstrap server (as opposed to Factory or Smartcard modes).

One possible interpretation is that the Access Control Object Instances may be created at the moment when the new object instances are created via BOOTSTRAP WRITE. This ensures that all required instances are present, but the Bootstrap Server then cannot reliably modify the ACLs, as their Instance Numbers are basically unknown and arbitrary - unless it first calls BOOTSTRAP DELETE on all existing ACL Instances, although that is confusing and inelegant, and also can be interpreted as putting the data model in an invalid state (somewhat related to what I described in issue #153).

So it seems that the Access Control Object cannot be automatically instantiated on object creation, to allow the Bootstrap Server to create new Access Control Object Instances from scratch. However, what should then happen on BOOTSTRAP FINISH? Should it be rejected if all required ACLs have not been instantiated? Or should the Client automatically instantiate the missing instances as necessary?

I believe that the correct behaviour needs to be explicitly described in the specification.

**Comment by ThGarnier** [comment]
yes, a discussion has just started on that topic  Bootstrap/ Multi-server Context (so Access Control)  for
cleaning it during next week  F2F meeting. keep in touch . Many thanks

**Comment by ThGarnier** [comment]
The simple way and certainly the main one in TS 1.0, is to start a new configuration from scratch, loading with the bootstrap commands the Server Account(s) , the Access Control Object Instances  with ACLs for Objects and Object Instances. In the release of November, the Bootstrap Finish will return an error code if the initial loaded configuration is not consistent. Maybe it will answer your question, please wait for that release; what is your real use case ?

**Comment by kFYatek** [comment]
The spec revision from November 10th resolves a lot of issues, but one case is still not exactly clear:

If the Bootstrap Server instantiates a multi-server environment and instantiates possibly _some_ of the relevant Access Control Objects, but not _all_ of them - should the remaining objects be automatically instantiated by the Client, or should it be treated as inconsistency, resulting in an error response to Bootstrap Finish?

**Comment by jpradocueva** [comment]
Agreed with DM Working Group to close.
