### ISSUE TITLE
Unit of SMNC (4/0/9)

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#156]
In OMA-TS-LightweightM2M-V1_0-20160407-C,
The unit of SMNC (4/0/9) was "%". 
Because SMNC is a code, the unit should be empty.

**Comment by fdur** [comment]
Fixed by OMA-DM-LightweightM2M-2016-0166R01-CR_Various_Simple_Fixes
To be closed
OK from 20161031 version
