### ISSUE TITLE
BS deletes all instances scenario

### ISSUE THREAD

**Issue by gilbaruch77** [OpenMobileAlliance/OMA_LwM2M_for_Developers#157]
When BS deletes using / , what is the expected behavior from device regarding handling objects such as 3 (there are resources that are read only)?

**Comment by ThGarnier** [comment]
The BS is God ;-),  delete / erase everthing exept the BS Account . (sect 5.2.5.2)

**Comment by softgearko** [comment]
@TheGarnier I think mandatory object instances such as 3/0,4/0, or 5/0 should not be deleted by DELETE / from BS. Else, BS have to send create all object instances messages.

**Comment by gilbaruch77** [comment]
Following to the discussion with OMA forum on Oct 26th, it seems that there is no clear answer. 
When Bootstrap server deletes the client's static information such as firmware version or sensor resources, who is responsible to retrieve it and when? 
Does it it make sense/have a meaning at all that Bootstrap server will ask to delete the client's static resources?

**Comment by fdur** [comment]
I noticed an issue about this: object 9
Object 9 is for Software update: one object instance for each embedded software.
If the client connects to the bootstrap, then DELETE on / is received ... which means that all object instances of object 9 need to be deleted ... which may indicate that all software need to be uninstalled ...
Correct ? :)

**Comment by jaimejim** [comment]
To my understanding, deleting Objects 3,4,5,6 and 7 does not make so much sense. 
Wouldn't it delete simply all information related to management servers (i.e. objects 0,1,2)?
Any new thoughts?

**Comment by jaimejim** [comment]
Right now the effect of a Bootstrap Delete is referenced on section 5.2.7.5:
"When the Delete operation is used without any parameter (i.e. without Object ID parameter), all Instances of all Objects in the LwM2M Client MUST be removed (except for the two cases mentioned above); this functionality could be used for initialization purpose before LwM2M Bootstrap-Server sends Write operation(s) to the LwM2M Client."

and on section 8.2.3:
"Only in Bootstrap Interface, Delete operation MAY target to “/” URI to delete all the existing Object Instances - except LwM2M Bootstrap-Server Account - in the LwM2M Client, for initialization purpose before LwM2M Bootstrap-Server sends Write operation(s) to the LwM2M Client."

For now that information will have to suffice. The reading is that with DELETE "/" you are deleting all device configuration in very exceptional cases. It does not really apply to sensor measurements -IPSO Objects- or for the Device Object. 

We will address this topic back again on 1.1.

**Comment by fdur** [comment]
I think that this case really needs to be well documented in 1.1 spec version.
Especially for object 9.
If a DELETE command is received on / from the BS server, I'm not sure that all installed applications (linked to all instances of object 9) need to be uninstalled ... (FMPOV DELETE cmd on one instance of object 9 means an application uninstall)

**Comment by hannestschofenig** [comment]
If this issue is still valid, please re-issue it against the LwM2M v1.1 release.
