### ISSUE TITLE
In BS, a client sends error for PUT /0/1 with empty values for resource 3,4,5.

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#159]
We are under Testfest. We just need to clarify this issue. a client implementer think a server's message problem. however, the server implementer think the client's problem.
This is the flow:
Client   -  BS
m1: POST /bs --->
m2 : <--- 2.04 
m3: <--- DELETE /
m4: 2.02 --->
m5: <--- PUT /0/0
m6: 2.04 --->
m7: <--- PUT /0/1
**m8: 5.00 --->**
m9: <--- PUT /1/0
m10: 2.04 --->
m11: <--- POST /bs
m12: 2.04 --->

The client sent 5.00 internal server error(m8 above) for BS's PUT /0/1 request(m7). PUT /0/1 message(m7) has zero size values for  3,4,5 resource(public, server public key, secret key). In detail, for resource 3, TLV message is encoded as  C0 03 (lengh=0). 
The client implementer think these resources are mandatory and these resources should have values.  the server implementer think this is client's implementation problem and  zero-length value is possible for 3,4,5 resource when no-sec mode.

**Comment by dnav** [comment]
In my opinion a zero-length value is a value. And I would consider the Server's command as valid.

Regards

**Comment by github-oma** [comment]
The suggestion during the TestFest/OMA group meeting was to split the test case  to capture (mandatory/optional) and make clear in the past criteria section what result should be expected.

**Comment by dnav** [comment]
This issue has been addressed in LwM2M v1.0
