### ISSUE TITLE
Requests sent in the middle of Register message exchange

### ISSUE THREAD

**Issue by dextero** [OpenMobileAlliance/OMA_LwM2M_for_Developers#162]
Let's consider following case, assuming CoAP Piggybacked Responses are used:

```
LWM2M                                       LWM2M
CLIENT                                     SERVER
  | --------------- Register ---------------> |
  | <-------------- Read /3/0 --------------- |
  | ------------------ ??? -----------------> |
  | <--- 2.01 Created (Register response) --- |
```
1. Is the LWM2M server allowed to make any requests to the client before sending a response to the received Register?
2. What is the expected response ("???" in the case pictured above)? Should the client respond to such requests before the registration is confirmed, return an error, or send CoAP RST?

**Comment by boaks** [comment]
see issue #7

**Comment by boaks** [comment]
even if the server send the read after the created, in UDP there is no garantee, that the client receives than the read after the created. 
There are different possible solutions (my favorite is from dnav), but without clarification, which solutions is chosen, I can't see, that it works interoperable.

**Comment by dnav** [comment]
This issue will be addressed in the next TS.

Regards,

**Comment by jpradocueva** [comment]
Agreed with DM Working Group to close.
