### ISSUE TITLE
Firmware Update State changing from Idle to Downloading Timing

### ISSUE THREAD

**Issue by gilbaruch77** [OpenMobileAlliance/OMA_LwM2M_for_Developers#163]
When the client receives Package or Package URI , should it change State to Downloading right away or only when the downloading process starts (meaning State will be still Idle until downloading starts) 

Thank you

**Comment by juanjperez** [comment]
The state should change to 'Downloading' when the client receives the Package or Package URI.

**Comment by hannestschofenig** [comment]
As Juan correctly noted, the state transition changes from Idle to Downloading when the client receives a Package or a Package URI. In the case where the firmware is written from the server to the Package resource the story is clear anyway. For the case where the client receives the URI first and then has fetch the firmware image from the indicated located there is a short delay before the package download starts but this delay is not exposed in the currently defined state machine.
