### ISSUE TITLE
What happens when IP address changes during Bootstrap?

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#164]
When an LWM2M Client is in the process of exchanging Bootstrap Interface messages with the Bootstrap Server, and the underlying network connection is lost - what is the expected behaviour?

The Client device will probably get a new IP address from a DHCP server or a similar source, and so the endpoint onto which the Bootstrap Server was sending Bootstrap Interface RPCs will no longer be valid.

Should the Client send the REQUEST BOOTSTRAP message again? Should it do so only if the connection was lost during a Client-Initiated Bootstrap, or would it make sense to do so to inform the server of the new endpoint even if the process was Server-Initiated before the connection loss?

**Comment by dnav** [comment]
In a Server Initiated Bootstrap, the Bootstrap Server is informed of the Client availability by out-of-band ways, typically the network infrastructure. In this case, the Bootstrap Server can cope with the Client network issues.
In a Client Initiated Bootstrap, the Client should send again the boostrap request as it is the only way for the Bootstrap Server to know the Client's new address.

Regards

**Comment by hannestschofenig** [comment]
I agree with David. The question is whether we need to clarify this issue in the specification.

**Comment by hannestschofenig** [comment]
If the bootstrap operation fails then the client may re-initiate the bootstrap procedure. However, it is an implementation dependent policy what the client does, when he initiates the next bootstrap interaction and how long it keeps trying.
