### ISSUE TITLE
Bootstrap server writing to optional resource which is not supported by the client

### ISSUE THREAD

**Issue by gilbaruch77** [OpenMobileAlliance/OMA_LwM2M_for_Developers#165]
What is the expected client behavior when Bootstrap server writes to optional resource which is not supported by the client (for instance to Server Default Minimum Period resource)?
Should the Client ignore the resource writing and report success?

**Comment by dnav** [comment]
Exactly. This is adressed in the next TS.

**Comment by hannestschofenig** [comment]
This issue has been addressed in LwM2M v1.0
