### ISSUE TITLE
Client bootstraped without all the supported resources

### ISSUE THREAD

**Issue by gilbaruch77** [OpenMobileAlliance/OMA_LwM2M_for_Developers#166]
What is the expected behavior from the client when bootstrap server does not include supported resource in the bootstrap writing?
Should the client disable that resource and not report it on discover interface?

**Comment by dnav** [comment]
If they are optional resources, yes. This is adressed in the next TS.

**Comment by hannestschofenig** [comment]
This issue has been addressed in the published LwM2M v1.0.
