### ISSUE TITLE
Bootstrap Information on UICC - unspecified endianness

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#167]
Section G.3.3, EF LWM2M_Bootstrap, defines a file format which is to be used for Bootstrap from Smartcard. It is defined to be a binary file, and its format is given in a BNF-like syntax. That syntax defines an entity called `HWORD` which is given as `%x00-FFFF` - however, the byte order for this 2-byte value is never explicitly given.

I assume that it shall be a Big Endian value (as all other multi-byte integers in the protocol) - however I believe it would be appropriate to explicitly specify whether the byte order is Big Endian, Little Endian or architecture-dependent.

**Comment by jpradocueva** [comment]
DM WG to review this Issue based on Pittsburgh feedback.

**Comment by ThGarnier** [comment]
yes you are right! the TS 1.0.1 will updated as follows (Appendix G3.3)  (last sentence): 
_The LwM2M specification already describes the TLV format for coding multiples instances and Resources of a given Object (§6.4.3), this section will only detailed how to store a collection of LwM2M Objects in this EF LwM2M_Bootstrap file; each Object is coded with a header containing a LwM2M Object ID and its Object Version coded in one or 2 Bytes, a LwM2M-TLV coding the Object Instances as payload, and a length being the size in bytes of this payload (LwM2M-TLV of the Object Instances)._ **Data are represented in network byte order (big endian).**
Thanks a lot
Th
