### ISSUE TITLE
Package URI in Firmware Update Object to be readable

### ISSUE THREAD

**Issue by mcocak** [OpenMobileAlliance/OMA_LwM2M_for_Developers#168]
Is there a specific reason why Package URI in Firmware Update object is only writable but not readable as well? This prevents the server to check in the future where the current firmware was downloaded from i.e. the server has no way to confirm the package URI later on. I think this resource should be both RW and this change will not affect the functionality of the resource.

**Comment by dnav** [comment]
Hi,
This resource is now Readable in the latest Technical Specification, OMA-TS-LightweightM2M-V1_0-20161123-D.doc.

Regards,
