### ISSUE TITLE
JSON Name in Response for GET resource request

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#173]
* OMA-TS-LightweightM2M-V1_0-20161123-D
* Section: 6.4.4, Page: 57

What should be Name value in the response for GET single resource (not Object or Object Instance)?
The TS said "when Base Name is not present, the default Base Name is the request URI".  If request URI is single resource, Name value should be empty, right?

For example,
```
Request:
GET /3/0/0
Accept: json

Response:
2.05
{"e": [
   {"n":"","sv":"Open Mobile Alliance"} 
] }
```

Which one is right for Name value in this case?
* "" :  empty value
* "/" : slash
* or else ?

**Comment by dnav** [comment]
Hi,
my understanding is that the name should have an empty value. This should be explicitely written in the TS.

Regards,

**Comment by ThGarnier** [comment]
Hum!!  Yes, the spec must be more explicit.
However, I don't think having a empty value is a good think (ambiguities / clarity).
My view is the following : we keep definition Name as it is   (Table 22)" The Name value .......The resulting name uniquely identifies the **Resource instance** from all others" 
=> however the second bullet could be changed (see below) but in still respecting the previous definition (text above):
**When Base Name is not present, the default Base Name is \/{Object}  or \/{Object}\/{Object Instance} according to the request URI. i.e:  if the request URI is \/{Object}/{Object_Instance} OR  \/{Object}\/{Object Instance}\/{Resource}, the array entry Resource Name will be  {Resource}\/{Resource Instance} **

That way : I think any ambiguities is then removed and the json description is clear :  
GET \/3\/0\/0  Accept: json 
will provide
Response:
 2.05
`{"e" : [
    {"n":"0","sv":"Open Mobile Alliance"}
]}`

Fixing the TS ambiguity that way will be proposed soon

**Comment by dnav** [comment]
Thing is this would contradict the SENML spec (https://datatracker.ietf.org/doc/draft-jennings-senml/) and would complicate the parsing.
I would prefer either make _Base Name_ mandatory or make _Name_ optional.

**Comment by ThGarnier** [comment]
Yes, you are definitively right :-) so the simplest way  for removing the ambiguity (and being compliant) is to remove the notion of default Base Name is the TS,  making the Name optional as well, and assuring the TS clearly says the concatenation of the Base Name and Name uniquely identifies a Resource Instance (whatever the Base Name and Name values) . So we'll  propose aTS  fix together in this way  :-)

**Comment by dnav** [comment]
Hi,

I just realized that the sentence "when Base Name is not present, the default Base Name is the request URI" is not part of any of the TS for LwM2M 1.0.x.
The TS states:
> •	when Base Name is not present, the **Array entry Name** is the full URI of the requested Resource Instance

Meaning that `{"e" : [ {"n":"0","sv":"Open Mobile Alliance"} ]}` is not a valid _application/vnd.oma.lwm2m+json_ payload. It should be: `{"e" : [ {"n":"/3/0/0","sv":"Open Mobile Alliance"} ]}`

Regards

**Comment by hannestschofenig** [comment]
Since the referenced text was removed in v1.0 I am going to close this issue.
