### ISSUE TITLE
Identifier Mix-up Security Attack with Bootstrap Interface

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#175]
Name, version and date of the document: OMA-TS-LightweightM2M-V1_0-20161123-D
Section of the document: Section 7.1.3 and Section 8.5

When a LWM2M server and a bootstrap server authenticate a LWM2M client they need to make sure that the identifier used during the DTLS handshake (such as the identifier in the client certificate) matches the endpoint name. 

This procedure is described and mandated for authentication of the LWM2M client to the LWM2M server. 

Unfortunately, the text and the error response code for the authentication of the LWM2M client to the bootstrap server is missing. (Compare the error code "Endpoint Client Name does not match with CN field of X.509 Certificates" with the Client Registration Interface in Section 8.5 with the error code available in the Bootstrap Interface. 

This is clearly a security problem. While implementations probably got this right it needs to be stated explicitly to avoid implementation flaws. 

The obvious fix is to update the text in Section 7.1.3 and Section 8.5 to ensure that the same procedure for LWM2M client authentication is used by the LWM2M server as well as the bootstrap server. 

Do others agree?

**Comment by jvermillard** [comment]
:+1:

**Comment by boaks** [comment]
So the complete text from `Client Registration Interface`, `Register`, `4.00 Bad Request` should be copied to the `Bootstrap Interface`, `Bootstrap Request`, `4.00 Bad Request` to make in consistent.

Also, a failing check for RPK (7.1.2) may be required to be added to the text. 
Errors in PSK or x509 trusting will end up in not being able to exchange messages at all. So a hint on that case may also be useful. 

Currently I'm not sure, how far the specification of the coupling of the DTLS layer to the registration interface is. Usually, considering "observe/notifies", a "Update" MUST be in the same DTLS session/epoch. If so, a violation of that should be mapped to the `Update` response code `4.00 Bad Request` also and therefore added to the text there. If the coupling is different (no need for same DTLS session/epoch because observe/notifiy is change or dropped), the text from above about the checks should also be added to the `Update` or it should explizitly state, that the spec. rely on the `location` to be secure on its own (I would not).
Same for "De-Register".

**Comment by boaks** [comment]
And let me rise my beloved question about the "DTLS role exchange" :-).

How should this work with x509, when the LWM2M server (no LWM2M endpoint name) is the DTLS client? What should be the "CN="s?

**Comment by hannestschofenig** [comment]
Hmmm. Good question.

**Comment by boaks** [comment]
I hope, you mean the questions and comments in my first answer.

The role exchange would work with certificates naturally. 
Both parties simply exchange their certificates and both check them according their trust and LWM2M roles.
But I still belief, "DTLS role exchange" will make more trouble, then it solves.

**Comment by sbernard31** [comment]
@boaks could you clarify which troubles this could make ?

**Comment by jvermillard** [comment]
> How should this work with x509, when the LWM2M server (no LWM2M endpoint name) is the DTLS client? What should be the "CN="s?

It should be the FQDN of the server. The same you will present when the device connect to the server

**Comment by boaks** [comment]
> @boaks could you clarify which troubles this could make ?

The "DTLS role exchange" only works under certain preconditions.
If these are not clear, the risc of interpret "failure in accordance with the spec"
into "failure" is the trouble I'm afraid. 

#2
contained a log of information, I'm not sure if the conclusion made it precise enough into the LWM2M TS.

**Comment by hannestschofenig** [comment]
The problem is the following: Imagine you have a device from company A and another device from company B. Both are managed by a bootstrap server. Both devices have unique, per-device credentials for use with DTLS.

Now, imagine that company A wants to sabotage the device used by company B. It uses its credentials during the TLS exchange. Then, it puts the endpoint name of the company B device. If the bootstrap server does not check whether the identifier provided in the DTLS handshake matches the identifier used at the application layer then it may be inclined to use the endpoint name for looking up what information (including keys) to provision to that device.

Once those keys and configuration information has been provisioned to the device of company A then it can start talking to the LWM2M server of company B. What the exact consequences are depends on the application. 

Does this help?

**Comment by hannestschofenig** [comment]
Regarding the question: 
> How should this work with x509, when the LWM2M server (no LWM2M endpoint name) is the DTLS client? What should be the "CN="s?

I think that both parties should use an FQDN in their cert. This means that the endpoint name will be an FQDN as well. Of course, running the DTLS server on the IoT device is much heavier than running it on the client and then there is also the additional attack surface as well. 

Of course, it would help if the spec talks about this in more detail. Who has implemented server-initiated bootstrap? We could ask them kindly to write some text...

**Comment by boaks** [comment]
So let me first say:
The LWM2M TS should not define IMPORTANT (I consider security to be important :-) ) behaviour only in the description of result codes!  It should state them more explictily.

1. If it's client initiate bootstrap, then the endpoint name is provided. And you are right, that this requires to be checked according 7.1. And, if the only intended hint to that should be the description of the reponse code, yes it must bo copied there. If alreday agreed.

2. If it's a server initiated bootstrap, the server must check the clients certificate, if this is the expected one and matchs the "assumed" device. So A can only presents A's certficiate and therefore shoudl only get A's data.

**Comment by boaks** [comment]
>  Of course, running the DTLS server on the `IoT device` is much heavier than running it on the `client`

Hm, I think the term `client` is somehow mixed up.

**Comment by boaks** [comment]
> Of course, it would help if the spec talks about this in more detail. Who has implemented server-initiated bootstrap? We could ask them kindly to write some text...

And 1 point more for specifyng a "server initiated bootstrap" just as trigger for a "client initiated bootstrap". It may be not impossible the specify it on its own, but it would make it easier to have it consistent to other aspects (security discuessed here, alternate path and object versioning discussed in other issues). It  would be just cost one more request/response pair.

**Comment by sbernard31** [comment]
>And 1 point more for specifyng a "server initiated bootstrap" just as trigger for a "client initiated bootstrap". It may be not impossible the specify it on its own, but it would make it easier to have it consistent to other aspects (security discuessed here, alternate path and object versioning discussed in other issues). It would be just cost one more request/response pair.

+1

**Comment by boaks** [comment]
The response code description s are not only in 8.5, they are also in 8.2.3 and 8.2.4.

So I would propose, to define the DTLS couling explizitly in s additional section and reference to that in the response code descriptions.

**Comment by hannestschofenig** [comment]
This issue was addressed in LwM2M v1.0.
