### ISSUE TITLE
Clarify DTLS behaviour in Bootstrap Interface

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#178]
OMA-TS-LightweightM2M-V1_0-20161123-D, 8.2.3

Doesn't contain information according DTLS like the Registratio Interface, 8.2.4

> When a new DTLS Session is started, or in NoSec mode when the LWM2M Client IP address changes, the Client MUST register again to the LWM2M Server.

(this is from 8.2.4, similiar should bein 8.2.3)

**Comment by hannestschofenig** [comment]
Are you suggesting that the client should re-initiate an exchange with the bootstrap server when the IP address of the client changes?

**Comment by boaks** [comment]
Sorry, my issue was missleading.
I just want, that the wanted behaviour should be specified. 
If the DTLS session is lost, the consequences should just be specified.

**Comment by hannestschofenig** [comment]
In LwM2M v1.1 we will address more error handling scenarios regarding DTLS and TLS.
