### ISSUE TITLE
Server-initiated Bootstrap is not ready for prime-time

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#179]
Name, version and date of the document: OMA-TS-LightweightM2M-V1_0-20161123-D
Section of the document: Section 5.2

The LWM2M says that "The LWM2M Bootstrap-Server MUST support Client Initiated Bootstrap and Server Initiated Bootstrap modes specified in the Bootstrap Interface."

Requiring the bootstrap server to support both modes is unrealistic for two reasons: 
1) There is very little implementation experience with server-initiated bootstrap.
2) Server-initiated bootstrap is under-specified and makes assumptions about the deployment environment, which are not commonly found. For example, it requires that the bootstrap server knows what client to contact and when. This assumes some reachability information to be configured in the bootstrap server, such as the IP address. 
3) It is heavy for IoT devices to implement since the IoT device needs to run a TLS server. 

I therefore recommend to lower the requirement for a bootstrap server and to only make client-initiated bootstrap mandatory to implement.

**Comment by boaks** [comment]
@hannestschofenig **TLS** server

Do you mean **DTLS**?

**Comment by dnav** [comment]
@hannestschofenig: 
In some network topologies, it is possible that the Server is informed of the presence of the Client and of its characteristics independantly of the LWM2M protocol. For instance in a mobile phone network, the operator infrastructure is aware of the end device registration.
Furthermore the Server-Initiated Bootstrap can occur at any time during the life cycle of the Client. The initial Bootstrap can be a Client-Initiated one. When required (e.g. LWM2M Server changes) the Bootstrap Server can start a Server-Initiated Bootstrap using the Client information from the first Bootstrap.
At LWM2M level, the only difference between Server-Initiated and Client-Initiated Bootstrap is that the latter starts with a Bootstrap Request message.
At DTLS level, it is true that "unexpected" Server-Initiated Bootstrap is resource-heavy for the device. However the TS does not mandate the Client to support all Bootstrap modes. 

Regards,

**Comment by hannestschofenig** [comment]
Correction: I indeed meant that the LWM2M client has to implement a DTLS server. 

David, I agree that there are circumstances where server-initiated bootstrapping is possible. The question is, however, whether this functionality is mandatory-to-implement. I argue that it should not. If it is mandatory to implement and most companies do not implement it since they don't have any customers supporting such a usage environment then we essentially have lots of products that are not compliant to the spec. That's not good IMHO. 

While there is little change from the LWM2M spec point of view but the impact for clients is huge. I also believe that the LWM2M spec is lacking details when it comes to the use of DTLS servers on the LWM2M client.

**Comment by jvermillard** [comment]
I would prefer to get rid of server initiated bootstrap and add something like a SMS for triggering the device into initiating a bootstrap.

**Comment by dnav** [comment]
@jvermillard : I don't get your point. For the Bootstrap Server, implementing Server-Initiated Bootstrap is straight forward as it is a subset of Client-Initiated Bootstrap.
For the device, Server-Initiated Bootstrap is not mandatory.
You can implement SMS trigger without breaking the LWM2M compliancy.

**Comment by hannestschofenig** [comment]
David, it makes little sense to require implementing server-initiated bootstrapping when companies prefer to use a combination of device wake-up functionality to trigger a client-initiated bootstrapping instead. 

Furthermore, the functionality for server-initiated bootstrapping isn't as easy as it sounds since the roles for client and for server are swapped. This means that the server-side in addition to the implementation of the TLS server now also has to use a client TLS stack.

To actually use this functionality in the wild one has to also implement server-initiated bootstrapping on the client side as well. This means that the device needs to respond to arbitrary requests. This increases the attack surface, as we have already seen with attacks against TR69. 

Furthermore, the device needs to implement a TLS server, which is more resource demanding than a client side implementation.

**Comment by boaks** [comment]
> For the Bootstrap Server, implementing Server-Initiated Bootstrap is straight forward as it is a subset of Client-Initiated Bootstrap.

Except, that the "implementation specific" part mentioned in 5.2.3.4 may not be `straight forward`.

**Comment by hannestschofenig** [comment]
In LwM2M v1.1 we are working on removing the server-initiated bootstrapping. This will also resolve the challenges with the reversed DTLS roles and the use of a DTLS server on the IoT device. 

Note: To help with the work you have to be OMA member.
