### ISSUE TITLE
LWM2M APIs

### ISSUE THREAD

**Issue by nginxsantos** [OpenMobileAlliance/OMA_LwM2M_for_Developers#182]
Where can I find RESTFUL OMA APIs for LWM2M Server?

**Comment by hannestschofenig** [comment]
The OMA LwM2M specification version 1.0, which is currently being worked on, standardizes the API between LwM2M client and the LwM2M server. 

The API used between the LwM2M server and application servers is outside the scope of the LwM2M version 1.0 specification. Vendors have defined their own APIs. As an example, here is the API from my employer ARM: https://docs.mbed.com/docs/mbed-device-connector-web-interfaces/en/latest/api-reference/

In general, there is still a lot of innovation and experimentation done by software developers to find out what the best possible API is. Hence, I believe it is too early to standardize an API between the LwM2M server and application servers.

**Comment by nginxsantos** [comment]
Thank you. Would you know if OMA has any plans of defining this. 

Regards, Santos

**Comment by hannestschofenig** [comment]
Currently version 1.0 of the specification is being finalized and discussions about features for version 1.1 have been going on for a while. We can add it to the wishlist and consider it when the work on version 1.1 goes ahead.

**Comment by nginxsantos** [comment]
Hi,

Thank you. Will 1.0 publish the APIs towards Application Servers?

Thanks. Santos

**Comment by hannestschofenig** [comment]
No, there are no such APIs defined in version 1.0.

**Comment by paaur** [comment]
I do not think DM WG has envisaged to work on APIs for LwM2M v1.1, this needs to be discussed in the WG and clarified. 

On the note of API, it is unclear what kind of features this API's is expected to perform, if these details are clarified , it would influence the discussion inside the DM WG
