### ISSUE TITLE
Conformance

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#186]
* Name, version and date of the document: OMA-TS-LightweightM2M-V1_0-20170111-D 
* Section of the document:B.1.8

The conformance section lists all sorts of objects in Appendix B.1.8. For example, the Connectivity Monitoring object can be found in there. When you look at the referenced Section E.5 then you see that it is optional. 

The notation is supposed to be explained in [SCRRULES], a non-existing reference. 

How should I interpret the conformance text in Appendix B.1.8?

**Comment by boaks** [comment]
> Appendix B.	Static Conformance Requirements
> The notation used in this appendix is specified in **[SCRRULES]**
> ...
> LwM2M-OBJ-004-**C**-**M**	Support of Device Object	Appendix E.4
> LwM2M-OBJ-005-**C**-**O**	Support of Connectivity Monitoring Object	Appendix E.5
> 

I guess, **[SCRRULES]** is just a missing reference and should be added in chapter 2.

(I hope, **C** is for client, **M** for mandatory, and **O** for optional.)

**Comment by hannestschofenig** [comment]
I am closing this issue since work has moved to LwM2M v1.1 and a conformance table will only be created early next year at the time when the specification gets completed.
