### ISSUE TITLE
Clarify intended usage of RFC7292/PKCS#12 information exchange

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#188]
OMA-TS-LightweightM2M-V1_0-20170111-D

> E.1.1.3 Certificate Mode
> The Certificate mode requires an X.509v3 Certificate along with a matching private key. The private key is stored in the Secret Key Resource, encoded using [RFC5958], as the private key in the RPK mode. The Certificate is encoded using the PKCS#12 format [RFC7292] in the Public Key or Identity Resource.

According RFC7292, section 3.1, PKCS#12 offers to "exchange information" in two modes, `Public-key privacy` and `Password privacy`. Is it really intended to use one of those modes? If so, please define, how this is intended to be used? So should there be a "Password" exchange prior to the bootstrap, which then provides the information in RFC7292? If this is not intended, define, which parts (subset) of RFC7252 are intended to be used.

My impression is, that RFC7292 is just **too** much. 
If RFC5958 is used for the private key, consider to use RFC5280/RFC6818 for encoding the certificates.

**Comment by hannestschofenig** [comment]
When we discussed the lack of description regarding the encoding of the security related fields I suggested something but go no feedback from any other member. 

I am fine with mandating DER encoded binary certificate, as defined in RFC 5280.

**Comment by boaks** [comment]
@hannestschofenig 

Thanks for your fast answer.
It's good to know, that I'm not the only one, who feel, that PKCS#12 may be strange :-)

**Comment by hannestschofenig** [comment]
Here is the CR: 
   http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2017/OMA-DM-LightweightM2M-2017-0032-CR_certificate_encoding.zip

**Comment by boaks** [comment]
Thanks! So I hope, the other members agree.

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20170208-A
