### ISSUE TITLE
Add "TEMPORARY NOT POSSIBLE" to FirmwareUpdate / Update Result

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#189]
OMA-TS-LightweightM2M-V1_0-20170111-D, E.6

Sometimes a device may reject a "download" or "execute update", because it has a "higher priorized" task. Currently such devices must report an error, which may be missinterpreted. Adding a new value "Temporary not possible" to resource 5 "Update Result" would allow a device to indicate, that generaly the action could be repeated successful in the future.

**Comment by ovidiu-usturoi** [comment]
Regarding the "Temporary not possible" status what will be the behavior:
1. If the procedure is not stated, probably everything will be ok.
2. If the procedure is stopped during the firmware upgrade, my recommendation is to add also a timeout for the next request (send the next packet after xx seconds, or something similar).

**Comment by hannestschofenig** [comment]
This is a new feature request for the firmware update mechanisms in LwM2M v1.1. If you care enough, join the OMA DM group and join us with the work on the new version.
