### ISSUE TITLE
Reference to PKCS#15 broken

### ISSUE THREAD

**Issue by hannestschofenig** [OpenMobileAlliance/OMA_LwM2M_for_Developers#190]
* Name, version and date of the document: OMA-TS-LightweightM2M-V1_0-20170113-D.zip
* Section of the document: Appendix G

The URL included in this reference is broken: 

[PKCS#15]	“PKCS #15 v1.1: Cryptographic Token Information Syntax Standard”, RSA Laboratories, June 6, 2000. URL:ftp://ftp.rsasecurity.com/pub/pkcs/pkcs-15/pkcs-15v1_1.pdf

It needs to be replaced with something else.

**Comment by ThGarnier** [comment]
Maybe just verify if your company accepts to access ftp sites.  The link itself seems not broken

**Comment by boaks** [comment]
@ThGarnier 

I tried the FTP URL from the office and from my private PC at home.
In both cases I couldn't fetch the document.

> 550 Requested action not taken. File unavailable.

I can browse `ftp://ftp.rsasecurity.com/`, but I can't see (and therefore fetch) any document.

So would it be possible, that you check the link also from a home PC?

**Comment by hannestschofenig** [comment]
Would this be a more appropriate reference: http://www.rsacertificate.com/emc-plus/rsa-labs/standards-initiatives/pkcs-15-cryptographic-token-information-format.htm

**Comment by hannestschofenig** [comment]
PKCS#15 is not used in the LwM2M specification anymore.
