### ISSUE TITLE
No Resource ID 4 at LwM2M Object Firmware Update

### ISSUE THREAD

**Issue by JosephJHCho** [OpenMobileAlliance/OMA_LwM2M_for_Developers#194]
OMA-TS-LightweightM2M-V1_0-20170208-A , E.6 LwM2M Object Firmware Update

There is no resource ID 4. 
Some resource to be added is missed?
OR
Just resource ID is mistyped?
Is it correct to change  4 for Update Result, 5 for PkgName, 6 PkgVersion, etc. ?

**Comment by ThGarnier** [comment]
The TS is correct and your reading as well : the Resource ID:4 has been removed with no replacement. 
It is not so nice, but ... as it is !!
So no change, no shift for the other existing Resources : just a hole.  e.g.  Update Result is still ID:5 ....
Th

**Comment by JosephJHCho** [comment]
I got it. Thank you.
