### ISSUE TITLE
Bootstrap-Server Account Timeout with Factory/Smartcard Bootstrap

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#195]
I'm referring to the official 1.0 spec (OMA-TS-LightweightM2M-V1_0-20170208-A).

The Bootstrap-Server Account Timeout (`/0/*/12`) Resource is defined in section E.1 as:
> The LwM2M Client MUST purge the LwM2M Bootstrap-Server Account after the timeout value given by this resource.

This definition does not specify the reference time for this timeout value, but more specific context is given in section 5.2.3.3 (Client Initiated Bootstrap):
> Step #3: Clean-up after successful Bootstrapping
>
> Successful Bootstrapping means that the Bootstrap-Finish command has been received by the LwM2M Client, AND the loaded Configuration is considered consistent by the LwM2M Client, i.e. the Bootstrap-Finish response code sent to the Bootstrap-Server is 2.04 (Changed); [...]
>
> If the Bootstrap-Server Account Timeout Resource is instantiated in the Security Object Instance of the Bootstrap-Server, the LwM2M Client MUST purge the LwM2M Bootstrap-Server Account after the expiration time provided by the value of this Resource. [...]

Also, section 5.2.3.4 (Server Initiated Bootstrap) refers to "procedures of the step#1 step#2 and step#3 specified in the LwM2M Client Initiated Bootstrap mode", so the definition described above also applies to Server Initiated Bootstrap. This is all clear so far.

However, there are also Factory Bootstrap and Bootstrap form Smartcard modes. It seems that there is nothing that would forbid e.g. the Bootstrap Information on Smartcard from containing a Bootstrap-Server Account, in addition to regular Server Accounts. How should the Client treat the Account Timeout resource in such case, after a successful Bootstrap from Factory or Smartcard (i.e. after successfully registering with some regular LwM2M Server)?

**Comment by jpradocueva** [comment]
DM WG to review this Issue based on Pittsburgh feedback.
Additional description could be added to the specs.

**Comment by jpradocueva** [comment]
The DM group has agreed the following comment on this topic:

This purge procedure is not applicable for factory bootstrap or smart card bootstrap.
