### ISSUE TITLE
TLV for large objects in resource constrained nodes

### ISSUE THREAD

**Issue by joakimeriksson** [OpenMobileAlliance/OMA_LwM2M_for_Developers#196]
The TLV format was designed with resource constrained embedded devices that normally come with small buffers and therefore need to use CoAP BLOCK transfer. But the problem is that when objects are quite large and the server requests a complete object with all its instances it is required to generate a full object representation as the first TLV is a TLV object instance TLV that includes Type, ID and length of the whole TLV - e.g. the full object instance representation. This means that the whole instance representation needs to be generated by either methods:

*  stored in a large buffer (and then sent)
*  everything is "locked" and the object instance is visited twice - once for getting size, and then for outputting the result.  

What is the best suggested approach here that a very resource constrained device should use?
The object can in theory be very very large (e.g. 16.7 MB) and how do you stream such an object - I would like to avoid locking the whole object and process it twice?

I can really see that object can contain a lot of data but I can not see how to create a good set of TLVs for them when exporting them via TLVs.

**Comment by joakimeriksson** [comment]
Ping! Anyone using TLVs on resource constrained devices - or is this a uninteresting topic?

**Comment by ovidiu-usturoi** [comment]
Hi Joakim,

Centero (centerotech.com) is using TLV data format for constrained devices.

Regards,
Ovidiu

**Comment by joakimeriksson** [comment]
Yes, but the TLV format itself requires anyone using it to know beforehand how big the data will be. We have also done Block transfers with large datasets but given let say a few KB data in a complex object with many resources you will have to first calculate the size your outer TLV will be before you start to produce the first CoAP blocks of TLV data. This is a bad design on resource constrained devices that need to produce the data as they stream it.

**Comment by martino-tlt** [comment]
Hi, this is an implementation choice as both options you describe look valid.
Local buffering before streaming sound recommendable and easier to implement. although memory is the most common constraint. If that’s the case, sizing the object and then “locking” it while sending data is probably the only option when you have limited storage capabilities.
You might also consider further optimizations on the server and how the objects are treated, e.g. force the server to read instances separately.
We don’t think the raised issue has an impact on LwM2M specifications and requires changes to current Techincal Specifications. But feel free to propose an optimization for version 1.1.

**Comment by joakimeriksson** [comment]
Ok, so we should target 1.1 specification for new optimisations for the TLV format then?! I do think that there some possible options. Will consider writing a suggestion as the TLV format will still be the default in the future I guess?

**Comment by hannestschofenig** [comment]
You should definitely target new optimized formats for v1.1 since no new functionality will be added to LwM2M v1.0.x. Of course, in the solution space they may be multiple options and potentionally you could make use of some other format, such as SenML or CBoR instead. That's something you are better able to judge.
