### ISSUE TITLE
Group communication

### ISSUE THREAD

**Issue by moleike** [OpenMobileAlliance/OMA_LwM2M_for_Developers#198]
This is a more general question.

There is RFC 7390 for CoAP [group communication](https://tools.ietf.org/html/rfc7390) based on IP multicast. Are there plans/discussions to add something based/related to that in the LwM2M protocol?

Thanks.

**Comment by Echo-xubei** [comment]
We have discussed the group multicast requirement in OMA DM. DM will plan this feature after 1.1 of LwM2M.
