### ISSUE TITLE
5.2.3.4 Figure 8: Procedure of Server Initiated Bootstrap, arrow direction typo

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#199]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS-LightweightM2M-V1_0_1-20170405-D, OMA-TS-LightweightM2M-V1_0-20170208-A
* Section of the document, ``(e.g. section: 6.2)``:  5.2.3.4
* Sequence of exchanges between Client and Server ``(if any)``:     C <- Bootstrap Write,Delete, Discover <- BS
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``: 
``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

In Section 5.2.3.4, Figure 8, The arrow of 'Write, Delete Discover Bootstrap" from LwM2M client to LwM2M Bootstrap server should be switched. I think it is a typo.
It should be; 
   C <- Bootstrap Write,Delete, Discover <- BS

**Comment by ThGarnier** [comment]
Yes :(   thank you : recent typo !! fix coming soon
Th

**Comment by ThGarnier** [comment]
should have been closed for a long time . TS 1.0.1
