### ISSUE TITLE
OMA LWM2M 1.0 - figure 11 in the TS (2017-02-08A)

### ISSUE THREAD

**Issue by joakimeriksson** [OpenMobileAlliance/OMA_LwM2M_for_Developers#200]
I am looking at the registration behaviour and the update. The spec says that all object and instances should be listed in the update whenever there was a change to the list. But the figure seems to have a typo as it do still list /12/1 as available even if it just was deleted in the previous operations (that was successful). Instead the /12/2 is gone. From my understanding the list should be:
`</1/1>,</3/0>,</12/0>,</12/2>` instead of `</1/1>,</3/0>,</12/0>,</12/1>,` which is in the specification right now.

This is on the 1.0 specification (2017-02-08A TS).

**Comment by ThGarnier** [comment]
good eyes :-)  Thanks . Fix coming

**Comment by ThGarnier** [comment]
Fixed in the 2017 Spring Specification

**Comment by joakimeriksson** [comment]
good to hear!
