### ISSUE TITLE
Figure 25,26,27 ACK_TIMEOUT to MAX_TRANSMIT_WAIT

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#201]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS-LightweightM2M-V1_0-20170208-A
* Section of the document, ``(e.g. section: 6.2)``: section 8.3
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:
``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

The description of Queue Mode Operation in Section 8.3 recommend MAX_TRANSMIT_WAIT for waiting. However, In Figure 25, 25, and 27, ACK_TIMEOUT are used.  I think they should be changed to MAX_TRANSMIT_WAIT instead of ACK_TIMEOUT in figures.

**Comment by fdur** [comment]
See also https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/98#issuecomment-256587347

**Comment by sandeepakhouri** [comment]
figures have been updated to address #98 and will be available as part of TS 1.1
