### ISSUE TITLE
Figure 27 POST /1/x/8, arrow direction typo

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#202]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS-LightweightM2M-V1_0-20170208-A
* Section of the document, ``(e.g. section: 6.2)``: 8.4
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:
``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

In figure 27, The arrow, POST /1/x/8 (Update Trigger), should be from Server to Client.

**Comment by sandeepakhouri** [comment]
This is fixed as part of 1.0.1
