### ISSUE TITLE
KiloBytes as 1000 or 1024 bytes?

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA_LwM2M_for_Developers#203]
* OMA-TS-LightweightM2M-V1_0 A
* Section of the document: E.8 LwM2M Object: Connectivity Statistics

Tx Data and RX Data are expressed in KiloBytes, some developer use 1KBytes => 1000 bytes, some other 1024 bytes.

Would be nice to address this confusion

**Comment by jvermillard** [comment]
Same issue on /3 memory resources in KB

**Comment by hannestschofenig** [comment]
We should reference RFC 7228 (see https://tools.ietf.org/html/rfc7228) and use the terminology there: 

"
   In this document, the term "byte" is used in its now customary sense
   as a synonym for "octet".  Where sizes of semiconductor memory are
   given, the prefix "kibi" (1024) is combined with "byte" to
   "kibibyte", abbreviated "KiB", for 1024 bytes [ISQ-13].
"

This seems to be inline with what others are doing.

**Comment by jvermillard** [comment]
by using kilobytes is it clear for everyone that this resource should contain the number of bytes divided by 1000

**Comment by hannestschofenig** [comment]
I think the solution is to indicate what we mean by putting text in the terminology section with a reference to Wikipedia: https://en.wikipedia.org/wiki/Kilobyte. If the group believes that the text meant kilobyte, which is 1000 bytes, then we should go for it. 

I will put respective text in LwM2M v1.1

**Comment by hannestschofenig** [comment]
I submitted a pull request for LwM2M v1.1
