### ISSUE TITLE
Observe and notification of resource after PUT

### ISSUE THREAD

**Issue by raviinroorkee-7** [OpenMobileAlliance/OMA_LwM2M_for_Developers#208]
Should client send the notification of a resource value change which is under observation and has been updated by write operation (PUT) by LWM2M server ?

**Comment by ovidiu-usturoi** [comment]
From my point of view, this is more like vendor specific. 
My approach is that any change of the resource value should be notified if the resource is under observation.  Into a complex system, a client can have multi-server support and the value could be changed by another server.  Adding write method validation  (over the air write - by the current server or another server - versus the internal resource change mechanism) introduce a new complexity in the client side.

**Comment by jhorvath2017** [comment]
Thank you for your comments. If you’re observing a resource you would want a notification any time there is a change. That said, the working group is discussing whether to specify, in 1.1, that this is a requirement (as opposed to being left to the solution provider to determine if they want it for their specific implementation) and if so, whether it would be configurable. Additionally if it is determined that it should be configurable, defining how it should be configurable.

**Comment by hannestschofenig** [comment]
If this issue is still valid, please re-issue it against the LwM2M v1.1 release.
