### ISSUE TITLE
Response for Update trigger PUT 1/x/8

### ISSUE THREAD

**Issue by raviinroorkee-7** [OpenMobileAlliance/OMA_LwM2M_for_Developers#209]
When submitting an issue please indicate the following information:
* Name, version and date of the document - OMA-TS-LightweightM2M-V1_0-20170208-A
* Section of the document, : 8.4

As per UPDATE TRIGGER MECHANISM , server can make client to sedn Registration Update by send PUT /1/x/8. However , Its not clear that if binding mode is set to "U"  then is it possible that server can trigger this request ? or it is meant only for "UQS" mode ?.

In any case ,as PUT /1/x/8 is execute operation , should the response of this request is required to be sent after response of Registration Update ? As result of PUT 1/x/8 is success/fail depends on result of Registration Update.

**Comment by ovidiu-usturoi** [comment]
My understanding is that the response of Execute command is a confirmation that the device receives the request and confirms that the command can proceed or not. 
The effect of the request should be treated separately. If in this case, the registration update will not come, the server should take the decision to deregister or not the client.

**Comment by fdur** [comment]
This point is not really clear but it's not linked to EXEC on /1/x/8 but on EXEC command itself.
If 2.04 is returned by a client on an EXEC command, the meaning is "Changed" ... so it may imply that the treatment is over, fully treated ...

Simple use case: EXEC on /3/0/12: reset error code
More complex use case: EXEC on /3/0/4: Reboot
If the 2.04 response linked to the EXEC command needs to be sent after the exec command treatment, for reboot case, it may imply that the response is sent after the device reboot, so in a new DTLS session ... which should normally not work
If the rsp is sent before the device reboot itself, it's not really possible to know that the reboot is really made.

**Comment by sandeepakhouri** [comment]
The Update Trigger Mechanism can be used with Current Transport Binding and Modes other than UQS. UQS is listed as an example that is described in more detail.

There is no dependency on the result of registration update for this response. 

LwM2M Version 1.1 will further clarify this section.
