### ISSUE TITLE
No Object Instance TLV for Single Instance Objects

### ISSUE THREAD

**Issue by mkovatsc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#21]
Test Case 6.2.2 expects the Object Instance TLV in the Test Procedure, although TS 6.3.3 states that the Instance TLV is omitted for Single Instance Objects.

**Comment by jpradocueva** [comment]
Added labels to assist with the classification of the issue.

**Comment by ThGarnier** [comment]
Hum !! TS 6.3.3 states that "Object Instance TLV is only required if multiple Object Instances are returned in a request ", so a single Object Instance is still acceptable. 
Regarding the test,  "it seems" the 2 cases could arrive (depending of the implementation); Client can choose to answer using i way or ii way, in the case of a  Single Object Instance. 
It's my understanding

**Comment by ThGarnier** [comment]
During the OMA Interim meeting (Sept 2016) this point has been discussed also in relation with #issue 86.
What has been adopted by the WG and applicable to this issue, is that TLV Object Instance will be used what ever the number of Object Instance to return. Even if the targeted object is Single Instance. 
This position has been taken for simplification. According to this, the test case 6.2.2 is correct and the TS 1.0 Section 6.3.3 will reflect asap this position ( issue will be closed then).

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
