### ISSUE TITLE
TLV payload structure in Write requests targeting Object Instance

### ISSUE THREAD

**Issue by dextero** [OpenMobileAlliance/OMA_LwM2M_for_Developers#210]
* Name, version and date of the document, ``OMA-TS-LightweightM2M-V1_0_1-20170413-D``
* Section of the document, ``Data Formats, section 3: TLV``:

The spec does not have any examples of a correct payload for a Write operation targeting an Instance ID, and only describes the case of Instance ID **not** being present in a Read request:

> when the Object Instance ID is not specified in the request, the Object Instance TLV MUST be used

**When issuing a Write request on an Instance path (e.g. /1/1), how should the TLV payload look like?**

1. "wrapped" variant: Object Instance TLV containing one or more Resource TLVs,
2. "unwrapped" variant: just a list of Resource TLVs,
3. both (1) and (2) are acceptable.

Cases (1) and (3) introduce the possibility of a Instance ID mismatch between one specified in Uri-Path and one from TLV Instance header, which can be handled in more than one way by LwM2M clients (they could either reject such response, or ignore one of Instance IDs).

**Comment by Echo-xubei** [comment]
I think the right TLV payload should be case 2) : just a list of Resource TLVs when a Write request on an object Instance path(eg. Write /1/1). 
In the section 6.4.3.1 Single Object Instance Request Example of OMA-TS-LightweightM2M-V1_0_1-20170413-D , there is an example response of Read /3/0 which you can refer to.

**Comment by dextero** [comment]
It looks like this issue was resolved in version 1.0 by disallowing Create operation on an Object Instance path (OMA-TS-LightweightM2M-V1_0-20170208-A: `5.4.6 Create`, `Table 25: Operation to Method Mapping`). The only way of enforcing a particualar Object Instance ID is to specify it inside the TLV/JSON payload.
