### ISSUE TITLE
LightweightM2M-1.0-int-755 – Setting the writable resources - Update supported objects - Test Procure

### ISSUE THREAD

**Issue by mmshaikh88** [OpenMobileAlliance/OMA_LwM2M_for_Developers#211]
Please provide the Test flow and procedure for the "Update supported objects".

The Testcase 755 needs to provide the test procedure and pass criteria for the "Update supported objects" in case of Firmware Update object.

**Comment by dnav** [comment]
Hi,

A new ETS is due shortly. It will be more complete and updated to match the latest TS.
Note that the "Update supported objects" resource is no longer part of the Firmware Update Object.

Regards,

**Comment by dnav** [comment]
The "Update supported objects" does not exist anymore in LwM2M 1.0
