### ISSUE TITLE
Clarify Read on empty objects or resources

### ISSUE THREAD

**Issue by mkrstic** [OpenMobileAlliance/OMA_LwM2M_for_Developers#213]
It does not seem clear what client should return as a response to Read request when value is temporarily missing.

For instance, LWM2M client has registered multi-instance object /11. No instances have been 
created. Then:
1. LWM2M server sends Read /11
2. Client responds with:
a) 2.05 Content without specifying data (sending zero-length bytes) or
b) 4.04 Not Found

What is correct behavior?

**Comment by sznaider** [comment]
Actually, the thing you're asking about seems to be defined in the
specification (maybe not super-explicitly though).

Take a look at the OMA-TS-LightweightM2M-V1_0-20170208-A, in section 8.5
(yellow table) it says that the Client can respond with 4.04 if `URI of the
"Read" operation is not found`.

Now, you claim Object `/11` is registered. In that case, one can issue Create
on it (without getting 4.04 in response), which therefore implies that the
URI `/11` exists, which means the condition of returning 4.04 on Read would
not be met.

**Comment by mkrstic** [comment]
Exactly! The question then arises, if condition of returning 4.04 on Read wasn't met, what would be appropriate response code? 

Code 2.05 seems logical since URI exists. The trick is, it is unclear how to specify payload when there's not any. One option would be to completely omit payload, but I don't think that would be valid LwM2m response. That was my original question.

**Comment by ovidiu-usturoi** [comment]
We can use  4.12 (Precondition Failed) since the object is not instantiated. In this case, the specification should be updated.

**Comment by dnav** [comment]
> One option would be to completely omit payload, but I don't think that would be valid LwM2m response.

I can't see why. In this situation, I would return a 2.05 code with a zero-length payload.

**Comment by fdur** [comment]
If /11 is registered but no object instance were created, if a READ command is received on /11, a zero-length payload can be sent by the client (so 2.05 rsp)
In the same use case, if a READ command is received on /11/x, then a 4.04 rsp is returned

**Comment by mkrstic** [comment]
It wouldn't be bad to update the specification to state exact behavior in situations like this.

Response 2.05 looked inappropriate to me because it should indicate a payload, and if there's no payload, I would have expected to get something like HTTP 204 "No Content" or corresponding 4.xx code.
   
Anyway, as you confirmed 2.05 response is valid here, this issue can be closed.

**Comment by dnav** [comment]
This will be clarified in TS for LwM2M 1.0.2

**Comment by hannestschofenig** [comment]
Issue has been addressed with CR http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2017/OMA-DM-LightweightM2M-2017-0218R01-CR_Read_clarification.zip for LwM2M 1.0.2
