### ISSUE TITLE
Error code definition

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA_LwM2M_for_Developers#214]
* Specification: OMA-TS-LightweightM2M-V1_0-20170208-A
* Section E.4

Resource description:

> When the single Device Object Instance is initiated, there is only one error code Resource Instance whose value is equal to 0 that means no error. When the first error happens, the LwM2M Client changes error code Resource Instance to any non-zero value to indicate the error type. When any other error happens, a new error code Resource Instance is created.

According to §6.3, resource instance ID is a 16-bit identifier.
If the error code is not reset, what is the behavior if the error code number reachs 65535 ?
Is it reasonable to have up to 65535 resource instances ?

Moreover, I think that the definition of 8=Peripheral malfunction needs to be checked.

**Comment by dnav** [comment]
Implementations can have a limit on the number of stored error codes.
Furthermore the `dim` attribute is limited to 255.
