### ISSUE TITLE
Glitches in XML object specifications

### ISSUE THREAD

**Issue by mjjaniec** [OpenMobileAlliance/OMA_LwM2M_for_Developers#215]
All issues are connected with XML specifications of LwM2M objects published here: [OMA LightweightM2M (LwM2M) Object and Resource Registry](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html)

#### Object - 0 - LwM2M Security - defined [here](http://www.openmobilealliance.org/tech/profiles/LWM2M_Security-v1_0.xml), specified [here](http://openmobilealliance.org/release/LightweightM2M/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf) in section E.1 LWM2M OBJECT: LWM2M SECURITY

* object name is: `LWM2M Security`, while according to the spec it should be named `LwM2M Security` (Note change of the case for letter "w")
* resource 0 is named: `LWM2M  Server URI`, it has capital "W" and **two** spaces between "LWM2M" and "Server URI"

#### Object - 7 - Connectivity Statistics - defined [here](http://www.openmobilealliance.org/tech/profiles/LWM2M_Connectivity_Statistics-v1_0.xml), specified [here](http://openmobilealliance.org/release/LightweightM2M/V1_0-20170208-A/OMA-TS-LightweightM2M-V1_0-20170208-A.pdf)

* object has incorrect description:
`This LwM2M Objects enables client to collect statistical information and enables the LwM2M Server to retrieve these information, set the *collection duration* and reset the statistical parameters.`
whilst `collection duration` resource was renamed to `Collection Period`
The same error could be found in the spec (OMA-TS-LightweightM2M-V1_0-20170208-A.pdf).

#### Object - 9 - Software Management - defined [here](http://www.openmobilealliance.org/tech/profiles/LWM2M_Software_Management-v1_0.xml), specified [here](http://www.openmobilealliance.org/release/LWM2M_SWMGMT/V1_0-20170314-C/OMA-TS-LWM2M_SwMgmt-V1_0-20151201-C.pdf)

* object name is `LWM2M Software Management`, but according to the spec it should be: `Software Management`

#### Object - 11 - APN connection profile - defined [here](http://www.openmobilealliance.org/tech/profiles/LWM2M_APN_connection_profile-v1_0.xml), specified [here](http://www.openmobilealliance.org/release/LWM2M_CONNMGMT/V1_0-20170314-A/OMA-TS-LWM2M_ConnMgmt-V1_0-20170314-A.pdf)
* Resource 16 - `Prefix length(2)` doesn't have a space before left parenthesis but all others does.
The spec contain the same error.

Additionally I think that putting a reference to the documentation inside a resource name is a bad idea.
I would like to suggest moving these references to resource descriptions.

**Comment by jpradocueva** [comment]
We are looking into this and preparing the Change Requests.

**Comment by hannestschofenig** [comment]
If this issue is still valid, please re-issue it against the LwM2M v1.1 release.
