### ISSUE TITLE
Need clarification for 'Connectivity Statistics' implementation

### ISSUE THREAD

**Issue by pkreddy04** [OpenMobileAlliance/OMA_LwM2M_for_Developers#217]
> Reference document: OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf
> Section: E.8 LwM2M Object: Connectivity Statistics

Need a clarification if the data in the resources 1-5 should be available for Server Read only after 'Stop' operation is executed or when the 'Collection Period' expires (or) should these stats (1-5) be available even intermittently whenever a Read/Observe operation is performed after 'Start' operation is initiated and before 'Stop' operation is performed or 'Collection Period' expires .

One argument for the latter case is, operator can also perform multiple Start/Stop or preset some default collection period and perform 'Start' as many times as needed and hence may only desire the stats data once the Stop is performed or Collection period expires instead of any intermittent data as it is difficult for the operator to keep track of when the collection period expired. 

Also, should a 'Start' operation initiation override the previous under progress 'Start' operation or should it be ignored on the client?

Guidelines on the above would be helpful.

**Comment by ThGarnier** [comment]
Hello, the only things the specification assures is that Data Collection is available after the Stop Command has been processed or when the Collection Period expired; so, what happen in between must be considered as implementation specific (as the spec says nothing) as long as this  does'nt break the behavior of the spec above. For sure the spec shouldn't let any ambiguity here :(

As the spec says that any start,  clears the data collection (Res 0-5) your "latter case" is not so obvious to consider with the current spec (whatever your use case is valuable): there is no specific/independant Data Collection "to preset" .  I agree that without status on the logging process, keeping track of the data Collection process is harzardous (that's also why we introduced le logStatus re-usable Resources for logging in OMNA) .

Last point :  as the Start operation, resets the data collection, it is implicit (again I agree implicit behaviour is not a good statement in a Spec) , your 1st assumption (overrriding)  is the correct one.
Hope it helps
Thierry
