### ISSUE TITLE
Object Registration - 10,257

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/OMA_LwM2M_for_Developers#218]
Please review the following registration from **Comsel System Ltd.**

 * [10,257](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=afaa9701-d11f-43f4-9635-b3b92d5c6a71_Object.xml)

**Comment by jpradocueva** [comment]
Pending that the submitter choose under what license this object should be registered:

Possible options:
* Apache 2.0
  * https://github.com/jpradocueva/apache20 
* GNU General Public License 3.0
  * https://github.com/jpradocueva/gnu30 
* MIT License
  * https://github.com/jpradocueva/mit 
* BSD 2- clause “Simplified” License
  * https://github.com/jpradocueva/bsd2 
* BSD 3 – clause “New”or “Revised” License
  * https://github.com/jpradocueva/bsd3 
* Eclipse Public License 1.0
  * https://github.com/jpradocueva/Eclipse10 
* GNU Affero General Public License v3.0
  * https://github.com/jpradocueva/gnu-affero 
* GNU General Public License v2.0
  * https://github.com/jpradocueva/gnu20 
* GNU Lesser General Public License v2.1
  * https://github.com/jpradocueva/gnu21 
* GNU Lesser General Public License v3.0
  * https://github.com/jpradocueva/gnu-lesser-3_0 
* Mozilla Public License 2.0
  * https://github.com/jpradocueva/mozila 
* Your Own License

**Comment by jpradocueva** [comment]
Some of the reusable resources have (Read and Write) Operations but here appear only Read operations, e.g. 5506.

**Comment by jpradocueva** [comment]
Content on Object Version and LwM2M Version is missing. Both fields should be described as (1.0)

**Comment by dbjorklu** [comment]
I used the reusable resource 5800 and 5805 for **active** power. This is questionable as there is no active, as opposed to **reactive**, power in district heating, as there is in electricity. But I like to reuse when possible.

**Comment by dbjorklu** [comment]
I choose the Apache 2.0 license

**Comment by jpradocueva** [comment]
@dbjorklu we haven't received further comments from the group.
Please re-submit after addressing the following issues:
- [ ] Resource 5506 change operations to RW from R. The problem with the editor tool has been resolved
- [ ] In the "Object Definition" table:
  - [ ] Object Version and LwM2M Version should be set to 1.0. Alternatively, could be left in blank but it is better to be consistent and indicate in the new objects these two parameters.

[LwM2M Editor Tool](http://devtoolkit.openmobilealliance.org/OEditor/Default)

**Comment by jpradocueva** [comment]
Still awaiting a reply from the submitter.

**Comment by jpradocueva** [comment]
The registration was updated to: [Load Editor with object 10257](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=f9c8793c-e98a-4d5a-88c3-861e3a34e8b4_Object.xml)
