### ISSUE TITLE
Need clarification regarding to when firmware update/download can be cancelled

### ISSUE THREAD

**Issue by rbtchc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#219]
* OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf
* Section E.6 LwM2M Object: Firmware Update

While I was reading the specification of firmware object at page 116.
In firmware resource 3 (State), I quote the description below

> If writing the firmware package to Package
Resource is done, or, if the device has
downloaded the firmware package from the
Package URI the state changes to
Downloaded.
Writing an empty string to Package URI
Resource or setting the Package Resource
to NULL (‘\0’), resets the Firmware Update
State Machine: the State Resource value is
set to Idle and the Update Result Resource
value is set to 0.

From the description, it seems that any time and any state when an empty package URI / resource is written to the client. The firmware download/update could be cancelled.

However, from the figure 29, there's only one link (Start: DOWNLOADED -> End: IDLE) mentioned such behavior which means firmware update can only be cancelled when state == DOWNLOADED and empty package resource / package URI is written to the client.

We are currently working on LwM2M client implementation, but we have two different interpretations to this.
1. Firmware update can be cancelled any time any states
2. Firmware update can be cancelled only when state equals DOWNLOADED

I'm not sure whether here's right place to raise the question.
But can anyone help to clarify the correct behavior to me?

Thanks

**Comment by hannestschofenig** [comment]
The firmware update can only be cancelled when the state equals DOWNLOADED since this is the only state transition shown in the state machine.

**Comment by fdur** [comment]
I think that Figure 29 is just an informative figure.
As indicated:
> Figure 29 shows a possible implementation of the firmware update mechanism

From my point of view, according to State resource description (/5/0/3):
> Writing an empty string to Package Resource or to Package URI Resource, resets the Firmware Update State Machine: the State Resource value is set to Idle and the Update Result Resource value is set to 0.
--> it should be possible to cancel an on-going package download (meaning /5/0/3 = 1 Downloading) by sending an empty URI to a client.
Then, when this empty URL is received by the client, the treatment should be, whatever the current State resource value:

- If any download is active, abort it

- State/Result resources needs to be set to Idle/Initial value

**Comment by hannestschofenig** [comment]
Do you need the feature for having to abort a firmware update in any state?

Personally, I am concerned with having any way for the LwM2M server to abort the firmware update since this places additional trust on the LwM2M server when in many cases you don't need this.

**Comment by rbtchc** [comment]
I think the main argument to allow the server to cancel firmware update at any state is that if the client gets stuck in the state other than downloaded/idle, the server can still reset the firmware update process.

**Comment by hannestschofenig** [comment]
But why should the client get stuck in any of the states? Of course, it may happen that it takes longer for the client to download the firmware image than expected but is that a reason to cancel it?

**Comment by rsalveti** [comment]
Not necessarily stuck, but since a firmware update download process can take a considerable amount of time (depending on the device, network, protocol, etc), it's nice to have a way to nicely abort the download and reset the state machine.

My interpretation from the spec is the same as described by fdur (figure is just informative).

Either way, I think this should be clarified on the spec.

**Comment by fdur** [comment]
The main issue is how to understand the following line:
> Writing an empty string to Package Resource or to Package URI Resource, resets the Firmware Update State Machine: the State Resource value is set to Idle and the Update Result Resource value is set to 0.

If this empty string is received by the client while the update state value is 1 (Downloading (The data sequence is on the way)), this resource value needs to be updated to 0 (Idle).
This implicitly means that the download needs to be canceled.
Correct ?

Or so now, another question:
From all your points of view, when this empty URL could be sent to a client ?

**Comment by rbtchc** [comment]
> If this empty string is received by the client while the update state value is 1 (Downloading (The data sequence is on the way)), this resource value needs to be updated to 0 (Idle).
> This implicitly means that the download needs to be canceled.
> Correct ?

Correct, if there is an ongoing download, it has to be canceled accordingly.
Also, if there is an ongoing upgrade (state = 3), it has to be canceled, if possible, too.

> Or so now, another question:
> From all your points of view, when this empty URL could be sent to a client?

Not quite sure I understand your question.

**Comment by hannestschofenig** [comment]
I will bring this topic up for discussion in the DM group again to find out whether this can and should be clarified in LwM2M v1.0.2 or whether we should rather wait till v1.1 in order to revise the firmware update state machine. Currently, the functionality provided (according to the members in the group) is that there is no functionality to reset the state machine during a firmware download operation.

**Comment by hannestschofenig** [comment]
We will investigate this requested functionality in LwM2M v1.1. Interested parties are welcome to join the standardization work on v1.1.
