### ISSUE TITLE
Common.xml: Schema violation regarding "Mandatory" field

### ISSUE THREAD

**Issue by davidgraeff** [OpenMobileAlliance/OMA_LwM2M_for_Developers#224]
Related to #222.
The xml file that describes the common resources does not validate with the given XML Schema. Multiple resources have no value set for `<Mandatory>`, which according to the Schema must be Mandatory/Optional.
Either the common file is corrected or the schema is changed to assume a default value of "Optional".

**Comment by jpradocueva** [comment]
See Issue: 

#222
