### ISSUE TITLE
Automatic XML validation before releasing a OMA LwM2M registry xml file

### ISSUE THREAD

**Issue by davidgraeff** [OpenMobileAlliance/OMA_LwM2M_for_Developers#225]
The current situation is, that the Common.xml, which describes all common LwM2M resources, does not validate against the provided xsd Schema.

## How to reproduce
Use an online tool like http://www.xmlvalidation.com/:

* Upload the http://www.openmobilealliance.org/wp/OMNA/LwM2M/Common.xml file
* Upload the schema http://openmobilealliance.org/tech/profiles/LWM2M.xsd file

The result should be 324 schema violations.

## Solutions for the current found problems

There are two categories of problems:

1. The order of the fields is wrong. This could be changed in the schema by replacing "sequence" with "all". There is no need to force an order on elements here.
2. Some enumeration fields have no value set. The schema can be made more relaxed in the sense that it accepts no or empty fields and a default is assumed. I have opened two bug reports #222 and #224 for the found problems already.

## Prevent this situation
I suggest an automated schema validation process before a new file version is released.

## Usecase
We're implementing an extension for the Eclipse Smarthome (ESH) project to support the LwM2M protocol. To keep up-to-date with defined Objects and Resources of the OMA LwM2M Registry, we automatically download the provided XSD Schema, objects **DDF.xml** file and common resources **Common.xml** file. The files are validated and then transformed into ESH Things and Channels. It is required that the files validate for this to work.

**Comment by jpradocueva** [comment]
See #222

**Comment by jaimejim** [comment]
Hi, in IPSO we do automatic XML validation on travis, you might want to take that and enhance it if you don't use that yet.

https://github.com/IPSO-Alliance/pub/issues/3
