### ISSUE TITLE
Need clarification for endpoint client name

### ISSUE THREAD

**Issue by GiedriusM** [OpenMobileAlliance/OMA_LwM2M_for_Developers#231]
* OMA-TS-LightweightM2M-V1_0_1-20170704-A
* Sections 6.3.1

First, the UUID is described as `urn:uuid:########-####-####-############`, however I think it should be updated to `urn:uuid:########-####-####-####-############`, i.e. to the 8-4-4-4-12 format as it is in RFC4122:
```
   The following is an example of the string representation of a UUID as
   a URN:

   urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6
```

Second, what is the recommended form when UUID is used in endpoint client name - with `urn:uuid:` or without?
`ep=urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6`
OR
`ep=f81d4fae-7dec-11d0-a765-00a0c91e6bf6`

**Comment by jaimejim** [comment]
From RFC4122, URNs that use UUID are constructed as the example:
"urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6"

From the LWM2M Specification, Table 20, the Semantics of the endpoint name is the URN itself, including the schema. 
Thus you should use the full URN as epname
epname = "urn:uuid:f81d4fae-7dec-11d0-a765-00a0c91e6bf6"

Regarding the format 8-4-4-4-12 you are correct and we will address it right away on CR 1.0.2.

**Comment by hannestschofenig** [comment]
This has been addressed in OMA-DM-LightweightM2M-2017-0222-CR_UUID_Fixing
