### ISSUE TITLE
New OMNA Registration - Object Range 10262 - 10284

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#232]
[New Objects - Private Range.zip]

Object Range 10262 - 10284

Files -
 (https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/files/1414388/New.Objects.-.Private.Range.zip)

Submitter - Smarterlogic 
Contact - richard.homburg@smarterlogic.com.au

Object ID: 10,262 (please ignore the ObjectID inside of Object)
Name: Interval Data Delivery
Company: smartlogic
Description: The Interval Data Delivery object provides an optimised means for managing the delivery of interval data from multiple Interval Data Object instances.
Link to Object: [10262](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8ad6cc1c-556e-4716-b644-a340080ccbaf_Object.xml)

Object ID: 10,263 (please ignore the ObjectID inside of Object)
Name: Event Data Delivery
Company: smartlogic
Description: The Event Data Delivery object provides a simple means for managing the delivery of event data from multiple Event Data Object instances.
Link to Object: 1[0,263](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=737f4932-663b-4d96-a62d-e6342007b5de_Object.xml)

Object ID: 10,264 (please ignore the ObjectID inside of Object)
Name: Delivery Schedule
Company: smartlogic
Description: The Delivery Schedule object provides a means for controlling the periodic delivery of interval and event data to the LwM2M server.
Link to Object: [10,264](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=2e22a00c-c54a-487c-98f5-4573d3d2a7de_Object.xml)

Object ID: 10,265 (please ignore the ObjectID inside of Object)
Name: Leakage Detection Configuration
Company: smartlogic
Description: The leakage detection configuration object provides a means for configuring the timing and sampling frequency of a vibration-based network leak detector
Link to Object: [10,265](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=7bc8c5cf-687d-441b-b13f-926e50a2b6bd_Object.xml)

Object ID: 10,266 (please ignore the ObjectID inside of Object)
Name: Water Flow Readings
Company: smartlogic
Description: Measures the flow of water in regular intervals
Link to Object: [10,266](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=ba024ccf-05b2-4402-a13b-377afcb3b0b4_Object.xml)

Object ID: 10,267 (please ignore the ObjectID inside of Object)
Name: Daily Maximum Flow Rate Readings
Company: smartlogic
Description: Measures the maximum flow rate and its time stamp for specified period
Link to Object: [10,267](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=89876c2b-e2c4-4ce8-859f-318fb9ffabf8_Object.xml)

Object ID: 10,268 (please ignore the ObjectID inside of Object)
Name: Temperature Readings
Company: smartlogic
Description: Periodic temperature measurements
Link to Object: [10,268](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=c893c28a-981c-4ad8-af29-7304af748070_Object.xml)

Object ID: 10,269 (please ignore the ObjectID inside of Object)
Name: Pressure Readings
Company: smartlogic
Description: Periodic pressure measurements
Link to Object: [10,269](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=20e89811-ac3e-4f3b-92ec-05aa84476ef2_Object.xml)

Object ID: 10,270 (please ignore the ObjectID inside of Object)
Name: Battery Level Readings
Company: smartlogic
Description: Periodic battery level measurements
Link to Object: [10,270](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=26260b7a-6428-42c0-ab36-20f14bdc07bc_Object.xml)

Object ID: 10,271 (please ignore the ObjectID inside of Object)
Name: Communications Activity Time Readings
Company: smartlogic
Description: Measures the total duration that the meter was activating its radio for packet transmission or receipt for the period. Used to monitor for excess power usage over time.
Link to Object: [10,271]( http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=e862dba8-574f-4e87-b4dd-b2a73d3abca1_Object.xml)

Object ID: 10,272 (please ignore the ObjectID inside of Object)
Name: Water Meter Customer Leakage Alarm
Company: smartlogic
Description: A binary flag indicating continual usage (e.g. greater than 5 L/h for 24 hours and the flow never returning to zero at any time).
Link to Object: [10,272](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b2cb3ff3-270d-41b4-9682-73df7cb406e2_Object.xml)

Object ID: 10,273 (please ignore the ObjectID inside of Object)
Name: Water Meter Reverse Flow Alarm
Company: smartlogic
Description: A binary flag indicating continual usage (e.g. greater than 5 L/h for 24 hours and the flow never returning to zero at any time).
Link to Object: [10,273](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1c74dc48-f100-4773-a76b-d10a02783100_Object.xml)

Object ID: 10,274 (please ignore the ObjectID inside of Object)
Name: Water Meter Empty Pipe Alarm
Company: smartlogic
Description: An alarm when meter detects there is no liquid in the pipe
Link to Object: 1[0,274](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=6989c1ec-0cab-4dd7-8c78-95e341a5e452_Object.xml)

Object ID: 10,275 (please ignore the ObjectID inside of Object)
Name: Water Meter Tamper Alarm
Company: smartlogic
Description: Detects interference from a strong magnetic field or other electrical sources. If this is not relevant for ultrasonic meters then the tamper alarm may be used to indicate someone attempting to open the physical enclosure or other options the manufacturer may present.
Link to Object: [10,275](ttp://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1dcfefcb-50e3-4f7f-913f-b5c9321a9138_Object.xml)

Object ID: 10,276 (please ignore the ObjectID inside of Object)
Name: Water Meter High-Pressure Alarm
Company: smartlogic
Description: Where supported by the meter this is an alarm that should be raised if the meter detects pressure above a pre-configured threshold.
Link to Object: [10,276](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b973a458-1040-4493-996d-a6b6a6ebf8ca_Object.xml)

Object ID: 10,277 (please ignore the ObjectID inside of Object)
Name: Water Meter Low-Pressure Alarm
Company: smartlogic
Description: Where supported by the meter this is an alarm that should be raised if the meter detects pressure below a pre-configured threshold.
Link to Object: [10,277](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=604f630e-fa7e-499c-b1ce-c5a123c9eb7b_Object.xml)

Object ID: 10,278 (please ignore the ObjectID inside of Object)
Name: High-Temperature Alarm
Company: smartlogic
Description: Where supported by the meter this is an alarm that should be raised if the meter detects temperature above a pre-configured threshold. When the temperature drops below the clear threshold, the alarm should be cleared.
Link to Object: 1[0,278](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=22795394-d3d4-48ac-9c0f-cbe0c250a67c_Object.xml)

Object ID: 10,279 (please ignore the ObjectID inside of Object)
Name: Low-Temperature Alarm
Company: smartlogic
Description: Where supported by the meter this is an alarm that should be raised if the meter detects temperature below a pre-configured threshold. When the temperature rises above the clear threshold, the alarm should be cleared
Link to Object: [10,279](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=5b50dd12-fa45-4cb1-be6e-f90863f63972_Object.xml)

Object ID: 10,280 (please ignore the ObjectID inside of Object)
Name: Water Network Leak Alarm
Company: smartlogic
Description: All meters must support the following default configuration. This alarm will be based on the frequency output of the vibration sensor/accelerometer on the SEW Daughter board. When a frequency is identified that has the characteristics of an upstream network leak, and its amplitude is above the defined threshold, the meter will report this as a network leak alarm.
Link to Object: [10,280](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=e29c44fb-ab9e-4d5d-a214-3ba483141b59_Object.xml)

Object ID: 10,281 (please ignore the ObjectID inside of Object)
Name: Low Battery Alarm
Company: smartlogic
Description: This Alarm is raised when the battery voltage drops below a defined level
Link to Object: [10,281](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=e29c44fb-ab9e-4d5d-a214-3ba483141b59_Object.xml)

Object ID: 10,282 (please ignore the ObjectID inside of Object)
Name: Daughter Board Failure Alarm
Company: smartlogic
Description: This binary status should indicate that the meter MCU can no longer communicate with a daughter board
Link to Object: [10,282](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=a392e46e-31e2-4e45-bda2-92f06ca9b4c8_Object.xml)

Object ID: 10,283 (please ignore the ObjectID inside of Object)
Name: Device Reboot Event
Company: smartlogic
Description: This binary status should indicate that the meter MCU can no longer communicate with a daughter board
Link to Object: [10,283](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=4a121ab3-106c-441a-8684-ea23c45a8307_Object.xml)

Object ID: 10,284 (please ignore the ObjectID inside of Object)
Name: Time Synchronisation Event
Company: smartlogic
Description: This event records the fact that the device has rebooted
Link to Object: [10,284](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=60a1eabd-8d06-4aeb-8a07-d2860f00f74b_Object.xml)

**Comment by ndamour** [comment]
As a general comment, some of the proposed objects here log events that happen on the device, and it would be nice to have in mind the event logging framework that is currently being discussed in the OMA DM group for LwM2M.

**Comment by seanmcilroy29** [comment]
http://openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

**Comment by seanmcilroy29** [comment]
OMNA Registry updated
