### ISSUE TITLE
New Resources - 6001-6029

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#233]
[New Resources.zip]

6001-6029 - Resource_Range

Files -
[New resources.zip](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/files/1414413/New.resources.zip)

Submitter - Smarterlogic

**Comment by ndamour** [comment]
Hello.
Which resource IDs are actually reserved?
The current reserved numbers in the OMNA registry are from 6000 to 6031 included, but the provided file only described 6000 to 6029.
Can you please provide 6030 and 6031 as well?

**Comment by seanmcilroy29** [comment]
OMNA Registry updated
