### ISSUE TITLE
Resource attributes in Discover

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#234]
The test specification `OMA-ETS-LightweightM2M-V1_0_1-20170830-D`, in test case 260, says that the server shall issue WRITE-ATTRIBUTES on the Object Instance level and then verify the attributes using DISCOVER on the whole object.

According to both `OMA-TS-LightweightM2M-V1_0-20170208-A` and `OMA-TS-LightweightM2M-V1_0_1-20170704-A`, it is unclear whether the Attributes should be returned in response to such Discover operation. To quote section 5.4.2:

> If Object ID is only specified, the LwM2M Client MUST respond to the “Discover” operation with the list of Object Instances and the list of their respective instantiated Resources. In addition, the list of Attributes which have be assigned to this Object level (see section 5.1.2 Attribute Classification) are also returned.

Also, the examples below show no Attributes on the Object Instance level being returned for Discover on the Object level, even though the result set includes Multiple Resources which would normally have at least `dim` Attributes - which seems to confirm that Discover on the Object level shall not contain Instance-level or Resource-level Attributes.

However, the ETS requires that the Discover on the whole object shall contain Instance-level and Resource-level Attributes, which seems to be in contradiction with the specification.

I believe this should be addressed by amending either the TS or the ETS.

**Comment by ThGarnier** [comment]
Most of your complain are legitimate on the ETS  :( even if  DM WG proceed to few adjustement in TS 1.0.2 (explicit list of the Object Instances for the  DISCOVER targeting Object ID only).
So the fixes are mainly concerning the int-260 test case (bad cut-and-paste); and yr feeling regarding the TS is correct (dim must be absent from the 2 1st Discover) .
 So, it is the opportunity in the ETS 1.0.2 to not only fix but also make this test more relevant by modifying a bit the test procedure (setting at Object Level, looking at Object Instance Level) 


> Normal flow:
1.	The initial DISCOVER (CoAP GET Accept:40) operation is performed on Objet Device ID:3  
2.	A WRITE-ATTRIBUTES operation set the pmin=10 & pmax=200 <NOTIFICATION> Attributes at the Object level 
3.	DISCOVER command is performed at Object Instance level of Object ID:3 
4.	The WRITE-ATTRIBUTES operation set the lt=1, gt=6 et st=1 <NOTIFICATION> Attributes of  the Resource ID:7 (Power Source Voltage)
5.	Same DISCOVER command as in test step 3. is performed 
6.	DISCOVER operation is performed on Resource ID:7 of the Object Device Instance

Pass Criteria
A.	In test step 1, the Success Message (“2.05” Content) is received by the Server along with the payload related to the DISCOVER request and containing :
< /3>,</3/0>,</3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>,</3/0/6> </3/0/7></3/0/8> </3/0/9>,</3/0/11>,</3/0/16>
B.	In test step 2, a Success message is received by the Server (“2.04” Changed)  related to the WRITE-ATTRIBUTES operation
C.	In test step 3, the Success message (“2.05” Content) is received by the Server along with the payload related to the DISCOVER request and containing :
</3/0></3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>, </3/0/6>;dim=2, </3/0/7>;dim=2, </3/0/8>;dim=2, </3/0/9>,</3/0/11>,</3/0/16>
D.	In test step 4, a “Success” message is received by the Server (“2.04” Changed)  related to the WRITE-ATTRIBUTES operation
E.	In test step 5, the Success message (“2.05” Content) is received by the Server along with the same payload received in step 3, except for the Resource 7 :
</3/0>,</3/0/1>,</3/0/2>, </3/0/3>, </3/0/4>, </3/0/6>;dim=2, </3/0/7>;dim=2, ;lt=1;gt=6;st=1, </3/0/8>;dim=2,</3/0/9>, </3/0/11>,</3/0/16>
F.	In test step 6, the Success message (“2.05” Content) is received by the Server along with the payload related to the DISCOVER request and just containing :
</3/0/7>;pmin=10;pmax=200;dim=2 ;lt=1;gt=6 ;st=1
>

**Comment by kFYatek** [comment]
Your suggestions for changes in the ETS look pretty much perfect to me.

**Comment by ThGarnier** [comment]
good :-)
