### ISSUE TITLE
Resource ``Firmware Update Protocol Support`` clarification

### ISSUE THREAD

**Issue by mjjaniec** [OpenMobileAlliance/OMA_LwM2M_for_Developers#235]
**Document:** OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf, 
**Section:** E.6 LwM2M Object: Firmware Update

Resource ``Firmware Update Protocol Support``  specifies what protocols are supported by LwM2M client to perform firmware update via PULL. Let's analyse the following setup:
```
{“bn”:“/”,
 “e”:[
 {"n":"5/0/8/0","v": 3},
 ]
}
```

To our understanding it should to be interpreted as supporting HTTPS because the value is 3 and 3 is for HTTPS.
Other implementation interprets it as supporting CoAP, because the Resource Instance Id is 0, which means CoAP.

The question is, whether supported protocols are encoded by resource values, or by Resource Instance IDs?

The specification states: "The following values are defined by this version of the specification:" thus we think that our interpretation (values) is correct.

Please confirm whether we are right, and if so please add the following note to the spec:
"Note that supported protocols are encoded by resource values, not by Resource Instance IDs."

**Comment by hannestschofenig** [comment]
The supported protocols are encoded by resource values. There is no need to explicitly indicate this since this is the default behavior.
