### ISSUE TITLE
Attachment or Assignation level of Notification Attributes

### ISSUE THREAD

**Issue by weilinchina** [OpenMobileAlliance/OMA_LwM2M_for_Developers#237]
* <<OMA-TS-LightweightM2M-V1_0_1-20170704-A>>:
* section: '5.1.2 Attributes Classification' - <NOTIFICATION> Class Attributes:
* when server write attributes to client: 
![write_attributes](https://user-images.githubusercontent.com/2929903/32273427-71ffb73c-bf3d-11e7-93da-fa37f780ea59.png)

as above graph specified: when server try to write notification attribute 'pmin=11' to object or object instance level, and there's already a notification attribute 'pmax=10' containing in its corresponding resource, at this time, the problem could be: client should to reject this write operation or accept it?

as there's a rule inside T-spec as bellow:
> 

The maximum period parameter MUST be not smaller than the minimum period parameter.
--

from my point of view, there're could be different understandings:
- the write operation to be denied due the rule of T-spec.
- the write operation to be accepted.

seems the 2nd point is not follow the rule which defined in the T-spec, but sometime it could be reasonable, image the situation as bellow:
- there're several resources bellow the object (regarding multiple instances and resources).
- notification attributes will not be used until the observation operation triggered on the resource/object/object instance.
PS: so to save resources, client may prefer use 'lazy' mode to launch and check the notification attributes.

based on this, the client handling the case maybe: ignore 'pmin' at the phase of checking whether to upload value of attribute 0 or not.

my question could be:
- do you agree 'the write operation to be accepted'?
- what's your idea regarding this?

**Comment by ThGarnier** [comment]
The more reasonable attitude is to consider that a Notification Condition is fulfilled (so notification sent)  when a Change Value Condition (gt, lt, st) AND a Timing Condition (pmin, pmax) are both fulfilled (TS 1.0.2  p 18). When a Timing Condition is not valid (rule violation, as in your case), the full Notification Condition is not valid, therefore not fulfilled (so no Notification is sent); (but the WRITE ATTRIBUTE in yr cas is accepted). 
In addition if there is  no Change Condition defined or it is not valid, the Notification Condition simply boils down to  Timing Condition.  
These notification Conditions are more (and fully)  formalized in the next TS 1.0.2  (section 5.1.2)
Th

**Comment by ThGarnier** [comment]
A full answer will be addressed in LwM2M 1.1  (consistency check related to the Attributes set inside a single WRITE-ATTRIBUTES command)
Th
