### ISSUE TITLE
Legacy stp attribute used in TS 1.0.1

### ISSUE THREAD

**Issue by dextero** [OpenMobileAlliance/OMA_LwM2M_for_Developers#238]
* Name, version and date of the document, ``OMA-TS-LightweightM2M-V1_0_1-20170704-A``:
* Section of the document, ``8.2.5 Device Management & Service Enablement Interface``:

Examples in this section use legacy `stp` attribute:
> d) Write-Attributes /3/0/9?gt=45&**stp=10** means the Battery Level [...]

> e) Write-Attributes /3/0/9?lt=20&gt=85&**stp=10** means the Battery Level [...]

`Table 4: <NOTIFICATION> class Attributes` in section `5.1.2 Attributes Classification` says the attribute should be spelled `st` instead.

**Comment by ThGarnier** [comment]
yes : that is addressed and fixed in  the TS 1.0.2 of October 10th (2017)
Thanks
