### ISSUE TITLE
Question: Object Device (Object ID 3): add manufacturer specific error codes

### ISSUE THREAD

**Issue by vogtdominik** [OpenMobileAlliance/OMA_LwM2M_for_Developers#24]
Is it possible / allowed to add manufacturer specific error codes to Resource ID 11 Error Code of the Device Object (Object ID 3)? If yes, what range can be used?

**Comment by hannestschofenig** [comment]
There are various ways to add new resources to objects and to even define new objects. First, you can register them via the OMA Registry (see http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) or you can also participate in the work on LwM2M v1.1.

**Comment by boaks** [comment]
The question was about adding new (manufacturer specific) values to a already define value range of a already defined resource in a already define object. 
This issue therefore asks a "private value range" for the Device.ErrorCode (/3/0/11). 
Your answer is to use a new object, which would complicate the "extended" usage of that feature.
For  me it seem to be more preferable to define such a "private value range".

**Comment by dnav** [comment]
The answer was either to use a new Obeject or to participate in the work on LwM2M v1.1. If the former does not suit your needs, it leaves you with the latter.
For IP and legal reasons, the OMA DM working group can only accept feature requests from OMA member companies.

Regards,
