### ISSUE TITLE
needs available space check for client device

### ISSUE THREAD

**Issue by weilinchina** [OpenMobileAlliance/OMA_LwM2M_for_Developers#242]
Issue [Package description for firmware updates](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/1) closed, but after the TestFest in Oct, I realize a problem especially for LWM2M client.

in ETS 1.0.1, we have two kinds of Firmware Update in pull mode (triggered by URL), as bellow:
- via CoAP blockwise.
- via HTTP.

in HTTP mode, HTTP header could contains an option 'Content-Length' to specify the length of HTTP body (firmware content), this length is important especially from client perspective, because if client running on a resource limited device, it uses this length to check whether there's enough available space to contains the new firmware, if not, client must refuse the upgrade request.

in CoAP blockwise mode, the first request launched by client 'normally' is a request to ask for the 1st block of firmware data (at least from my client implementation), compare to HTTP mode, there's no check for the whole firmware length, it could possibly cause the problem that there's not enough available space remaining.

some matters need to be make clear:
- in ETS 1.0.1, case 773, shortage of storage memory.
my point: this happened at the time that error case really happened, but previous downloading flow (customer money) already wasted.
- client knows its own firmware length (at least in a limited future).
my point: client should not expect to know exactly whether there's enough available space or not, because firmware length decided by how many new features added (out of knowledge of client).
- at downloading phase, storage space may be used by other tasks, so there's no meaning to check previously there's enough available space or not.
my point: I think this is the real usage of error case 773 in ETS 1.0.1

from technique, we could have a negotiation (at least on length) before client and server start the real download process. but I'm not sure where this should be described, in T-spec or in ETS cases? But I think this should not depends on error case 773 only.

**Comment by hannestschofenig** [comment]
Please feel free to add new resources to, for example, the device object to allow the server to determine how much available flash memory there is. This would allow the LwM2M server to determine the available resources before shipping an update. 

Realistically, however, an OEM should figure this out ahead of time for low end IoT devices since he/she will hopefully test these updates before sending them to the devices. Of course, they may be more advanced devices where different vendors provide updates to different libraries and hence such an error may occur with devices in the field.

**Comment by boaks** [comment]
RFC7959 (blockwise), section 4, "The Size2 and Size1 Options", page 30

>  The Size2 Option may be used for two purposes:
>    o  In a request, to ask the server to provide a size estimate along
>       with the usual response ("size request").  For this usage, the
>       value MUST be set to 0.
>    o  In a response carrying a Block2 Option, to indicate the current
>       estimate the server has of the total size of the resource
>       representation, measured in bytes ("size indication"). 

FMPOV 'Size2' seems to be the coap-equivalent for http 'Content-Length'.
So, if it works for http, it should work for coap.

**Comment by hannestschofenig** [comment]
This seems to be a problem of HTTP and/or CoAP and unrelated to LwM2M.
