### ISSUE TITLE
New Objects - Private Range 10286

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#243]
[New Object - Private Range - 10286]

Object Range 10286
Submitter - Huawei

Object ID: 10,286 
Name: App Fota Container
Company: Huawei
Description: This LWM2M Object is used to download the firmware package of a device's application.
Link to Object: [10286](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2Flwm2m%2FRegistrations%2F10286.xml)

**Comment by dnav** [comment]
Hi,

Wouldn't the [Software Management](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2FLWM2M_Software_Management-v1_0.xml) and the [Software Component](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2FLWM2M_Software_Component-v1_0.xml) Objects suit your needs ?

Regards

**Comment by jpradocueva** [comment]
Registration completed. The submitter didn't notify OMA if the license was ok.
