### ISSUE TITLE
Is it mandatory to have bootstrap server information in 0/0 always?

### ISSUE THREAD

**Issue by nivasvarma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#245]
I have gone through the spec "OMA-TS-LightweightM2M-V1_0_1-20170704-A" and did not find any where on whether the bootstrap server details to be stored on the 0/0.

Could you let me know if I am missing this any where in the spec. I will come to actual issue. During client initiated bootstrap, server sends a put on 0/0 with LWM2M server details. In this case, if already bootstrap server details are available at 0/0, how should the LWM2M client behave? 
Does the client needs to over write?
Does the client creates next available instance of security object?

It would be great help if some one shares thoughts and point me the relevant section of the spec.

Regards,
Srini

**Comment by hannestschofenig** [comment]
You cannot use object 0/0 for a bootstrap server. The reason is that the LwM2M server object cannot point to a security object with the Short Server ID of value of 0

**Comment by fdur** [comment]
Hi Hannes
are you sure that /0/0 is linked to short server ID = 0 ? :)
From my point of view, /0/0 object instance can concern a bootstrap server.

**Comment by hannestschofenig** [comment]
Sorry. I wrote nonsense. 

Here is the corrected version: 
You cannot use object 0/0 for a LwM2M server; you can only use it for the bootstrap server. The reason is that the LwM2M server object cannot point to a security object with the Short Server ID of value of 0.

**Comment by ThGarnier** [comment]
@nivasvarma Just to clarify : 
                   * when you say "Bootstrap-Server details to be stored in /0/0", you  mean the Bootstrap-Server is setting the Instance 0 of the Security Object : right ?
                    * in fact, Instance 0 of the Security Object is not reserved anymore to the Bootstrap-Server since the release TS 1.0.1. With the Bootstrap  Discover command, the Boostrap Server is able to identify the Instance of the Security Object containing its Security "details" ( section 5.2.7.3 :no ssid for that Instance; in the example the Instance 1 of the Security Object is dedicated to the Bootstrap-Server)
                   
For adressing your issue : when you say : "During client initiated bootstrap, server sends a put on 0/0 with LWM2M server details"; you want to say "...Bootstrap-Server send a PUT on /0/0 with the LwM2M Server details" right ?
       So  YES, on principle nothing prevents the BOOSTRAP-SERVER to do bad things; it can decide to overwrite its own credentials or to provide a very bad  configuration to the Client (wrong ACL configuration ...) ; that's why DISCOVER allows it to be aware of many things regarding the Client Configuration; this feature will be even enhanced in LwM2M 1.1 . BOOTSTRAP-SERVER has full priviledges so it must be handled with care.   HOWEVER : (see section 5.2.6) when the BOOTSTRAP-FINISH is issued,
the Client must perform consistency checks before leaving the Bootstrap sequence ; nothing prevents the Client to accept to go to death without fighting :-)  
Clear enough ?
Th

**Comment by nivasvarma** [comment]
Hi All, Appreciate your replies!!!
Hi Garnier,

I understand that discover during the bootstrap provides me the data by which I can identify the security object instance where the bootstrap details are stored and avoid that to PUT the LWM2M server details. But the catch here is, discover is NOT a mandatory feature, hence it is difficult for us. 
Another point is, the stage of issuing discover during bootstrap. Can I issue discover at any stage of the bootstrap process? Just like below combinations

1) Discover --> Write
2) Write --> Discover
3) Delete --> Discover --> Write
4)Delete --> Write --> Discover

This is not clear in the spec.

**Comment by ThGarnier** [comment]
Hum !! what do you mean by not mandatory features; there is no optional command, whatever the interface is concerned; without DISCOVER command, incremental bootstrap is really problematic, I guess impossible !! right ?  Why DISCOVER could be not used at any moment during the BOOTSTRAP process ? for sure it should be used at pertinent moment :-)

**Comment by nivasvarma** [comment]
Hi Garnier,

Sorry I could not respond to this as I got struck with some other priority tasks. for the query you asked " what do you mean by not mandatory features" is that "Discover during the bootstrap" is not a mandatory feature from client perspective.  Hence client may not implemented this. Hence bootstrap server can not find out the already used instance of security object.

**Comment by hannestschofenig** [comment]
We believe this issue is addressed in the additional bootstrap server capabilities in v1.1.
