### ISSUE TITLE
Clarification on the 'Stop' operation in 'Connectivity Statistics' object

### ISSUE THREAD

**Issue by pkreddy04** [OpenMobileAlliance/OMA_LwM2M_for_Developers#247]
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: **OMA-TS-LightweightM2M-V1_0_1-20170704-A**
* Section of the document, ``(e.g. section: 6.2)``: **E.8 LwM2M Object: Connectivity Statistics**

If a 'Collection period' is defined and used in the 'Connectivity Statistics' object, should a 'Stop' operation trigger stop collecting information or should be ignored by client and return an error?

While the description for 'Stop' makes it clear that client should 'Stop collecting information', but the description text for 'Start' leaves a little ambiguity that 'If resource 8 (Collection Period) value is 0, the client will keep collecting information until resource 7 (Stop) is executed, _otherwise the client will stop collecting information after specified period ended_.'

I think client can stop collection information whenever a 'Stop' operation is executed, so that gives an operator an explicit way to Stop an operation which was initiated on the client.

**Comment by hannestschofenig** [comment]
If you invoke the stop resource then the collection of data will be stopped regardless of what is stated in the Collection Period resource.

So, the three resources, namely start, stop, and collection period, together provide you three different ways of collecting data: 

 1) Use start and stop if you don't know the desired length ahead of time. 
 2) Use start and collection period for a time-based collection of data. After the indicated time in seconds (in the collection period) the collection will be stopped. 
 3) Use start and collection period for a time-based collection of data with the "emergency stop" capability of the stop resource. 

Do you think that this needs to be clarified in v1.1?

**Comment by pkreddy04** [comment]
Thank you. Yes, it would be helpful to have clarification like this in the spec.
