### ISSUE TITLE
Inconsistent "step" CoRE Link param naming in specification

### ISSUE THREAD

**Issue by rbtchc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#250]
When submitting an issue please indicate the following information:
* Name, version, and date of the document: OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf
* Section of the document: section 5.1.2 and 8.2.5

In section 5.1.2, "step" attribute has core link param defined as "st". However in section 8.2.5, page 78 (141), example (d) is using "stp" as step attribute.

**Comment by asoloway64** [comment]
Changing "stp" to "st" has been proposed for the v1.1 version of the Technical Specification.

**Comment by rbtchc** [comment]
Got it. I will close the issue.
