### ISSUE TITLE
Connection Management: is preferred bearer more important than preferred operator

### ISSUE THREAD

**Issue by lauri-piikivi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#251]
Regarding the spec:  Lightweight M2M – Connectivity Management Object (LwM2M Object – ConnMgmt)  Approved Version 1.0 – 14 Mar 2017 Open Mobile Alliance OMA-TS-LWM2M_ConnMgmt-V1_0-20170314-A 

Chp 8. LwM2M Object: Bearer selection
It is unclear to me what is the priority of data used for network selection. For example is the preferred bearer first used to limit available networks, or are the preferred or allowed networks stepped through in order to find a technology that the radio supports -- if there is a multi-mode radio. This should be clarified in the specification

**Comment by mojanm** [comment]
Right or wrong I think the specification assumes the reader having a detailed knowledge of PLMN selection process, hence the apparent lack of clarity. The paragraph above the object table, quoted below,  essentially addresses how the resource can/should be used: 
“This object allows via remote bearer and network configuration to overwrite automatic network and bearer selection e.g. as supported by the UICC. An equivalent example for overwriting automatic selection is a user doing manual network and bearer selection on a smart phone.”
My reading of this paragraph is that for a cellular client if this resource is present and has an assigned value, client should essentially perform manual PLMN selection. This involves modem performing full PLMN search on all its supported Radio Access Technologies (RATs) and returning list of found PLMNs. Here LwM2M client is acting as the user and once it receives the list of found PLMNs it should select a PLMN that best matches the ordered list of bearer types in the  Preferred Communication Bearer List.

**Comment by lauri-piikivi** [comment]
Does it need to scan all RATs, usually there is a match earlier
1. Select 1st RAT from preferred bearers
2. SCAN PLMS
3. Compare to preferred or allowed -- choose if match
4. If not match, go to 1

But this means the RAT (bearer) is more preferred than the operator list -- because it is used first to filter the scan for potential operators.
You seem to suggest that all technologies are scanned, and then operator is selected -- meaning that you prefer the operator list over the bearer list. Which is correct?

**Comment by mojanm** [comment]
My understanding is that here the server effectively requesting manual PLMN selection and the procedure will be as per manual PLMN selection laid out in 3GPP specifications. The only difference is that in case of a standard mobile handset the list of found PLMNs is presented to the user to choose one from, whereas here the answer should already be known via resource 6, Operator List. So, for the feature to work properly, the server needs to set resources 0, 6 and 7 to sensible values. How the client implements manual PLMN search and when it stops searching is an implementation issue. In my view the requirement on the client is to find the highest priority PLMN from PLMN List resource which supports the bearer type specified in resource 0. If the client finds such a PLMN and successfully attaches to the NW, NAS layer in modem will treat it as manually selected PLMN and operate accordingly with respect to various mobility procedures, etc.
However, if this manual PLMN selection fails, like a mobile handset client should revert back to the last registered PLMN.

**Comment by lauri-piikivi** [comment]
I think we agree, but let's verify 2 cases
- CASE A terminal uses preferred bearer [0] NB-IOT, and finds preferred operator [3]
I think you and I are saying that the terminal is good to select the operator [3] "...is to find the highest priority PLMN from PLMN List resource which supports the bearer type specified in resource 0.")
- CASE B terminal uses preferred bearer [1] CAT-M1, and finds preferred operator [1]
bearer is less preferred (assuming the list is priority ordered) but operator is more preferred (assuming list is preference ordered). 
My concern is that for management server it can be confusing if terminals end up selecting the operators differently for same configuration.

**Comment by mojanm** [comment]
Bearer type resource determines the order of RAT priority for carrying out PLMN search and PLMN list determines the PLMN priority for selecting a PLMN of a particular RAT. So, I cannot see any confusion or inconsistency. The two list obviously have some relationship, but a  mobile client can be in a particular location where for example there is no NB-Iot coverage which may be the preferred bearer, or vice a versa no coverage for a highest priority PLMN of selected NB-IoT bearer type.

**Comment by hannestschofenig** [comment]
Network selection is not driven through the connectivity object (unless you are in a manual mode).
Automatic network selection is driven by 3GPP specifications. Manual selection is implementation-specific.
