### ISSUE TITLE
Connection Management: Execute command needed?

### ISSUE THREAD

**Issue by lauri-piikivi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#252]
Spec: Lightweight M2M – Connectivity Management Object (LwM2M Object – ConnMgmt)  Approved Version 1.0 – 14 Mar 2017 Open Mobile Alliance OMA-TS-LWM2M_ConnMgmt-V1_0-20170314-A 

It is unclear, if connection parameters are updated, that are those taken to use immediately? Device can not know if there are multiple objects coming in separate commands. When the parameters are changed, it can affect the current connection the device has. It seems an explicit execute command to update the connection parameters is needed.

**Comment by mojanm** [comment]
@lauri-piikivi, can you please elaborate which communication parameters you are referring to? Are you referring to some of the resources in Cellular connectivity object, OID 10, e.g. PSM Timer, etc.?

**Comment by lauri-piikivi** [comment]
I think the biggest problems are any changes on preferred bearer, operator list (and it's mode) and any APN settings change. Are those taken to use immediately -- breaking the connection. Or is there some time out and should that be specified

**Comment by mojanm** [comment]
At the end of client’s current message exchanges with the Lwm2M server, RRC connection to the NW will be released and client modem returned to Idle state. That seems to be the appropriate time to execute this procedure as it has no dependency on how the client modem implements PLMN search, i.e. background search v foreground search. So, don’t really see any specific need for a separate execute command.

**Comment by lauri-piikivi** [comment]
For remote management the cellular device is server role, it waits requests to the registered resources.  It can not know when the client has finished. Additionally the cellular connection is usually done with a separate modem, that does not reveal the exact event or time of RRC idle. (RRC idle transition is forced by the network, so they do vary) So the server is left hanging.  Also the client or other clients may be carrying out also other commands on the cellular device to take the most of the power usage for the connection. And since it consumes power to wait if there is still something happening, an explicit command seems warranted. At minimum some guidance on the timeouts

**Comment by hannestschofenig** [comment]
When the parameters are taken into account is implementation-specific.
