### ISSUE TITLE
IPSO Object 3336 updated with new resource

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#254]
IPSO Object [3336 ](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2Flwm2m%2F3336.xml)has been updated with resource 5513

Updated object for review [3336](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2Flwm2m%2FRegistrations%2F3336_changes.xml)

**Comment by jpradocueva** [comment]
Problem Reported via [LwM2M Editor](https://github.com/OpenMobileAlliance/OMA_LWM2M_Editor/issues/32).

>In the online [DDF](http://www.openmobilealliance.org/tech/profiles/lwm2m/3336.xml), object 3336 >uses resource 5514 for Latitude and 5515 for Longitude
>
>While in [IPSO Alliance's definitions](https://github.com/IPSO->Alliance/pub/blob/master/reg/xml/3336.xml), 5513 is for Latitude, 5514 for Longitude and 5515 for >Altitude

**Comment by mojanm** [comment]
IS IPSO using object versioning?

**Comment by jpradocueva** [comment]
@mojanm I haven't seen any evidence that they are using Object Versioning. In addition, I believe that these object were registered before introducing Object Versioning.

**Comment by jpradocueva** [comment]
In the current OMNA repository the Reusable Resources:
 * 5514 is dedicated to "Latitude"
 * 5515 is dedicated  to "Longitude"
 * 6039 is dedicated to "Altitude"
