### ISSUE TITLE
OMNA Registration - Object 10300

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#255]
OMNA Registration requested by Huawei Technologies Co., Ltd.
Object pending for review [10300](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2Flwm2m%2FRegistrations%2F10300.xml)

Download file
[10300.zip](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/files/1502202/10300.zip)

**Comment by jpradocueva** [comment]
Feedback on this registration:
* The Object is missing the software license, please use [LwM2M Editor License](http://devtoolkit.openmobilealliance.org/OEditor/License) to add a license.
* Is this registration part of the Enabler called: **Binary Application Data Container**? If yes, then it should not be registered as ```x-label Object``` . It should be added as a supporting file to the Enabler **Binary Application Data Container**.

**Comment by jpradocueva** [comment]
This request is a duplication of 10286 Object. 
See #243 therefore it is closed.
