### ISSUE TITLE
Need clarification about X.509 certificate.

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#257]
I would like to better understand how X.509 certificate is intended to be used in LWM2M v1.0.x.
(I will ask several questions, if needed I can split this issue in many, just let me know)

In [RFC 6698](https://tools.ietf.org/html/rfc6698#section-2.1.1) (referenced by LWM2M spec), there is 4 certificate usage defined. ("CA constraint", "service certificate constraint", "trust anchor assertion", "domain issue certifcate"). The LWM2M spec clearly say that only "domain issue certificate" is supported.  

1) Does this restriction concern only server certificate usage ? (or also client certificate usage ?)
2) If this does not concern client certificate usage ? what are client certificate usage supported ?
3) Does this restriction concern also EST mode ?
4) What are reasons of this restriction ?  

The LWM2M spec describe what is "reference identifier" and "presented identifier" for a server certificate.
If I understand well: in case of use of  "fully qualified DNS domain name"  `dNSName` field MUST be used (for LWM2M §7.1.9) and also `SubjectAltName` or `Common Name` (for [CoAP §9](https://tools.ietf.org/html/rfc7252#section-9.1.3.3)).

5) Both are needed,  am I right ?

What about client certificate, the LWM2M spec is not so clear... 

6) I understand that endpoint client name should be used as reference identifier(§7.1.5) but which certificate field should be used to extract the presented identifier ?

Thx
(a bit out of topic, but this would be good to have en html version of the LWM2M spec (like IETF one) to be able to link chapter)

**Comment by sbernard31** [comment]
@hannestschofenig any input on this ?

**Comment by hannestschofenig** [comment]
Thanks for your questions. You raise a number of questions. Let me try to answer them one by one: 

> The LWM2M spec clearly say that only "domain issue certificate" is supported.
> Does this restriction concern only server certificate usage ? (or also client certificate usage ?)

It refers to the server certificate usage, which is also the scope of RFC 6698. 

> If this does not concern client certificate usage ? what are client certificate usage supported ?
Client authentication is just very different from server authentication. 

> Does this restriction concern also EST mode ?
This restriction is independent of the way how certificates are provisioned. Hence, it also applies to the EST mode. 

> What are reasons of this restriction ?
The PKI model is quite sophisticated and allows different ways to use it. In LwM2M v1.0 the group wanted to go for the most simplistic model only. With v1.1 we will add further modes. 

> The LWM2M spec describe what is "reference identifier" and "presented identifier" for a server certificate. If I understand well: in case of use of "fully qualified DNS domain name" dNSName field MUST be used (for LWM2M §7.1.9) and also SubjectAltName or Common Name (for CoAP §9).

> Both are needed, am I right ?
https://tools.ietf.org/html/rfc6125 describes the terms and the procedure in great detail. 

> What about client certificate, the LWM2M spec is not so clear...
For the client certificate the story is much easier and maybe we should explain that as well. For the client certificate used with the bootstrap server the bootstrap server essentially has to get the necessary information from the factory (or whatever mechanism is used to get them to the device initially). This way the bootstrap server can authenticate the client. For the LwM2M server authenticating the LwM2M client there is also some flexibility. For example, the bootstrap server may provide the information about the distributed client certs to the LwM2M servers or, if a dedicated CA is used, then the LwM2M server may just be happy enough to verify that the client certificate has been signed by the dedicated CA. 

> I understand that endpoint client name should be used as reference identifier(§7.1.5) but which certificate field should be used to extract the presented identifier ?

This is not further specified in LwM2M v1.0 and there may be additional text in v1.1. In some sense deployments can use whatever policy they prefer. TLS / DTLS stacks typically provide APIs to access these fields and so server implementation can be configured to compare whatever a specific deployment prefers.

**Comment by sbernard31** [comment]
Thanks a lot @hannestschofenig for your responses. This helps a lot.

**Comment by sbernard31** [comment]
@hannestschofenig,  about your last comment : 

>This is not further specified in LwM2M v1.0 and there may be additional text in v1.1. In some sense deployments can use whatever policy they prefer. TLS / DTLS stacks typically provide APIs to access these fields and so server implementation can be configured to compare whatever a specific deployment prefers.

I see in the LWM2M v1.0.x, *§8.5 Response Codes* : 
_"Endpoint Client Name does not match with CN field of X.509 Certificates"_
(This is also present in LWM2M v1.1)

Which seems to say that CN field should be equals to endpoint name.

What do you think about that ?
