### ISSUE TITLE
OMNA-Registration of Cellular connectivity

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#266]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2017-12-07 14:06:16 UTC</td></tr><tr><td>Submitter's name</td><td>Sandeep Akhouri</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Cellular connectivity</td></tr><tr><td>Object Description</td><td>Cellular connectivity object</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=d9ba8ac7-79dc-467b-a49d-4875962f057c_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=d9ba8ac7-79dc-467b-a49d-4875962f057c_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration cannot be accepted via OMNA.
OMA Objects cannot be registered via OMNA. The submitter needs to create inside of OMA a new Work Item to create a new revision of this Object as the enabler is already approved.
