### ISSUE TITLE
Can Server DELETE 4/0, 5/0, 6/0, 7/0 ?

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#270]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS_LightweightM2M-V1_0_1-20170704-A
* Section of the document, ``(e.g. section: 6.2)``: section 5.4.7
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:
``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

TS says, "The only exception concerns the single Instance of the mandatory Device Object (ID:3) which SHALL NOT be affected by any Delete operation."
Does it mean that Server can delete 4/0, 5/0, 6/0, 7/0?  
I think that, these object instances (Connectivity Monitoring, Firmware, Location, Connectivity Statistics) were created by device(LWM2M Client). therefore, these object instances are not allowed to be deleted by Server.

**Comment by hannestschofenig** [comment]
> Does it mean that Server can delete 4/0, 5/0, 6/0, 7/0?

yes, if it has the access rights.
