### ISSUE TITLE
OMNA-Registration of fuxd_ufi

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#273]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-01-10 04:05:15 UTC</td></tr><tr><td>Submitter's name</td><td>fuxd</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>fuxd</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>fuxd_ufi</td></tr><tr><td>Object Description</td><td>fuxd_ufi</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=6b0f031d-f024-405a-a2bc-fec43d6bb880_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=6b0f031d-f024-405a-a2bc-fec43d6bb880_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is empty.
