### ISSUE TITLE
How are APNs mapped to operator network?

### ISSUE THREAD

**Issue by lauri-piikivi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#275]
SPEC: Regarding the spec: Lightweight M2M – Connectivity Management Object (LwM2M Object – ConnMgmt) Approved Version 1.0 – 14 Mar 2017 Open Mobile Alliance OMA-TS-LWM2M_ConnMgmt-V1_0-20170314-A

The mapping of APN to operator is unclear. The device chooses network based on RAT (bearer) and operator list. But it is not defined what APNs map to the operator selected ? 

Does the APN stay the same when roaming?  Does seem to behave so for generic internet APN in normal phone. If this is the correct understanding, it might be clarified in the doc.

**Comment by ytava** [comment]
Usually the same APN is used also when roaming (should be acceptable under roaming agreements).
However i believe that indeed there is a gap in LWM2M spec dealing with different APNs (PDNs) for different LWM2M servers. 
Multiple cellular carriers require that carrier server (for ex. DM server) would be accessed through Admin APN (closed NW) while other LWM2M server (for ex. for FOTA or diagnostics) would be accessed through the main Internet APN. 

I believe that during bootstrap process, bootstrap server should configure a kind of mapping of which APN should be used for each LWM2M server being configured.

**Comment by asoloway64** [comment]
Object 11, APN Connection Profile, contains Resource 8, Validity, to indicate which PLMNs (MCC/MNC) the APN is valid for.
