### ISSUE TITLE
Need clarification of Data format TLV response on single resource request

### ISSUE THREAD

**Issue by Gopishankarp** [OpenMobileAlliance/OMA_LwM2M_for_Developers#276]
SPEC : OMA-TS-LightweightM2M-V1_0-20170208-A.
**6.4 Data Formats for Transferring Resource Information**
For data format TLV , Type field when server is sending a read request to the client for a single resource value E.g ( 1/0/1 )  **Lifetime**(id 1) resource in **Server**(id 1) object, so path /1/0/1.

In the Client response , TLV header identifier type is 00 which is object instance (**00.. .... = Type of Identifier: Object Instance (0)** ) . 
According to the document , each TLV entry starts with a Type byte that indicates if the TLV contains an Object Instance, a Resource, multiple Resources, or a Resource Instance.
Here in the response , it should be 11 but in the client response it is 00(Object Instance). Is it right ?
or object instance TLV could be sent on resource request ?

**Response from the client:**

<img width="445" alt="tlv_response_hex" src="https://user-images.githubusercontent.com/22880479/35132305-910ccb42-fcf0-11e7-8296-0d48e46e0467.PNG">

**Comment by ThGarnier** [comment]
Yes you are right, the answer for a simple Resource could be of having a TLV with Type identifier 11.
However, if the Client sends back an answer starting from the top hierarchy of the object Instance, it is not wrong : The Spec say 00: Object Instance in which case the Value contains ONE or more Resource TLV; so both cases are acceptable; with 11 it will be shorter, however maybe the Client implemenation could consider it is more efficient to systematically use the same approach to reply. Do you agree ?

**Comment by sbernard31** [comment]
Could you explain what are the benefit about supporting both cases in the specification ?
It seems to me that just make implementation a bit more complicate to allow to consume more bandwidth.

**Comment by sbernard31** [comment]
@ThGarnier  ping!

**Comment by hannestschofenig** [comment]
Having two ways to accomplish the same goal allows the implementer to select the best approach.

**Comment by sbernard31** [comment]
OK but this also forces to support both approach to keep interoperability...

And more than that in this case, there is 1 approach which clearly worst than the other ...
