### ISSUE TITLE
Only port 5683 mentioned for both coap and coaps in 8.2.1

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#277]
OMA-TS-LightweightM2M-V1_0_2-20171207-D, page 74, 8.2.1 Firewall/NAT

> For a firewall to support LwM2M, it should be configured to allow outgoing UDP packets to destination port 5683 (other ports can be configured), and allow incoming UDP packets back to the source address/port of the outgoing UDP packet for a period of at least 240 seconds. These UDP packets may contain DTLS or CoAP payloads. When a firewall is configured as such any LwM2M Clients behind it should use Queue Mode.
> For a firewall to support LwM2M it can be configured to allow both outgoing and incoming UDP packets to destination port 5683 (other ports can be configured). These UDP packets may contain DTLS or CoAP payloads. When a firewall is configured as such any LwM2M Clients behind it are not required to use Queued Mode, but may use it for other reasons (e.g., a battery powered sleeping device).

Is the intention to use port 5683 also for DTLS?
Any reason, why LWM2M wants to differ from RFC7252, 12.7, which defines 5684 for DTLS.

https://tools.ietf.org/html/rfc7252#section-12.7

**Comment by hannestschofenig** [comment]
Thanks for spotting this bug. The intention is, of course, to follow RFC 7252 and to use one port for CoAP over UDP and another port for CoAP over DTLS over UDP. 

It will be corrected in LwM2M v1.1.

**Comment by boaks** [comment]
Thanks!
