### ISSUE TITLE
Behavior when server writes the same value of lifetime

### ISSUE THREAD

**Issue by kporwal20** [OpenMobileAlliance/OMA_LwM2M_for_Developers#278]
Hi All,

As per the OMA-TS-LightweightM2M-V1_0_1-20170704-A/Section - 5.3.2 Update.

Snippet:
![image](https://user-images.githubusercontent.com/31787876/35376614-d705285c-01d1-11e8-8051-4ddda4cd54b7.png)

It is clearly mentioned that on a CHANGE in the value of lifetime, the client MUST send out a reg. update.

Question: For example, lifetime value of resource /1/x/1 is 86400, and server writes the same value of lifetime i.e. 86400 on /1/x/1. Since, it is not a CHANGE in the value, should the client send a Registration Update to the server?

**Comment by hannestschofenig** [comment]
Since the value has not changed it will not send a Registration Update. However, why should the server send a value that is already pre-configured. In that case it would be better not to write the same value again.

**Comment by kporwal20** [comment]
@hannestschofenig Thanks for the clarification.
Agreed, that the server MUST not write the same value of the lifetime logically. But given all the access rights an LwM2M server can have, isn't it that the server can right any value, whether same or different, for that matter. You can correct me if I am wrong?
The idea was to discuss regarding the behavior when the server writes the same value of lifetime explicitly.

**Comment by hannestschofenig** [comment]
It is implementation-dependent on how you interpret what constitutes a change. The group decided not to change the specification.
