### ISSUE TITLE
OMNA-Registration of ttt

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#282]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-02-05 05:35:15 UTC</td></tr><tr><td>Submitter's name</td><td>ww</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ttt</td></tr><tr><td>Object Description</td><td>xxx</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8cdc80e2-aeee-4757-9aa4-e08962b15b2d_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8cdc80e2-aeee-4757-9aa4-e08962b15b2d_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is not valid.
