### ISSUE TITLE
[implementation-specific] issue with smaller lifetime values

### ISSUE THREAD

**Issue by GiedriusM** [OpenMobileAlliance/OMA_LwM2M_for_Developers#283]
When submitting an issue please indicate the following information:
* Name, version and date of the document: OMA-TS-LightweightM2M-V1_0_1-20170704-A
* Section of the document: Section 5.3
* Sequence of exchanges between Client and Server: client sends periodic updates via CoAP

```
The registration is soft state, with a lifetime indicated by the Lifetime Resource of that LwM2M Server Object Instance.
....
If the lifetime of a registration expires without receiving an update from the LwM2M Client:
* the LwM2M Server MUST remove the registration of that Client;
```

This means that the update message must reach WITHIN the lifetime, including any delays caused by transport (CoAP) layer. From the client perspective, to be sure that the update will be delivered in time, it must send update every `lifetime - COAP_MAX_EXCHANGE_LIFETIME`. With default settings COAP_MAX_EXCHANGE_LIFETIME is 247 seconds, which is fine when the lifetime has a much larger value. Things change when lifetime becomes close to (or even less than) COAP_MAX_EXCHANGE_LIFETIME. For example:

* if lifetime is 10 minutes (600 seconds), updates should be sent every 5.8 minutes (600-247 seconds). Not ideal, but fine.
* if lifetime is 5 minutes (300 seconds), updates should be sent every 53 seconds. This starts to get ineffiecient, because updates are sent five times more frequently than they __usually__ should be.
* if lifetime is less than or equal 4 minutes (247 seconds), the updates should be sent one after another, i.e. __flooding__ the server.

The main problem I see here is that the COAP_MAX_EXCHANGE_LIFETIME is dependent on client side CoAP configuration and it can be different for different clients, therefore application which wants to change the lifetime cannot adjust for it. However there are cases, where small lifetime if required and setting it to the same value (say 200 seconds) to multiple clients/implementations may result in very different results - some will flood, some will send periodically.

I am looking for any comments or suggestions how this implementation specific issue could be resolved.

Thank you!

**Comment by sbernard31** [comment]
Could you define a bit more the use case where a lifetime is lesser than 5 or 10 minutes ?

**Comment by sbernard31** [comment]
> First, and most importantly, my concern is that there is no general solution or any guidance from LwM2M standard how this issue should be addressed. Especially the update flood scenario. IMO the standard could state the minimum delay between two consecutive update messages.

You're right, the specification should details issue about using a small lifetime or just discouraged to use it.

FMPOV, lifetime is more a server concept which means  "hey devices, if you don't talk to me before `lifetime` seconds I will consider you left me".

That's means to me that you can have a life time of 1800s and a devices which talks each 30 or 60s. This is not a problem.

In other words,  lifetime should not be use to configure communication period of device using queue_mode.

If we need to configure this communication period, maybe we need a new resource. 
(I don't know if it should be a Device(3) resource or a Server(1) one)

**Comment by GiedriusM** [comment]
> FMPOV, lifetime is more a server concept which means "hey devices, if you don't talk to me before lifetime seconds I will consider you left me".

> In other words, lifetime should not be use to configure communication period of device using queue_mode.

I fully agree with you, but it was the closest I could find that would allow changing update period. The fact that client provides it during registration the server is even more suggestive.


> If we need to configure this communication period, maybe we need a new resource.

I had a though of suggesting a new resource, but then could not answer to myself:
* Should (update period + exchange lifetime) > lifetime be allowed? Or even update period > lifetime?
* If so what to do when update period is increased? Should the lifetime be automatically updated?
* What if lifetime is decreased?
* If above is true, then what's the actual difference between the two?

I would be happy to have update period resource if the details are clear in the standard.
Slightly different idea was to have "exchange lifetime" resource in the Device(3) object, so that an application could calculate and adjust the lifetime accordingly to client configuration.

> (I don't know if it should be a Device(3) resource or a Server(1) one)

Almost definitely in the Server(1). Different application/services may require different update periods and it would be a waste of battery juice if many updates had to be sent frequently in a scenario where only one of them had to be.

**Comment by sbernard31** [comment]
Just my 2 cents : 

> Should (update period + exchange lifetime) > lifetime be allowed? Or even update period > lifetime?
> If so what to do when update period is increased? Should the lifetime be automatically updated?
> What if lifetime is decreased?

We can imagine 2 solutions : 
1. device does not allow a server to set a (period < lifetime- coap echange lifetime )
2. device uses the smaller between (period and  lifetime- coap echange lifetime) as communication period. 

I prefer 2. because 
 - with 1. the server should know period value to set lifetime value and vice versa.
 - with 2. configuring period could be optional. 

> If above is true, then what's the actual difference between the two?

I see lifetime as a kind of "session lifetime" and period as a kind  "application feature".

> Slightly different idea was to have "exchange lifetime" resource in the Device(3) object, so that an application could calculate and adjust the lifetime accordingly to client configuration.

I prefer both solution above because this sounds to me more straightforward. (but this is really subjective)

> Almost definitely in the Server(1)

I feel you're right about that.

**Comment by GiedriusM** [comment]
> device uses the smaller between (period and lifetime- coap echange lifetime) as communication period.

What do you think should be done when the period or (lifetime - coap echange lifetime) is equal to or less than zero?



> I prefer both solution above because this sounds to me more straightforward. (but this is really subjective)

I believe more feedback and thoughts are needed from other people, especially those that are working on the standard and those, that are working on implementations.

**Comment by sbernard31** [comment]
> What do you think should be done when the period or (lifetime - coap echange lifetime) is equal to or less than zero?

period <= 0 could means "do not communicate periodically" (except to maintain your registration alive)
For lifetime we could raise a bad request.

> I believe more feedback and thoughts are needed from other people, especially those that are working on the standard and those, that are working on implementations.

👍

**Comment by GiedriusM** [comment]
> For lifetime we could raise a bad request.

```
5.9.2.1.  4.00 Bad Request

   This Response Code is Like HTTP 400 "Bad Request".
```

then going to https://tools.ietf.org/html/rfc7231#section-6.5.1

```
400 Bad Request

The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
```

it gives a sense that 400 is used for a request that is malformed in one or another way and is not concerned with the content.

Something like https://tools.ietf.org/html/rfc4918#section-11.2 would be more suitable
```
422 Unprocessable Entity

The server understands the content type of the request entity (hence a 415 Unsupported Media Type status code is inappropriate), and the syntax of the request entity is correct (thus a 400 Bad Request status code is inappropriate) but was unable to process the contained instructions.
```

Too bad there's no 4.22 in CoAP :(

**Comment by hannestschofenig** [comment]
I was wondering about two things: 

1) Why do you need to use the default value of EXCHANGE_LIFETIME? 
2) Why do you set your registration lifetime to such a short value? I would set it to longer lifetime, still use Queue Mode but send Registration Updates when the device wakes up.

**Comment by GiedriusM** [comment]
> Why do you need to use the default value of EXCHANGE_LIFETIME?

I don't follow the question...

> Why do you set your registration lifetime to such a short value? I would set it to longer lifetime, still use Queue Mode but send Registration Updates when the device wakes up.

To have a **small** and **configurable** update period and a **reliable** connection. Let's say you have battery operated alarm system, therefore queue mode. The sensors wake up only when triggered or when they need to send LwM2M update. You may want to arm/disarm it within a reasonable timeframe or detect a jamming (**small** update period and in part **reliable** connection). Some security components (say, a certain zone) may not need such small latency so to save battery power you need **configurable** period. Also, a sensor may be connected to multiple servers and only one of them may need a small latency (configurable per server). And a **reliable** connection is in relation with CoAP being lossy and having the exchange lifetime.

You suggestion would only work if there was a trigger to wake up a device - a "default update period". Currently there's no such resource in LwM2M (not **configurable**). The closest I can find is server lifetime. But the update should be sent no less than every `lifetime - coap exchange lifetime`, otherwise you may end up with client timeout in lossy environment (not **reliable**). And here problem with small server lifetime (less than coap exchange lifetime) appears.

**Comment by hannestschofenig** [comment]
The group discussed this issue. The LwM2M specification does not provide any recommendation regarding the lifetime settings and leaves it as implementation dependent. The most suitable value has to be determined by those deploying the technology.

**Comment by sbernard31** [comment]
I think, there is maybe a misunderstanding, here we said that we need 2 values/resources :  

 - a Lifetime which will be used to delete state at server side after no sign of life of a device.
 - an update period which would be optional and configurable by server and which could be used to control the approximative period between 2 registration update .

So this could not be leaved at implementation as we need a new LWM2M resources in `Device` or `server` object.

**Comment by GiedriusM** [comment]
> The group discussed this issue. The LwM2M specification does not provide any recommendation regarding the lifetime settings and leaves it as implementation dependent. The most suitable value has to be determined by those deploying the technology.

Looking at the answer it does not seem that the issue was understood in it's entirety.

> I think, there is maybe a misunderstanding, here we said that we need 2 values/resources :
> 
> * a Lifetime which will be used to delete state at server side after no sign of life of a device.
> * an update period which would be optional and configurable by server and which could be used to control the approximative period between 2 registration update .
> 
> So this could not be leaved at implementation as we need a new LWM2M resources in `Device` or `server` object.

Yes, this would be one of the (best) solutions.
