### ISSUE TITLE
Cancel Observations on Object level

### ISSUE THREAD

**Issue by kporwal20** [OpenMobileAlliance/OMA_LwM2M_for_Developers#291]
OMA-TS-LightweightM2M-V1_0_1-20170704-A
Section: 5.5.3 Cancel Observation

![image](https://user-images.githubusercontent.com/31787876/36048905-ccbeffbc-0e06-11e8-8433-83546c5a985d.png)

With reference to the description of Cancel Observation, the spec talks about cancelling the observations on Object Instance and Resource level but doesn't mention anything regarding the behavior for cancelling observations on object level.

Queries:
1. Is the behavior for Cancel operation expected to be same as that of Object Instance/Resource level?
2. Or, The cancel at object level MUST not be allowed? As in, is it entirely server deployment based expectation?

Thanks!

**Comment by mojanm** [comment]
Looks to be miswording in the spec. In my view it should simply read:
The “Cancel Observation” operation is sent from the LwM2M Server to the LwM2M Client to end an observation relationship.
