### ISSUE TITLE
OMNA-Registration of LampState

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#296]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-03-05 10:25:58 UTC</td></tr><tr><td>Submitter's name</td><td>wuqingfan</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>shanghaisansi</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LampState</td></tr><tr><td>Object Description</td><td>de</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=f7604aef-20e3-4156-b0fd-4bc0403704d8_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=f7604aef-20e3-4156-b0fd-4bc0403704d8_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This is an invalid registration request.
