### ISSUE TITLE
OMNA-Registration of brightness

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#298]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-03-06 11:16:52 UTC</td></tr><tr><td>Submitter's name</td><td>wuqingfan</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>shanghaisansi</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>brightness</td></tr><tr><td>Object Description</td><td>bright</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=2716d20d-e7ad-4473-8753-ac2c1c14d5d7_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=2716d20d-e7ad-4473-8753-ac2c1c14d5d7_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This is an invalid request.
