### ISSUE TITLE
Is it OK for a client to De-Register during Firmware Update?

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#300]
I'm basing this question on the TS 1.0.2.

When an LwM2M server executes the /5/0/2 Resource (Firmware Update / Update), the client is supposed to apply a downloaded firmware image, which is most likely followed by a reboot with a new version - which in most implementations involves sending Register message to the LwM2M Server(s).

The question is - is it permitted to first De-Register before applying the firmware and rebooting? And if the client does so, how should the Server interpret such act?

Section 5.3.3 "De-register" states that:
> Upon receiving this message, the LwM2M Server removes the registration information from the LwM2M Server.

This might be interpreted as implying that the Server shall forget information about the client's state, including the expectations about the Firmware Update state. On the other hand, sending De-Register is common thing to do for Client implementations during a "graceful shutdown" procedure, and it seems to make sense to do a graceful shutdown before flashing firmware image.

Similar question may be asked about the Reboot operation (/3/0/4).

**Comment by fdur** [comment]
Very good question !!!

**Comment by hannestschofenig** [comment]
Here is my take on it. 

If the firmware image is obtained from a LwM2M server then de-registering from it right before or during the firmware update download is not a good idea. The consequence would be a discontinued firmware update process. 

If the firmware image is obtained via third party repository then the firmware update download should not be impacted from de-registering from a LwM2M.

**Comment by kFYatek** [comment]
> If the firmware image is obtained from a LwM2M server then de-registering from it right before or during the firmware update download is not a good idea.
What about after the download, but before actually applying (flashing) it? What do you think about that case?

**Comment by hannestschofenig** [comment]
If you de-register once you reached the "Downloading" state then the server will not be able to initiate the transition to the "updating state", according to the state machine. The server will also not be able to observe the status of the firmware update process itself.

**Comment by kFYatek** [comment]
I rather meant a flow such as:
1. Successful firmware image download
2. Client reaches "Downloaded" state
3. Server calls Execute on the "Update" resource
4. Client reaches "Updating" state, sending relevant notifications if applicable
5. Client sends De-Register
6. Actual firmware upgrade process
7. Client reboots with the new firmware and registers with the server again; the firmware object is in the "Idle" state with result set to "Success" or any appropriate error result

What do you think about such flow? Is it appropriate, or should the client avoid sending the De-Register message? Note that sending Register is most likely required anyway, unless the client is somehow able to store its whole state (including DTLS sessions) in some non-volatile memory across a firmware upgrade.

**Comment by GiedriusM** [comment]
Referencing reboot issue #280

**Comment by hannestschofenig** [comment]
Since de-registration is not mandatory the recommended way would be to keep the registration, to then reboot after the firmware update, and to then re-register once the device has started with the new firmware.
