### ISSUE TITLE
OMNA-Registration of temp

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#301]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-03-21 12:13:20 UTC</td></tr><tr><td>Submitter's name</td><td>aolian</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>temp</td></tr><tr><td>Object Description</td><td>tempture</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=891498a4-a884-4d9b-a186-01b9eb897e7d_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=891498a4-a884-4d9b-a186-01b9eb897e7d_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
This is an invalid registration request.
