### ISSUE TITLE
OMNA-Registration of Smart_street_lamp

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#302]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-03-26 06:18:02 UTC</td></tr><tr><td>Submitter's name</td><td>浙江魔豆科技有限公司</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Smart_street_lamp</td></tr><tr><td>Object Description</td><td>Smart street lamp</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8362c90f-df94-4f4c-9578-dcd7785ed31a_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8362c90f-df94-4f4c-9578-dcd7785ed31a_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
This is an invalid registration request.
