### ISSUE TITLE
LWM2M block-wise notify issue

### ISSUE THREAD

**Issue by aforster23** [OpenMobileAlliance/OMA_LwM2M_for_Developers#303]
We are using the CoAP block-wise transfer method when any LWM2M resources that we are observing are larger than normal size. In such cases, the device will wake up each day and notify its observed resource to the server via the block-wise method. This all works fine, with the device sending the first CON block #0 packet, followed by the server requesting all remaining packets using GET for each remaining block.

The problem arises where the very last block is being sent as a piggyback ACK + content message in response to the GET from the server. If , for some reason, this last ACK block from the device fails to reach the server, the server will start re-trying the previous GET message. However, our device has already progressed to sending other notifications (related to other observed resources) after which it will disconnect from the network (as it uses an NB-IOT optimization to disconnect once it has sent its final packet). Meanwhile the retry GETs from the server won't get through as the device will have disconnected already. 

Our solution is to change the device so that it separates the piggy-back response for the very last block into a separate ACK (to the GET) followed by a CON + block content. The server will then need to ACK this message before the device then progresses on to its next task (which is notifying other resources before disconnecting from the network).

Does anyone have a more elegant solution to this issue?

Thanks

**Comment by hannestschofenig** [comment]
I am wondering whether this is really an issue with LwM2M. It almost appears that this is related to the timing and the use of block-wise transfer. 

Could you send a message flow diagram so that I can see whether I properly understand the interaction?

**Comment by aforster23** [comment]
Hi, please see wireshark attached for how we are now achieving our desired outcome for block-wise notification, with the last packet being a CON message from the device.
Welcome any comments. thanks


![lwm2m blockwise notify](https://user-images.githubusercontent.com/37088626/39334130-f7fb52e4-499c-11e8-8f8c-c7156132e900.PNG)

**Comment by hannestschofenig** [comment]
We discussed this topic in the OMA DM group and we believe that this is an issue that should be discussed in the IETF since it has nothing to do with LwM2M itself but is a topic related to the blockwise transfer spec.
