### ISSUE TITLE
OMNA-Registration of RDB

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#304]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-04-15 23:19:46 UTC</td></tr><tr><td>Submitter's name</td><td>Adrian Taylor</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>NetComm Wireless Limited</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>RDB</td></tr><tr><td>Object Description</td><td>This object allows manipulation of Runtime Database variables.</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=9f77cf75-327a-4e2a-a8b0-6387f9fa2db4_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=9f77cf75-327a-4e2a-a8b0-6387f9fa2db4_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
The XML file submitted has listed this Object as 10260 which has already taken by Runtime Database.
Could you update the Object ID for RDB to 10301

**Comment by jpradocueva** [comment]
This registration can be also interpreted as a new revision of the Object.
DM Working Group needs to clarify if this new registration can be considered as version 1.1 of this already registered Object.

**Comment by adriant-ntc** [comment]
Apologies if this was not the correct way to do it, but yes, this submission is intended to be an updated version of object 10260.

**Comment by adriant-ntc** [comment]
Hi,
Just wanted to ask about the status of this submission. Is any action currently required on my part?

**Comment by jpradocueva** [comment]
@padhupadhu, @ThGarnier  DMSE needs to review this registration.

**Staff input**
- [ ] The URN should be updated to reflect the Object Version ```urn:oma:lwm2m:x:10260:x.y```
- [ ] DMSE Working Group should confirm the Object Version (x.y) for this re-registration. 
    * Mandatory Resource, ```Unset``` is removed, 
    * Mandatory Resources, ```Value``` and ```Persistent``` are demoted from Mandatory to Optional
then the new Object should then be registered as version ```2.0```. 

Please confirm.

Note: as this is the first time that we have a new Object Version of an existing Object, we would like that DMSE Working Group provides his input.

**Comment by jpradocueva** [comment]
@adriant-ntc 
Based on DM WG internal reply, the Object should registered as v2.0:
* ```Object ID:``` 10260
* ```File name:``` 10260-2_0.xml
*  ```URN:``` urn:oma:lwm2m:x:10260:2.0
* ```Object Version:``` 2.0

Please apply the corresponding changes and we will proceed with the registration.
Thanks

**Comment by adriant-ntc** [comment]
Done, updated submission at #332.

Thanks,
Adrian

**Comment by jpradocueva** [comment]
Superseded by Issue #332
