### ISSUE TITLE
IPSO Smart Objects definition inconsistencies

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/OMA_LwM2M_for_Developers#309]
Contact details - harri.hytonen@vaisala.com - Organisation - Vaisala. 
We are planning to use LwM2M for device management and monitoring in our weather and environmental sensors. 
What puzzles me is the definition of some IPSO Smart Objects in OMA Registry. Some objects define the “Unit” resource (ID 5701) as type “Float” and some “String”.  For example, “Generic Sensor” 3300, “Voltage” 3316, “Current” 3317 (and many more) define Unit as Float. 
I wonder if this is a mistake or if is some logic behind this? This is irritating us quite a lot and slowing down our plans to take LwM2M in use. 
If the type definition is a mistake, then I kindly request that all Unit resources will be harmonized to String type.

Objects with “Float” type Unit resource:
[1]  [3300](http://www.openmobilealliance.org/tech/profiles/lwm2m/3300.xml) 
[2]  [3316](http://www.openmobilealliance.org/tech/profiles/lwm2m/3316.xml) 
[3]  [3317](http://www.openmobilealliance.org/tech/profiles/lwm2m/3317.xml)

**Comment by sznaider** [comment]
Not only 3300, 3316, 3317 are affected, but also:
- [3318](http://www.openmobilealliance.org/tech/profiles/lwm2m/3318.xml)
- [3319](http://www.openmobilealliance.org/tech/profiles/lwm2m/3319.xml)
- [3320](http://www.openmobilealliance.org/tech/profiles/lwm2m/3320.xml)
- [3321](http://www.openmobilealliance.org/tech/profiles/lwm2m/3321.xml)
- [3322](http://www.openmobilealliance.org/tech/profiles/lwm2m/3322.xml)
- [3323](http://www.openmobilealliance.org/tech/profiles/lwm2m/3323.xml)
- [3324](http://www.openmobilealliance.org/tech/profiles/lwm2m/3324.xml)
- [3325](http://www.openmobilealliance.org/tech/profiles/lwm2m/3325.xml)
- [3326](http://www.openmobilealliance.org/tech/profiles/lwm2m/3326.xml)
- [3327](http://www.openmobilealliance.org/tech/profiles/lwm2m/3327.xml)
- [3328](http://www.openmobilealliance.org/tech/profiles/lwm2m/3328.xml)
- [3329](http://www.openmobilealliance.org/tech/profiles/lwm2m/3329.xml)
- [3330](http://www.openmobilealliance.org/tech/profiles/lwm2m/3330.xml)
- [3346](http://www.openmobilealliance.org/tech/profiles/lwm2m/3346.xml)

**Comment by jpradocueva** [comment]
@sznaider the IPSO WG inside of OMA is aware of these issues and they are working in resolving them.
