### ISSUE TITLE
OMNA-Registration of Generic Sensor

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#331]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-10 01:03:13 UTC</td></tr><tr><td>Submitter's name</td><td>Ａｎｄｙ</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Ningbo maidu zhilian technology co. LTD.</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Generic Sensor</td></tr><tr><td>Object Description</td><td>smoke fire detector</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=9bc9d29f-9ed5-4b5d-898c-2687b150f34c_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=9bc9d29f-9ed5-4b5d-898c-2687b150f34c_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is not valid. It aims to re-register an existing Object.
