### ISSUE TITLE
OMNA-Registration of RDB

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#332]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-13 23:36:58 UTC</td></tr><tr><td>Submitter's name</td><td>Adrian Taylor</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>NetComm Wireless Limited</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>RDB</td></tr><tr><td>Object Description</td><td>This object allows manipulation of Runtime Database variables.</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=4d16775f-9275-43d2-b27f-fcc3c8656a96_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=4d16775f-9275-43d2-b27f-fcc3c8656a96_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Registration Details:
```Location of the Object to register:``` ftp://wwwftp.openmobilealliance.org/tech/profiles/lwm2m/10260-2_0.xml
```URN:``` ```urn:oma:lwm2m:x:10260:2.0```
```xml link:``` 10260-2_0
```LwM2M Editor link:``` 10260-2_0
```Name:``` Runtime Database
```Company:``` NetComm Wireless Limited
```Description```:  This object allows manipulation of Runtime Database variables.

**Comment by seanmcilroy29** [comment]
Object updated in the DEV area http://devwww.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html 
* Links opens up in XML and tool editor
* XML doc is valid against the schemas

**Comment by jpradocueva** [comment]
New object registration seems correct:
http://dev_devtoolkit.openmobilealliance.org/OEditor/OMNAVerify
 * Tool needs to be updated to deal with dual registration (Object ID) 

READY for PUBLICATION

**Comment by seanmcilroy29** [comment]
Object has been applied to OMNA registry under 10262 http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#x_label

**Comment by jpradocueva** [comment]
Document was registered as 10260 Revision 2.0
http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=http%3A%2F%2Fwww.openmobilealliance.org%2Ftech%2Fprofiles%2Flwm2m%2F10260-2_0.xml
