### ISSUE TITLE
OMNA-Registration of oA Basic Control

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#333]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-14 12:45:02 UTC</td></tr><tr><td>Submitter's name</td><td>Georg Kuenz</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>OpenAIS</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>oA Basic Control</td></tr><tr><td>Object Description</td><td>oA Basic Control</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=0aa128d0-7407-402c-b076-28abe334ca45_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=0aa128d0-7407-402c-b076-28abe334ca45_Object.xml">Load Editor with object</a></td></tr>

**Comment by mojanm** [comment]
All OpenAIS proposed objects have “Documentary Description” resource, resource id 901, which is of type string and length 256. It would be better if this is defined as a reusable resource in the reusable resource ID range.

**Comment by jpradocueva** [comment]
The discussion of this submission has been moved to: https://github.com/jpradocueva/public-openAIS
