### ISSUE TITLE
OMNA-Registration of oA Logical Colour Temperature Light-Point Actuator

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#337]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-14 12:49:55 UTC</td></tr><tr><td>Submitter's name</td><td>Georg Kuenz</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>OpenAIS</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>oA Logical Colour Temperature Light-Point Actuator</td></tr><tr><td>Object Description</td><td>oA Logical Colour Temperature Light-Point Actuator</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=b67f1ec2-a272-4eb1-a09e-6070411a0b24_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b67f1ec2-a272-4eb1-a09e-6070411a0b24_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
The discussion of this submission has been moved to: https://github.com/jpradocueva/public-openAIS
