### ISSUE TITLE
OMNA-Registration of oA Security

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#351]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-05-14 15:09:28 UTC</td></tr><tr><td>Submitter's name</td><td>Georg Kuenz</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>OpenAIS</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>oA Security</td></tr><tr><td>Object Description</td><td>oA Security</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=efec17f9-5e16-4848-88bf-3e1f75efea3b_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=efec17f9-5e16-4848-88bf-3e1f75efea3b_Object.xml">Load Editor with object</a></td></tr>

**Comment by mojanm** [comment]
Comment column in the object defintion for Resource 5, Secret Group Key, indicates Read operation on the resource is not permitted by any server. If that is the intention, the operation column should reflect this; currently set to RW.

**Comment by jpradocueva** [comment]
The discussion of this submission has been moved to: https://github.com/jpradocueva/public-openAIS
