### ISSUE TITLE
Information about LwM2M Object EventLog

### ISSUE THREAD

**Issue by MarcelMak** [OpenMobileAlliance/OMA_LwM2M_for_Developers#354]
Hi guys,

there is a LwM2M Object EventLog with Object Id 20 on the OMA LightweightM2M (LwM2M) Object and Resource Registry, but unfortunately there is no information about this object. Does anybody has any clue about the specification for this object?

Best Regards,
Marcel

**Comment by jpradocueva** [comment]
The Event Log Enabler (which contains Object and Technical specifications) is still in Candidate state.
Until the group doesn't send the Enabler package for final approval, the Object will not be available in the OMNA registry (it may change from Candidate to Approved).

In any case the documents are available via standard OMA publication in this page: http://openmobilealliance.org/wp/index.html 
and in this link: http://openmobilealliance.org/release/LwM2M_EventLog/

**Comment by MarcelMak** [comment]
Thank you for your quick and really helpful answers. Even if the specification (for the candidate) will slightly change, it is almost clear how to use it.
