### ISSUE TITLE
Write-partial clarification

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#355]
Hi,
clarification related to Write-partial is appreciated
* OMA-TS-LightweightM2M-V1_0_2-20180209-A 
* section: 5.4.3 Write 

the write operation can be sent through PUT (write->replace) or POST (write->partial update) (section 8.2.5).

I have some doubs regarding write-partial cases:
**a)** **single resources**: write-partial 1/1 [data: defMaxPeriod=100, disable-timeout=200]: this command updates only these 2 resources and leave other resources unchanged;
case a is quite clear

**b)** multiple-instance resources: let assume I have 2 instances of ACL resource: 2/3/2 [0="10",1="11"];
I want to **update only multiple-instance 1** of ACL resource:
write-partial 2/3/2 [data: 1="111"]: this command updates only 1 resource and leave other resources unchanged;
case b could be quite clear: anyway, could you confirm?

**c)** starting from case b), I want to update instance 1 of ACL and **add a new multiple-instance**:
write-partial 2/3/2 [data: 1="1111",2="22"]: this command updates 1 resource, add a new resource and leave other resources unchanged;
case b could be quite clear: anyway, could you confirm?

**d)** the specification reports this sentence:
_When the Resource is a Multiple-Instance Resource, the existing array of Resource Instances is updated meaning some Instances **may be created or deleted** under the condition that the LwM2M Client authorizes such operations._ 

Since the creation seems covered by case c,
**how can be possible deletion of an instance into ACL resource?**
or when the resource is multiple-instance it's a special case so does the write-partial have the same behaviour of the replace (PUT)? then are cases c and d unfeasible?

please provide also some examples.
thanks
Giuseppe Melis

**Comment by hannestschofenig** [comment]
We clarified this issue in the bugfix release of v1.1 (=v1.1.1)
