### ISSUE TITLE
UQS mode on LwM2M and PSM

### ISSUE THREAD

**Issue by jwbjwbjwb** [OpenMobileAlliance/OMA_LwM2M_for_Developers#356]
AT&T spec in below link requires that device support UQS mode ( UDP with Queue Mode and SMS ) on LwM2M :
https://iotdevices.att.com/Uploaded_Docs/device_management_implementation_guide_3_20180323085341296.pdf

Does it mean that device will not support PSM (Power Saving Mode)?
I am unable to see if this is addressed in "OMA-TS-LightweightM2M-V1_0_2-20180209-A".
Would you please help to clarify ?

**Comment by ytava** [comment]
Hi,

AT&T general DM requirement for modem is to support UQS (SMS as a trigger).
Still, depending on the specific application and device type, device can work in PSM. 
Those two aspects are mostly independent, but as understood while working in PSM (unlike ERDX) the device is not reachable from the NW side during T3412.

Generally, devices that are required to be pagable from the NW (for any type of MT - SMS or data) are not suitable for PSM, but AT&T DM requirement doesn't block you from using PSM. 

For devices that work in PSM, carrier may use registration lifetime which is shorter than 3GPP T3412 (would impact power consumption) or somehow synchronize the trigger SMS to when the device is connected or sending TAU.
