### ISSUE TITLE
SMNC resource would be better if string format (otherwise new resource with len of MNC)

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#360]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A
* E.5 LwM2M Object: Connectivity Monitoring

SMNC (resource 9)
Integer 
Serving Mobile Network Code. In case Network Bearer Resource has 0(cellular network). Range (0…999). As specified in TS [3GPP_TS_23.003]. 

Since the **mobile network code** consists of **two or three decimal digits** (for example: MNC of 001 is not the same as MNC of 01), the integer value 1 could be misunderstood as 01 or 001, so I think **integer format is not the best way** to represent this resource.

if it were a **string value**, the string "01" would be different from the string "001".

Otherwise, **keeping the SMNC as integer, a new resource could be add** into this object containing the **length of MNC**, using the same way of 3GPP specifications:
3GPP TS 11.11 V8.14.0 (2007-06)
3GPP TS 31.102 V14.1.0 (2017-01)

EFad field contains this byte:
Length of MNC in the IMSI:
The length indicator refers to the number of digits (2 or 3), used for extracting the MNC from the IMSI 

With this new resource, if the integer value of SMNC is:
a) 1, and
-- a1) the len of MNC is 2, the SMNC has to be considered as "01"
-- a2) the len of MNC is 3, the SMNC has to be considered as "001"

b) 11, and
-- b1) the len of MNC is 2, the SMNC has to be considered as "11"
-- b2) the len of MNC is 3, the SMNC has to be considered as "011"

c) 111, and
-- c1) the len of MNC is 2,                sould the SMNC be truncated to "11"?
-- c2) the len of MNC is 3, the SMNC has to be considered as "111"

**Comment by dnav** [comment]
Hi,

You wrote:
> for example: MNC of 001 is not the same as MNC of 01

But the 3GPP TS 23.003 V15.5.0 (2018-09) states on page 41 that:
> In order to guarantee inter-PLMN DNS translation, the \<MNC\> and \<MCC\> coding used in the "mnc<MNC>.mcc<MCC>.gprs" format of the APN OI shall be:
> -	\<MNC\> = 3 digits
> -	\<MCC\> = 3 digits
> -	If there are only 2 significant digits in the MNC, one "0" digit is inserted at the left side to fill the 3 digits coding of MNC in the APN OI.
> As an example, the APN OI for MCC 345 and MNC 12 will be coded in the DNS as "mnc012.mcc345.gprs".

Thus I would think that an MNC of `01` is encoded as `001` making them the same.

I'm not an expert on 3GPP so I may be missing something.

Regards,

**Comment by giuseppe-melis** [comment]
Hi David,
maybe it's not a big issue.
Anyway, a cellular device uses mcc-mnc from EFimsi to identify home/roaming cells, so it should always know if mnc is 2 or 3 digits long.
Thanks
Giuseppe

**Comment by hannestschofenig** [comment]
No changes are required to the spec, see comment by David. The spec is written to follow the 3GPP specification.
