### ISSUE TITLE
4.03 response code description is inconsitent with register behavior specification

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#37]
At §8.5, for register request, the specification say : 
_4.03 Forbidden The Endpoint Client Name results in a duplicate
entry on the LWM2M Server._

and at §5.2.1 :
_If the LWM2M Client sends a “Register” operation to the LWM2M Server even though the LWM2M Server  as registration information of the LWM2M Client, the LWM2M Server removes the existing registration  information and performs the new “Register” operation. This situation happens when the LWM2M Client forgets the state of the LWM2M Server (e.g., factory reset)_

I think the 4.03 response code description should be used instead when a client is not allowed to register on a server. (a typical use case)

**Comment by ThGarnier** [comment]
fixed in TS 1.0 of April 2016 Release:

**Comment by Megan-OMA** [comment]
Closed 14-April-2016 per Thierry's comment above.
