### ISSUE TITLE
Support sms binding

### ISSUE THREAD

**Issue by LJenny** [OpenMobileAlliance/OMA_LwM2M_for_Developers#371]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS-LightweightM2M_Transport-V1_1-20180612-C
* Section of the document, ``(e.g. section: 6.2)``: 4
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

Is there an open source that supports sms binding?
And if there is only "S" binding, is it necessary to handle operations such as register, create, and read through sms?

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

**Comment by hannestschofenig** [comment]
In v1.1 we have clarified the use of the SMS binding. 
To my knowledge there is no open source code available.

**Comment by hannestschofenig** [comment]
There is no way to only have "S" binding.
