### ISSUE TITLE
ETS test LightweightM2M-1.0-int-777 has wrong expected state result

### ISSUE THREAD

**Issue by dnav** [OpenMobileAlliance/OMA_LwM2M_for_Developers#374]
OMA-ETS-LightweightM2M-V1_0_2-20180608-D

Test case LightweightM2M-1.0-int-777: Error Case 6: unsupported package type

Test case states that the expected result of step 4 is having the State Resource set to value 1 (Downloading). It should be 0 (Idle).

**Comment by jpradocueva** [comment]
This issue will be revised in the next ETS.
