### ISSUE TITLE
ETS test LightweightM2M-1.0-int-774 has wrong expected update result

### ISSUE THREAD

**Issue by dnav** [OpenMobileAlliance/OMA_LwM2M_for_Developers#375]
OMA-ETS-LightweightM2M-V1_0_2-20180608-D

Test case LightweightM2M-1.0-int-774: error Case 3: out of memory

Test case states that the expected result of step 4 is having the Update Result Resource set to value 2 (out of storage). It should be 3 (out of memory).

**Comment by jpradocueva** [comment]
This will be fixed in the next version of the ETS.
