### ISSUE TITLE
LightweightM2M-1.0-int-303 – Cancel observations using Observe with Cancel : Weird Test case procedure.  

### ISSUE THREAD

**Issue by jaeeunchoi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#376]
In the 'OMA-ETS-LightweightM2M-V1_0_2-20180608-D'

The pass criteria B. of 'LightweightM2M-1.0-int-303 – Cancel observations using Observe with Cancel parameter' says :

'B. The Server stops receiving information on “Power Source Voltage” and “Power Source Current” after having sent the Cancel Observation (with Cancel parameter) on the Device Object Instance (/3/0).Associated entries from the list of observers are removed.'

But there's no clear description on this in the TS (OMA-TS-LightweightM2M-V1_0_2-20180209-A)
And it looks conflicting with the underlying CoAP specification.( rfc7641 'Observing Resources in the Constrained Application Protocol (CoAP)')
It says : 'If the Observe Option in a GET request is set to 1 (deregister), then
the server MUST remove any existing entry with a matching endpoint/
token pair from the list of observers and process the GET request as
usual. The resulting response MUST NOT include an Observe Option.' in 4.2 Request chapter.

I think the more clear description is need on TS and ETS about this test case.

**Comment by jpradocueva** [comment]
DMSE will further investigate
