### ISSUE TITLE
register post from client

### ISSUE THREAD

**Issue by ting222** [OpenMobileAlliance/OMA_LwM2M_for_Developers#377]
When submitting an issue please indicate the following information:
* Name, version and date of the document, :OMA-TS-LightweightM2M-V1_0_2-20180209-A
* Section of the document,`:5.3.1 Register
* Sequence of exchanges between Client and Server `: Register
client post the register like the following,

ep=GTO_test&lt=30&sms=null&lwm2m=1.0&b=U 
but sms is an optional message, is it acceptable for server  with such register?

**Comment by jpradocueva** [comment]
This is not an acceptable message to the server. The sms=MSISDN, it cannot be null.
* sms is an optional parameter, it doesn't need to be included. 

DMSE, will further discuss this topic.

**Comment by hannestschofenig** [comment]
Joaquin correctly responded to this issue already.
