### ISSUE TITLE
Excessive TLV data for READ request

### ISSUE THREAD

**Issue by sikor** [OpenMobileAlliance/OMA_LwM2M_for_Developers#378]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A
* section: 6.4.3 TLV
* communication: 
  Server ---- GET /1/0 -----> Client
  Client ------ Content Response: TLV [Object instance 0][Resources 1, Resource 2, ....] ----> Server

In example above, client sends unnecessary information about object instance. The object instance number is obvious because it is given in READ path.

Currently, specification contains example TLV responses for given request paths but it does not specify MUST/MUST NOT requirements. So for example client is allowed to send all instances of given object when read is performed for only one resource, for example: /1/0/0

I think that specification should clearly say that it is possible by client to send excessive TLV data in response. Then, server-side libraries implementors will known that they have to handle that case.

**Comment by jpradocueva** [comment]
DMSE recommends to move to CBOR.

DMSE should consider to address this problem for v1.0 implementations.

**Comment by sbernard31** [comment]
About needs of TLV clarification : #276

About cleaning TLV, fixing examples (or ensure there is no errors) could be a good idea too : #281

**Comment by hannestschofenig** [comment]
When a read is performed for only one resource, for example: /1/0/0, then it will only get that resource and not all instances of the object. 

This example shows the appropriate behavior: 
* Server ---- GET /1/0 -----> Client
  Client ------ Content Response: TLV [Object instance 0][Resources 1, Resource 2, ....] ----> Server

Where do you see the problem?
