### ISSUE TITLE
LightweightM2M-1.0-int-0 – Client Initiated Bootstrap'  : verifying the client setup using BOOTSTRAP-DISCOVER

### ISSUE THREAD

**Issue by jaeeunchoi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#379]
In the 'OMA-ETS-LightweightM2M-V1_0_2-20180608-D'
The step 3 and pass criteria D. of 'LightweightM2M-1.0-int-0 – Client Initiated Bootstrap' says :
'3. The Bootstrap Server performs a BOOTSTRAP-DISCOVER operation (CoAP GET Accept:40 / ) to verify the Client setup'
'D. In test step 3., the Bootstrap Server received the Success message (“2.05” Content) along with the payload related to the BOOTSTRAP-DISCOVER request and containing :
lwm2m="1.0",</0/0>;ssid=1,</0/1>, </1/0>;ssid=1,</3/0>'

=> Then, what is a proper behavior of the server when it detect something wrong in the BOOTSTRAP-DISCOVER response. (e.g. some object instances are not created..)

**Comment by jpradocueva** [comment]
The specification doesn't dictate what to do in this case.
