### ISSUE TITLE
OMNA-Registration of Soil Moisture

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#384]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-07-12 06:38:17 UTC</td></tr><tr><td>Submitter's name</td><td>Prachin</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Soil Moisture</td></tr><tr><td>Object Description</td><td>This object should be used over a soil moisture sensor to report a remote soil moisture measurement.</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=0cb48e41-f7c3-4dbd-990d-17ce5f091367_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=0cb48e41-f7c3-4dbd-990d-17ce5f091367_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration appears to be the same as Issue #385
