### ISSUE TITLE
LightweightM2M-1.0-int-0 – Client Initiated Bootstrap, Is that okay if we use modified configuration 13(without PSK mode) in bootstrap test?

### ISSUE THREAD

**Issue by joosaeng** [OpenMobileAlliance/OMA_LwM2M_for_Developers#387]
Our intern( heartrecycle95 at gmail.com ) asked this question to me.

* OMA-ETS-LightweightM2M-V1_0_2-20180608-D

* Bootstrap Interface: [0-99] / LightweightM2M-1.0-int-0 – Client Initiated Bootstrap

* Our intern asked me "The client has to support configuration C.13 which contain PSK set-up part. but I wonder why this test has to use PSK because Pass-Criteria has nothing about PKS?"

Is that okay if we use modified configuration 13(without PSK mode) in bootstrap test?

**Comment by hannestschofenig** [comment]
In this test case we want to determine whether a LwM2M Client is able to connect to the LwM2M Bootstrap-Server using the Bootstrap interface when using the PSK credential. If you use some other credential, such as X.509 certificates, then you miss the point of this use case.

We could definitely clarify this issue in the test case description.
