### ISSUE TITLE
Bootstrap Server Account purge

### ISSUE THREAD

**Issue by dnav** [OpenMobileAlliance/OMA_LwM2M_for_Developers#39]
The Technical Specification in chapters 5.2.2.3 Client Initiated Bootstrap and 5.2.2.4 Server Initiated Bootstrap states:

> The LWM2M Server SHOULD purge the LWM2M Bootstrap Server Account after successful bootstrapping. 

But the Bootstrap Server Account is stored in the LWM2M Security which is not accessible to any LWM2M Server.

Moreover the same chapters write:

> the LWM2M Client MUST purge the LWM2M Bootstrap Server Account after the timeout value Bootstrap Server Account Timeout, if defined, or immediately after successful bootstrapping if the timeout value is not defined.

Thus the whole unbootstrapping procedure described in chapter E.1.3 seems unreachable since there will never be a bootstrap server to remove a LWM2M server the client is registered to.
It is also impossible to add new LWM2M servers to LWM2M clients during their lifetime without factory-resetting them.

**Comment by jvermillard** [comment]
I also wonder how you change credentials? For example X.509 certificates have an expiration date.

**Comment by jvermillard** [comment]
This CR is referencing this issue
http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2015/OMA-DM-LightweightM2M-2015-0018-CR_Bootstrap_Server_Account.zip

**Comment by ThGarnier** [comment]
Yes I agree, there are discussions in OMA DM at that time on that point  :-)   !!

**Comment by dnav** [comment]
Addressed in the current TS.
