### ISSUE TITLE
Update registration on observe notification

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#391]
About OMA-TS-LightweightM2M-V1_0_2-20180209-A.

I am a Leshan committer. (Open source java implementation of LWM2M)

And recently a user asks us how he can update registration on notification. He would like to update address/port of the registration linked to the notification.

I know there was long discussion about it long time ago : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/115.

I re-read this issue, I re-read the last version of the spec and I'm still confused about that...

Currently, in Leshan we just update registration on `registration update`. Should/could we also do that on notification ?

**Comment by hannestschofenig** [comment]
With LwM2M v1.0 and v1.1 we update registration on `registration update`. We are not providing functionality for registration update based on the notification message.

**Comment by sbernard31** [comment]
Thx for the clarification :)
