### ISSUE TITLE
Firmware Update State Machine error

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#393]
In OMA-TS-LightweightM2M-V1_0_2-20180209-A, figure 29 § E.6.1 Firmware Update State Machine, I think there are issues.

![figure 29](https://user-images.githubusercontent.com/840294/43320658-7887b05c-91a9-11e8-9586-b6834b5dc65a.png)

**1)  In UPDATING state, a `Firmware update Failed [Res==8]` event bring to both states IDLE and DOWNLOADED.**

The description of resource 3 from Firmware Update object 5 says : 
_"When in Downloaded state, and the executable Resource Update is triggered,
the state changes to Updating.
If the Update Resource failed, the state returns at Downloaded."_

**2) I suspect that the Integrety Check Failed [Res ==5] event from UPDATING to IDLE is a mistake too.**

`Integrity Check Failed` is more about downloading firmware than updating .

**Comment by sbernard31** [comment]
Your personal view could make sense, but having a state machine with 1 state which could go to 2 several states with the same event seems really counterintuitive to me. Even more when the spec does not explain the idea behind this.

**Comment by hannestschofenig** [comment]
It appears that there should be a clarification in the state machine description and we will update the firmware update functionality in LwM2M v1.2. We could incorporate this issue into the bugfix release of v1.1 as well, if needed.

**Comment by hannestschofenig** [comment]
LwM2M v1.2 contains clarifications in resource #3 to indicate that there may be multiple reasons for an error.  Regarding the transition from Downloadingto Idle on Integrity Check Failed: it depends a bit on when the signature of the downloaded image is verified in the implementation. For some bootloaders, like Mcuboot, the signature verification happens when the update is to be performed rather than when the image is downloaded. I could imagine that there are other implementations doing the check twice.

**Comment by sbernard31** [comment]
> Regarding the transition from Downloading to Idle on Integrity Check Failed: it depends a bit on when the signature of the downloaded image is verified in the implementation. For some bootloaders, like Mcuboot, the signature verification happens when the update is to be performed rather than when the image is downloaded. I could imagine that there are other implementations doing the check twice.

Thx for clarify this.
So I was wrong about : **2) I suspect that the Integrety Check Failed [Res ==5] event from UPDATING to IDLE is a mistake too.**

-----------------------------
About **1) In UPDATING state, a Firmware update Failed [Res==8] event bring to both states IDLE and DOWNLOADED.**

The specification v1.2 clarify this : 

> If the Update Resource failed, the state may return to either Downloaded or Idle depending on the underlying reason of update failure, e.g. Integrity Check Failure results in the client moving to the Idle state.

So I think we are good.

@hannestschofenig, when I think I get my answers should I close the issue or should I let you do it ?

**Comment by hannestschofenig** [comment]
I can close the issue. Thanks for your quick response.
