### ISSUE TITLE
Python LWM2M client libraries

### ISSUE THREAD

**Issue by valensd-etc** [OpenMobileAlliance/OMA_LwM2M_for_Developers#394]
This is a help wanted issue.

I am a developer trying to get an LWM2M client running on a Beaglebone Black. I am most comfortable in Python programming so I was looking for a Python LWM2M client library to start my application development. Unfortunately there is only 1 project on git hub and it has gone dormant. I could try and use a wakaama client and cmake but I'm curious what the development community for LwM2M suggests. I know there is the aiocoap library and the coapthon library if I wanted to start my own client from scratch.

I understand LwM2M was designed for resource limited devices so C implementations make sense.

Thanks in advance!

**Comment by valensd-etc** [comment]
@Alex-EEE No I didn't get any traction on this. I think I'll try using a Python wrapper for a c library at some point.

**Comment by hannestschofenig** [comment]
A Google search pointed me to this LwM2M client written in Python: https://github.com/aellwein/lwm2mclient

Have you had a chance to look at it?
