### ISSUE TITLE
OMNA-Registration of Time Synchronisation Event

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#395]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-08-06 06:59:44 UTC</td></tr><tr><td>Submitter's name</td><td>Hodorware</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Latest Payload</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Time Synchronisation Event</td></tr><tr><td>Object Description</td><td>time sync</td></tr><tr><td>Link to object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=ce710bf7-af24-4762-b0f8-e4f822ee7a9a_Object.xml">Download Object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=ce710bf7-af24-4762-b0f8-e4f822ee7a9a_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This Object is already registered in OMNA: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
