### ISSUE TITLE
OMNA-Registration of LwM2M Server

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#402]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-08-09 20:28:01 UTC</td></tr><tr><td>Submitter's name</td><td>Joaquin Prado</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LwM2M Server</td></tr><tr><td>Object Description</td><td>Test Please ignore</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=da889687-37cc-4eb3-8a1d-606cf350ec91_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/da889687-37cc-4eb3-8a1d-606cf350ec91_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=da889687-37cc-4eb3-8a1d-606cf350ec91_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Test to see the new link to the object.
