### ISSUE TITLE
FOTA test case "Error Case 7: invalid URI": need clarification

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#404]
* OMA-ETS-LightweightM2M-V1_0_2-20180815-A:
* Section 6.1.6.6.13 LightweightM2M-1.0-int-778 – Error Case 7: invalid URI (package URI) :

this test is designed to catch a negative case when the package URI is invalid.
my client development is able to detect syntax mistakes into the URI string during IDLE state, so I don't need to go to DOWNLOADING state at step C and then go back to IDLE state at step E, as required by the test (we change only last 5/0/5 update result resource according to the test):
**what do you think about?**

Anyway, please assume that I modify my code to move the syntax mistake detection into DOWNLOADING state: in this case the detection will be so fast that I go back to IDLE state in a very short time, so I probably will not be able to send a notify related to DOWNLOADING state because pmin (or def min period) will not be reached yet; maybe the notify will never been sent because there is no transition between IDLE-(DOWNLOADING too fast)-IDLE states.

Just to try to match the test results, I could **force a notify for the DOWNLOADING state as soon as the syntax mistake is detected** and then a new one for the IDLE state.
In this case we will send 2 notifies before pmin is reached --> out of spec
**what do you think about?
should the test results be modified?**

**Comment by hannestschofenig** [comment]
Solved for v1.1 test spec but not for v1.0
