### ISSUE TITLE
OMNA-Registration of LWM2M Meta Object

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#405]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-09-05 14:55:57 UTC</td></tr><tr><td>Submitter's name</td><td>Bill Silverajan</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Tampere University of Technology</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LWM2M Meta Object</td></tr><tr><td>Object Description</td><td>A meta object to provide one or more locations for data model XML definitions for vendor-specific devices.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=055e1685-7df3-4811-ac0d-52385f4a831e_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/055e1685-7df3-4811-ac0d-52385f4a831e_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=055e1685-7df3-4811-ac0d-52385f4a831e_Object.xml">Load Editor with object</a></td></tr>

**Comment by bsilverajan** [comment]
Thanks so much for your help. I've now resubmitted the registration and it has been assigned to issue #406 

I'd be ok with closing this issue related to the original registration.

**Comment by jpradocueva** [comment]
New registration issue in #406
