### ISSUE TITLE
OMNA-Registration of esmContextInfo

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#408]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-09-07 09:47:35 UTC</td></tr><tr><td>Submitter's name</td><td>fn fn</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>DAOLAI Intelligent technology co. LTD</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>esmContextInfo</td></tr><tr><td>Object Description</td><td>App data transmission</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=2b2c1bfb-86ac-46ef-884a-968ec5d07ce2_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/2b2c1bfb-86ac-46ef-884a-968ec5d07ce2_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=2b2c1bfb-86ac-46ef-884a-968ec5d07ce2_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration request doesn't appear to be legit.
