### ISSUE TITLE
OMNA-Registration of VolteCallEvent

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#409]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-09-12 08:19:57 UTC</td></tr><tr><td>Submitter's name</td><td>xxsaxsa</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>VolteCallEvent</td></tr><tr><td>Object Description</td><td>xsax@dwd.bg</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=35325e75-552d-4bf4-be22-c19444788acb_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/35325e75-552d-4bf4-be22-c19444788acb_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=35325e75-552d-4bf4-be22-c19444788acb_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
This Registration is has been submitted as a duplication of 3381
