### ISSUE TITLE
OMNA-Registration of HexData

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#411]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-09-25 02:45:27 UTC</td></tr><tr><td>Submitter's name</td><td>王灵艳</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>深圳拓邦股份有限公司</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>HexData</td></tr><tr><td>Object Description</td><td>Data transmission</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=09fcb1c0-23e4-4975-9842-5a259359580d_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/09fcb1c0-23e4-4975-9842-5a259359580d_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=09fcb1c0-23e4-4975-9842-5a259359580d_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration has an incorrect Legal disclaimer. The OMA legal disclaimer it is only used by OMA members and groups.
Please resubmit your registration under a different legal disclaimer.

**Comment by mojanm** [comment]
Couple of comments:
1) Object specific resource IDs normally start with 0 rather than 1 as proposed for HexData object
2) Opaque data type is normally used to represent sequence of binary octets which Data, resource ID 2, in the object seems to represent; see Appendix C of LwM2M v1.1 core spec.

**Comment by seanmcilroy29** [comment]
王灵艳 - Please review the submitted observations.
Submission will be closed 28 Feb

To aid in further Object submissions via the [Editor tool ](http://devtoolkit.openmobilealliance.org/OEditor/Default) please see our [support guidelines](https://wiki.openmobilealliance.org/display/TOOL/Introduction+to+LightweightM2M)
