### ISSUE TITLE
Android LWM2M client 

### ISSUE THREAD

**Issue by Yalayak** [OpenMobileAlliance/OMA_LwM2M_for_Developers#412]
Hello everyone,

I'm looking for the possibility of deploying a lwM2M client on an android board. Apparently Leshan doesn't work well with android are there any other alternatives?

**Comment by sbernard31** [comment]
You can also report issues to Leshan Team and helps to make it works on android :
https://github.com/eclipse/leshan/issues/new

**Comment by bzero** [comment]
@dnav download that app, it does not provide DTLS only COAP protocol.
