### ISSUE TITLE
OMNA-Registration of App Fota Container

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#413]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-10-09 15:48:11 UTC</td></tr><tr><td>Submitter's name</td><td>beixu</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>App Fota Container</td></tr><tr><td>Object Description</td><td>xxxxxx</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=f49e4d7b-c4db-4664-8f25-e32f11b7f32a_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/f49e4d7b-c4db-4664-8f25-e32f11b7f32a_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=f49e4d7b-c4db-4664-8f25-e32f11b7f32a_Object.xml">Load Editor with object</a></td></tr>

**Comment by Echo-xubei** [comment]
Just a test. Could you help to delete this issue?
