### ISSUE TITLE
can we use this for dash board purpose

### ISSUE THREAD

**Issue by anuscool** [OpenMobileAlliance/OMA_LwM2M_for_Developers#414]
i have two sensor which are connected to leshan server,i want to access leshan server data(device data) using Rest API,can we do this

**Comment by sbernard31** [comment]
@anuscool, your question is about Leshan and you already asked it at the right place : https://github.com/eclipse/leshan/issues/581

I tried to answer you but my response doesn't seems to satisfy you, too bad... 

Anyway, this repository is about LWM2M specification and so your question is totally out of topic here...
