### ISSUE TITLE
OMNA-Registration of Event Log

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#415]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-10-13 07:45:58 UTC</td></tr><tr><td>Submitter's name</td><td>zaqiot</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>zaqiot</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Event Log</td></tr><tr><td>Object Description</td><td>SD51NB is a NB-IoT based smoke detector</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=d1635a40-ff21-463a-8728-e03fac3d2c38_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/d1635a40-ff21-463a-8728-e03fac3d2c38_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=d1635a40-ff21-463a-8728-e03fac3d2c38_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Private companies are not allowed to register Objects in this range. The range (0 - 1023) is dedicated to Objects produced by OMA Working Groups. 
Currently there is a Work Item to develop an EventLog Object inside of OMA.
We are closing this Issue as it is not possible to complete the registration.
