### ISSUE TITLE
FOTA, package URI and interoperability

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA_LwM2M_for_Developers#417]
Specification: OMA-TS-LightweightM2M_Core-V1_1-20180710-A
Section: E.6: LwM2M Object: Firmware Update

I've one question regarding package URI for interoperability.
The resource can be written and read by a LwM2M server.
According to the client implementation, this package URI could be erased at package download end for example, whatever the download result (and the download result can be retrieved by /5/0/3 resource value).
According to the server implementation, a server can request to read the package URI after or/and before sending the install request (EXEC /5/0/2) just to be sure that the downloaded package is the correct one.
What is the recommendation on package URI storage for interoperability ?

**Comment by hannestschofenig** [comment]
Where did you got the description of what the client and the server implementations do with regard to the package URIs?

**Comment by fdur** [comment]
I didn't find any description on the package URI management.
But for interoperability and according to client/server implementation, it could be nice to indicate how the package URI needs to be managed on client side in an alternative mechanism.
Can the package URI could be deleted on device side before receiving the install request ?
A server could request to be able to read the update status and result and then the package URI before sending the install request.
If a client deletes the package URI on download end and if the server requests it in order to send the install request, this could lead to an issue ...

**Comment by hannestschofenig** [comment]
We consider this aspect implementation dependent.
