### ISSUE TITLE
OMNA-Registration of Voltage Logging

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#418]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-10-24 05:46:59 UTC</td></tr><tr><td>Submitter's name</td><td>Andrew Forster-Knight</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>South East Water  Corporation</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Voltage Logging</td></tr><tr><td>Object Description</td><td>Object for logging and recording voltages from any voltage source (for example cathodic test points)</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=7f541076-b6bb-4c30-a2e5-3b78a7143728_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/7f541076-b6bb-4c30-a2e5-3b78a7143728_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=7f541076-b6bb-4c30-a2e5-3b78a7143728_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Object updated to remove empty spaces between tags and Object version added.
Object resubmitted - https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/435
