### ISSUE TITLE
Size of public key‘s in „Raw-Public Key mode“

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#42]
The TS 20150228 mentions in E1.1.2
„Thus the Certificate Resource would contain a 32 byte public key and the Secret Key Resource a 32 byte private key.“
But ECC uses two public keys (“x” and “y”) each of 32 bytes. 
Should public key x and public key y be stored concatenated (xy, 64 bytes) in the "public keys" resources?

**Comment by BillBennett** [comment]
Also, doesn't the size vary with different curves? CoAP specifies "curve secp256r1 MUST be supported" - does that mean that keys for other curves MUST NOT be used? Is that risky?

**Comment by BillBennett** [comment]
Also also, I think the PSK is variable-length because it gets hashed. That means "The default PSK Cipher Suites defined in this specification use a 128-bit AES key. Thus this key would be represented in 16 bytes in the Secret Key Resource." is also misleading.

**Comment by boaks** [comment]
There is already an open issue on the PSK length.

See https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/4

**Comment by BillBennett** [comment]
Whoops. Thanks!

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20160407-C, E.1.1.2

Still defines 32 bytes!

**Comment by hannestschofenig** [comment]
Resolution for the incorrect length indication is to delete the following sentence from Appendix  E1.1.2: 

„Thus the Certificate Resource would contain a 32 byte public key and the Secret Key Resource a 32 byte private key.“

Reason for change: The statement is incorrect, as also pointed out in issue#48:https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/48

Affected version: LWM2M v1.0

**Comment by ThGarnier** [comment]
solved in TS 1.0 Sept 2016 release

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
