### ISSUE TITLE
LWM2M client agent observations scenario 

### ISSUE THREAD

**Issue by arilwan** [OpenMobileAlliance/OMA_LwM2M_for_Developers#421]
Hi Everyone, 

I want a complete scenario (or maybe tutorial).  That clearly explains how an LWM2M client send that to agent. Here's the scenario I have :

I have a FIWARE architecture in which I want a  lwm2mclient to send update to IDAS (the LWM2M agent)  from a backoffice data source (I have this already).  I am not sure if I curl can be used for that. I am using wakaama implementation of the CoAP. 

Any idea please.

**Comment by hannestschofenig** [comment]
Please have a look at my recently released tutorial: 
https://community.arm.com/arm-research/b/articles/posts/10-things-you-should-know-about-lwm2m

Does this help?
