### ISSUE TITLE
[Resource Registration]OMNA-Registration of Reusable resources

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#426]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-02 08:05:41 UTC</td></tr><tr><td>Submitter's name</td><td>Andrew Foster-Knight</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>South East Water Corporation</td></tr><tr><td>Type of registration</td><td>Reusable resources</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=1acd9c2c-3077-48b3-b2bb-7df2ebffa307_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/1acd9c2c-3077-48b3-b2bb-7df2ebffa307_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1acd9c2c-3077-48b3-b2bb-7df2ebffa307_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Approved - https://github.com/OpenMobileAlliance/ipso-wg/pull/156
