### ISSUE TITLE
OMNA-Registration of Daughter Board Failure Alarm

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#427]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-06 12:06:00 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Test Migration</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Daughter Board Failure Alarm</td></tr><tr><td>Object Description</td><td>Test Migration</td></tr><tr><td>Download Object</td><td><a href="http://azuredevtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=32394f76-beab-4845-92a6-7e2ce389aa7a_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://azuredevtoolkit.openmobilealliance.org/OEditor/OMNA/32394f76-beab-4845-92a6-7e2ce389aa7a_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://azuredevtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=32394f76-beab-4845-92a6-7e2ce389aa7a_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Testing migration of tools
