### ISSUE TITLE
Error code in Device object

### ISSUE THREAD

**Issue by ky0on** [OpenMobileAlliance/OMA_LwM2M_for_Developers#428]
I found that only 8 error codes are available and their meanings are fixed in Device object (OMA-TS-LightweightM2M_Core-V1_1-20180710-A, Appendix E.4).

How could I store error codes other than the 8 error codes?

**Comment by hannestschofenig** [comment]
This means that currently only 8 error codes are defined. It is possible to extend the error codes. What error codes would you like to define? You can submit a request for a new object version via this editor: 
http://devtoolkit.openmobilealliance.org/OEditor/Legal?back=default.aspx

**Comment by hannestschofenig** [comment]
If you want to extend the list of error codes please send us your new error codes + description then we will update the object specification. 

If you want to use vendor-specific error codes then you can create a new object to convey these error codes.
