### ISSUE TITLE
 Inconsistency in Standard LwM2M Object – ConnMgmt

### ISSUE THREAD

**Issue by emmelmann-fokus** [OpenMobileAlliance/OMA_LwM2M_for_Developers#43]
The standard "Lightweight M2M – Connectivity Management Object (LwM2M Object – ConnMgmt), Candidate Version 1.0 – 13 Jan 2015, contains inconsistencies

Inconsistencies

==> LWM2M Object: WLAN connectivity
- Resource definition ID 2 (Radio Enabled) allows only to specify that the system operates in the 2.4GHz or 5GHz bands.
- Resource definition ID 14 (Standard) specifies values for IEEE 802.11ah which operates in sub-1GHz bands.
- As both recource definitions are mandatroy, this causes a conflict for all 802.11 modes that operate outside the 2.4GHz or 5GHz band.  It is impossible to have always a valid setting for the "Radio Enabled" and "Standard" resource definitions, e.g. for 802.11ah (Standard resource
  definition) it is impossible to specify sub-1G band in the Radio Enabled resource definition.

**Comment by boaks** [comment]
According "TS 20151030-C, appendix D.1

"Mandatory: if this field is “Mandatory”, then the LWM2M Server and the LWM2M Client MUST support Resource. If this field is “Optional”, then the LWM2M Server and the LWM2M Client SHOULD support the Resource."

I'm not sure about the exact meaning of "support". 
This may mean: 
- must be implemented but no actual value is required 
or 
- must be implemented and actual value is required 

So the TS should clarify the meaning. 

(This may also help for https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/77)

**Comment by Megan-OMA** [comment]
@ThGarnier will you please provide a final comment on why this issue is to be closed before we close it

**Comment by hannestschofenig** [comment]
The approved version of the connectivity object no longer has any of the mentioned issues.
