### ISSUE TITLE
OMNA-Registration of WiFi Scan

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#430]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-12 20:13:34 UTC</td></tr><tr><td>Submitter's name</td><td>Joe Baird</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>T-Mobile</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>WiFi Scan</td></tr><tr><td>Object Description</td><td>WiFi scan results to be used either for WiFi provisioning or crowd-sourced location</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8ce231ea-5bb8-4c2c-ac73-263912674828_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/8ce231ea-5bb8-4c2c-ac73-263912674828_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8ce231ea-5bb8-4c2c-ac73-263912674828_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
The registration of this Object has been moved to the new OMNA lwm2m-registry in: https://github.com/OpenMobileAlliance/lwm2m-registry/issues/16
