### ISSUE TITLE
OMNA-Registration of Bitmap

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#431]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-15 07:00:20 UTC</td></tr><tr><td>Submitter's name</td><td>Transmission</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>yftech</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Bitmap</td></tr><tr><td>Object Description</td><td>only for transmission,no need data analyse</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=2a60611a-9398-4931-8f35-60e6ee8bd450_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/2a60611a-9398-4931-8f35-60e6ee8bd450_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=2a60611a-9398-4931-8f35-60e6ee8bd450_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is a duplication of an Object that already exist.
