### ISSUE TITLE
OMNA-Registration of Pressure Transient

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#434]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-15 14:14:23 UTC</td></tr><tr><td>Submitter's name</td><td>Andrew Foster-Knight</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>South East Water Corporation</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Pressure Transient</td></tr><tr><td>Object Description</td><td>Object for measuring and summarizing high frequency pressure readings</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=888a5636-4453-4c1c-9571-14da0038bfd4_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/888a5636-4453-4c1c-9571-14da0038bfd4_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=888a5636-4453-4c1c-9571-14da0038bfd4_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Following values required to be added >
MultipleInstances value
Mandatory value

**Comment by aforster23** [comment]
please add the following                                                                                              <MultipleInstances>Single</MultipleInstances>
<Mandatory>Mandatory</Mandatory> 

Thanks

**Comment by aforster23** [comment]
please add the following                                                                                              <MultipleInstances>Single</MultipleInstances>
<Mandatory>Mandatory</Mandatory> 
Thanks

**Comment by jpradocueva** [comment]
The registration of this object is taking place here: https://github.com/OpenMobileAlliance/lwm2m-registry/issues/9
