### ISSUE TITLE
OMNA-Registration of Voltage Logging

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#435]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-15 15:07:57 UTC</td></tr><tr><td>Submitter's name</td><td>Andrew Foster-Knight</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>South East Water Corporation</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Voltage Logging</td></tr><tr><td>Object Description</td><td>Object for logging and recording voltages from any voltage source (for example cathodic test points)</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=b3faf48f-43b1-4b78-8092-a6d78cda903b_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/b3faf48f-43b1-4b78-8092-a6d78cda903b_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b3faf48f-43b1-4b78-8092-a6d78cda903b_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
The registration of this object is taking place here: https://github.com/OpenMobileAlliance/lwm2m-registry/issues/10
