### ISSUE TITLE
OMNA-Registration of Network Monitoring

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#437]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-19 03:16:37 UTC</td></tr><tr><td>Submitter's name</td><td>Long Rong</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>China Mobile</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Network Monitoring</td></tr><tr><td>Object Description</td><td>network parameters</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=10132cea-81b7-4831-8aaf-f6c31a3f09ad_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/10132cea-81b7-4831-8aaf-f6c31a3f09ad_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=10132cea-81b7-4831-8aaf-f6c31a3f09ad_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Long Rong
Currently, this object has no [License declaration](http://devtoolkit.openmobilealliance.org/OEditor/License), which is a mandatory requirement.
Please, could you update the object and re-register it via the [Editor tool](http://devtoolkit.openmobilealliance.org/OEditor/Default). 
To aid in any further submissions user [guidelines](https://wiki.openmobilealliance.org/display/TOOL/Introduction+to+LightweightM2M) are available.
