### ISSUE TITLE
OMNA-Registration of Dissolved Oxygen

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#438]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-20 02:35:56 UTC</td></tr><tr><td>Submitter's name</td><td>Ha Phu</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Dissolved Oxygen</td></tr><tr><td>Object Description</td><td>Dissolved Oxygen shows us how much oxygen was dissolved in water</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=1c6b1e14-3b82-4b08-9e0f-1e532f193447_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/1c6b1e14-3b82-4b08-9e0f-1e532f193447_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1c6b1e14-3b82-4b08-9e0f-1e532f193447_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registrations doesn't comply with the registrations rules: http://www.openmobilealliance.org/documents/whitepapers/OMA-ORG-Guidelines_Creation_Registration_LwM2M_Objects_Resources-V1_0-20180209-A.pdf
