### ISSUE TITLE
LWM2M Object: Bearer Selection -- incomplete defintion of values for Preferred Communications Bearer Resouce

### ISSUE THREAD

**Issue by emmelmann-fokus** [OpenMobileAlliance/OMA_LwM2M_for_Developers#44]
LWM2M Object: Bearer Selection -- Preferred Communications Bearer Resource (ResID 0)

Specification of values incomplete
- Issue:  The spec does not define the use of values above 100.  This may lead to issues if implementations use these values that may later on be assigned by a revision of the standard
- Suggested Remedy:  Make values above 100 (i.e. 101 -- 254) "reserved";  assign at least one value as "vendor-specific".

**Comment by hannestschofenig** [comment]
The issue was not considered as worthwhile to address.
