### ISSUE TITLE
OMNA-Registration of Test

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#440]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-24 22:14:14 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Test</td></tr><tr><td>Object Description</td><td>Testing migration functionality</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=176c6b2d-9f30-4e3d-8713-dade1f443638_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/176c6b2d-9f30-4e3d-8713-dade1f443638_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=176c6b2d-9f30-4e3d-8713-dade1f443638_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Testing migration functionality -
