### ISSUE TITLE
OMNA-Registration of AT&T Connectivity Extension

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#441]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-11-29 19:16:40 UTC</td></tr><tr><td>Submitter's name</td><td>David K Smith</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>AT&T</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>AT&T Connectivity Extension</td></tr><tr><td>Object Description</td><td>The AT&T Device Management Object will be used to gather information describing the UE and the operating state of the UE.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=b18e55cd-0174-4aa0-8728-314413c546d0_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/b18e55cd-0174-4aa0-8728-314413c546d0_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b18e55cd-0174-4aa0-8728-314413c546d0_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is discussed in the new OMNA LwM2M Registry repository: https://github.com/OpenMobileAlliance/lwm2m-registry/issues/4
