### ISSUE TITLE
OMNA-Registration of OpticalBox-Lock

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/OMA_LwM2M_for_Developers#442]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-04 08:25:25 UTC</td></tr><tr><td>Submitter's name</td><td>OpticalBoxLock</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>GTI</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>OpticalBox-Lock</td></tr><tr><td>Object Description</td><td>gjx</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=3273a00d-d6e9-45e6-8d08-0ccf4e4c180c_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/3273a00d-d6e9-45e6-8d08-0ccf4e4c180c_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=3273a00d-d6e9-45e6-8d08-0ccf4e4c180c_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This registration is replaced by #443
