### ISSUE TITLE
Spec of BinaryAppDataContainer

### ISSUE THREAD

**Issue by chelliwell** [OpenMobileAlliance/OMA_LwM2M_for_Developers#444]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``:
* Section of the document, ``(e.g. section: 6.2)``:
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

**Comment by chelliwell** [comment]
The spec for this object (V1_0-20180615-A) has an Informative appendix B. I was wondering why the 'Resource ID' column on Table 3 goes from 1-4. Shouldn't it be from 0-3 as per Table 2?  e.g. "Data" is always a Resource ID of 0.
Is this a column of typos, or am I misunderstanding the defining of Resources?

**Comment by Echo-xubei** [comment]
It's a column of typos. The Resource ID of Table 3 should goes from 0-3. We will add a PR to address this issue.

**Comment by chelliwell** [comment]
Thanks for confirming.
I also wondered about the "Data Creation Time" resource. What was the intention for this - the name suggests creation time of the data (read? write?), but the description says timestamp of the _object instance_ creation.

**Comment by changhongna** [comment]
The "Data Creation Time" shoud be the creation time of the "Data" Resource.
I will submit a CR to correct it. Thanks for your comment.

**Comment by changhongna** [comment]
The CR has been submitted to the OMA portal:
http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/2019/OMA-DM-LightweightM2M-2019-0003-CR_Bug_Fix_for_BinaryAppDataContainer.zip

**Comment by Echo-xubei** [comment]
The CR LightweightM2M-2019-0003 has addressed this issue and the R&A has started. This issue could be closed once the CR is agreed.

**Comment by hannestschofenig** [comment]
Is the CR public in the meanwhile, Echo?

**Comment by hannestschofenig** [comment]
The new version of the spec will become public in the next few weeks.

**Comment by Echo-xubei** [comment]
The new version of the spec has been public. This issue can be closed.
http://openmobilealliance.org/release/LwM2M_APPDATA/
