### ISSUE TITLE
A very basic question about LWM2M transport layer

### ISSUE THREAD

**Issue by yummychop** [OpenMobileAlliance/OMA_LwM2M_for_Developers#445]
Hi, I would like to use LWM2M protocol over LTE, I would like to ask is it possible to use LWM2M over LTE-A/LTE-Advanced Pro? Or LWM2M can only be implemented on LTE-M/LTE-NB ( LPWAN LTE)? 
Thank you in advance

**Comment by mojanm** [comment]
Yes, absolutely. LwM2M can be used across a wide range of networks, cellular, WLAN, etc. It's designed to accommodate constrained devices where there may be limitation on power consumption, processing power or bandwidth. However, this design approach does not make it any less usable on high end devices deployed across high data rate networks.
See also Cellular connectivity (object id10), APN connection profile (oid 11), WLAN Connectivity (oid 12) as to how a Lwm2M device could be configured to efficiently make use various access technologies.

**Comment by hannestschofenig** [comment]
@yummychop: Please take a look at the v1.1 protocol and bugfix release (v1.1.1) will be released very soon, which incorporates feedback we have received.  

Here is the link to the spec: 
http://openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/
