### ISSUE TITLE
pmax and def max period missing: "The value of 0, means pmax MUST be ignored" sentence should be added

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#449]
OMA specification OMA-TS-LightweightM2M-V**1_0_2**-20180209-A doesn't explain as well what happen if pmax and Def max period are both missing.
this is the sentence:
Section 5.1.2 Attributes Classification
...
_Notes: The Maximum Period Attribute indicates the maximum time in seconds the LwM2M Client MAY wait between two notifications. When this "Maximum Period" expires after the last notification, a new notification MUST be sent. In the absence of this parameter, the "Maximum Period" is defined by the Default Maximum Period when set in the LwM2M Server Account or considered as 0 otherwise._

I don't know what 0 value could be managed: I don't want to send notifies every 0 seconds!

I see that the new OMA-TS-LightweightM2M_Core-V**1_1**-20180710-A specification explains better the meaning of 0 value.
Section 5.1.2 Attributes Classification
...
_**The value of 0, means pmax MUST be ignored.**_

Since this is a shared feature, could you add the same explanation into the 1.0.2 specification?

**Comment by asoloway64** [comment]
Thank you for your input. There is no proposal at this time to update the v1.0.2 specification. If additional updates to that specification become necessary, the above statement will be considered for inclusion.

**Comment by hannestschofenig** [comment]
Giuseppe, we added the following statement to the LwM2M v1.1 specification: 
“The value of 0, means pmax MUST be ignored.”

See page 21 of 
http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.pdf

I hope this helps!

**Comment by giuseppe-melis** [comment]
@hannestschofenig is it the same statement that I recall in the last part of the ticket description?

_I see that the new OMA-TS-LightweightM2M_Core-V1_1-20180710-A specification explains better the meaning of 0 value._
_Section 5.1.2 Attributes Classification_
...
_The value of 0, means pmax MUST be ignored._

since the 1.1 version has been clarified, my question was:
_Since this is a shared feature, could you add the same explanation into the 1.0.2 specification?_

From my point of view, it's clear that the rule _The value of 0, means pmax MUST be ignored_ is valid also for 1.0.2 version even without explicit explanation in v1.0.2 specification.
According to @asoloway64 comment, it will be added to v1.0.2 spec document in future.
For me the issue can be closed.
Do you agree?
