### ISSUE TITLE
TLV object instance presence for write request

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#452]
I feel there is a kind of ambiguity in the specification. (This concerns LWM2M v1.0.x and v1.1)

In _§6.3.3 Write in v1.1_, the specification say :
_"If no Resource ID is indicated, ... ... , then the value included payload is an Object Instance containing the Resource value"_
(pretty much the same in _§5.4.3 Write in v1.0.x_)

But in _§7.4.3 TLV in v1.1_, the specification say : 
_"For simplicity and to prevent any ambiguity on Object Instance Identity, when the Object Instance ID is not specified in the request, the Object Instance TLV MUST be use"_
(same in _§7.4.3 TLV in v1.0.x_)
=>Which hints this is possible to not use it if object instance id is present in the request.

The example at _"§7.4.3.1. Single Object Instance Request Example"_ seems to confirm that. Because for a Read request on 3/0, the object instance level is not present in TLV.

I feel _§Write_ paragraph describes the "high level picture", then each content format can contain some kind of particularity ? but It sounds to be not so clear for every one => https://github.com/eclipse/leshan/issues/660

**Comment by hannestschofenig** [comment]
In the Write operation the object instance Id is required and hence the quoted statement from Section 7.4.3 cannot apply.

**Comment by sbernard31** [comment]
I feel there is a misunderstanding.

I try differently.

§7.4.3 TLV in v1.1(same in §7.4.3 TLV in v1.0.x), the specification say :
>"For simplicity and to prevent any ambiguity on Object Instance Identity, when the Object Instance ID is not specified in the request, the Object Instance TLV MUST be use"


=> Which hints this is possible to omit the Object instance TLV **when the object instance id is present in the request**.

But where is this applicable ? 
It seems that : 
[Read request](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-1-0-631-Read), [Write request](www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-3-0-633-Write), [Bootstrap Write](www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-3-0-633-Write) when object ID is present object instance MUST not be omit.
> If no Resource ID is indicated, then the value included **payload is an Object Instance containing the Resource values.**

Only [bootstrap read](www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-3-0-633-Write) does  not say that explicitly. (I'm not sure this is intended or just no there because the information is generally present in RESOURCE ID column which is not present)

So the §7.4.3, sounds not applicable ? (read example in 7.4.3.1 is not correct ?)
or
each content format can contain some kind of particularity ?

**Comment by asoloway64** [comment]
I think "each format can contain some kind of particularity" is correct as 7.4.3 is general and has contextual specifics when applied to each operation.

**Comment by sbernard31** [comment]
@asoloway64, Just to be sure I get the your point.

Is it possible to omit the Object Instance level with TLV format for a WRITE request ?

**Comment by asoloway64** [comment]
My opinion is "Yes". Since the object instance ID is included in the WRITE operation URL, it does NOT NEED to be included in the TLV payload (from a functionality perspective). I don't see any error in the specification. "when the Object Instance ID is not specified in the request, the Object Instance TLV MUST be used" does not mean that when the object instance Id IS specified in the request, the object instance Id MUST NOT be in the payload. You can interpret the text to mean that if the object instance Id IS in the URL, then the object instance Id NEED NOT be in the TLV payload. Whether Clients are expecting it in TLV payload is an interoperability question.

**Comment by sbernard31** [comment]
>  I don't see any error in the specification

I would not say there is an error too. But maybe just an ambiguity ? At the beginning the question was raised by a Leshan user (eclipse/leshan#660). I don't know if it is possible to change the text to make is less ambiguous ?

Anyway, for this is now clear for me. Thx for you detailed answer.
(On my side you can close this issue)
