### ISSUE TITLE
clarify how to register to the Slack channel

### ISSUE THREAD

**Issue by kai-chi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#454]
I wanted to join the Slack channel but the README doesn't specify how to register.
Scrolling through the git log I found a link to the gitter channel and there a tip to ping helpdesk@omaorg.org. They now opened a JIRA ticket for it and asked me to create a JIRA account. Looks like it's progressing but it would be nice if details about the process would be included in the README.
Thanks!

**Comment by seanmcilroy29** [comment]
Many thanks for your observation. 
I've now added to the README a line of text ```To request an Invite to the LwM2M chat room email helpdesk@omaorg.org```.
This will automatically create a ticket in JIRA for the staff to work to action.
