### ISSUE TITLE
Create request can be use to create several object instances ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#456]
I always thought that create operation only allowed to create 1 object instance (by request).

But reading the specification again, I have doubts because of [§6.3.6. Create](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#6-3-6-0-636-Create) :
_"The "Create" operation is used by the LwM2M Server to create **Object Instance(s)** within the LwM2M Client"_
(same in LWM2M v1.0.x §5.4.6 Create)

I suppose its just a typo, but I would like confirmation.
(If this is true, this should also be fixed in the table same chapter)

**Comment by hannestschofenig** [comment]
Nothing in the spec prevents a LwM2M Server from creating multiple instances of an object in a LwM2M Client with a single request.

**Comment by sbernard31** [comment]
I don't know why I believed that :thinking: ...
@dnav Do you support Multi instances Create Request in wakaama ?
