### ISSUE TITLE
which Resource contains MAC/EUI-64?

### ISSUE THREAD

**Issue by kai-chi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#457]
Hi,
I have troubles interpreting the documentation and I am not sure in which Object/Resource I can find the MAC/EUI-64 address? Two potential candidates are:
1. Object 3 - Device - Field "Serial Number"
2. Reusable Resource 5907 - "Host Device Unique ID"

Is it any of these two or even another one?
Thanks!

**Comment by hannestschofenig** [comment]
It depends what you want to accomplish. 

Are you trying to create a new object that has a resource with a MAC/EUI-64 address in there? 

Could you provide a bit more context about the use case you have in mind?

**Comment by kai-chi** [comment]
Hi @hannestschofenig,

I am writing a LWM2M server and I would like to be able to identify the connected devices with a unique ID. Assuming that they can disconnect/re-register/connect to another server it has to be something hardcoded, making the MAC address a perfect candidate.
I am using the Leshan implementation where I automatically get a "Registration ID". The problem is it's more like a session ID so every time the device disconnects and connects the ID will change. I want to be able to track the device across multiple sessions and multiple servers so it has to be something sitting on the device itself.

I don't want to create new objects. I would like to use something available and be compliant with the specification.

**Comment by sbernard31** [comment]
@kai-chi  what identifies the client is not "registration id" but "Endpoint Client Name"

_"Identifies the LwM2MClient on one LwM2M Server (including LwM2MBootstrap-Server).
Provided to the LwM2MServer during Registration, also provided to LwM2MBootstrap-Server when executing the Bootstrap procedure."_

Look at **§5.3.1 Register** an **§8.2.4 Registration Interface** (LWM2M 1.0.x)

**Comment by kai-chi** [comment]
@sbernard31, right, my mistake, I was referring to "Endpoint Client Name". 
Nevertheless, the problem remains the same. The "Endpoint Client Name" is session-based. If the device reboots it registers with a new name. 
An option to track its activity across multiple sessions would be to bind its "Endpoint Client Name" with its data link layer identifier and that's what I'm trying to do.

**Comment by sbernard31** [comment]
I do not understand **endpoint name** is supposed to be an identifier. It should not changed after a reboot... It is not session-based identifier.

So I pretty sure it can be used to identify the device.

**Comment by kai-chi** [comment]
@sbernard31, that is correct. I was mistaken. Thanks for pointing it out.
Then makes it possible to identify the device across sessions.
Is there still a way to extract a device's MAC with LWM2M?

**Comment by sbernard31** [comment]
I don't know exactly what could mean MAC address in a general way as a device could have several network interfaces.

I suppose if something like this was available it should be in an object like [**Connectivity Monitoring**](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) ? 
But I can not see it. :confused: 

Anyway, the LWM2M specification says that endpoint name (device identifier) should use an URN form (see §6.3.1 from lwm2m 1.0.x)
So, if you still have the idea to use MAC address as identifier, maybe you could consider to use this kind of URN based on MAC `urn:dev:mac:0024befffe804ff1` which are defined in [draft-ietf-core-dev-urn ](https://tools.ietf.org/html/draft-arkko-core-dev-urn-05)  

But the draft also says : 
```
   Universally Unique IDentifier (UUID) URNs [RFC4122] are another
   alternative way for representing device identifiers, and already
   support MAC addresses as one of type of an identifier.  However,
   UUIDs can be inconvenient in environments where it is important that
   the identifiers are as simple as possible and where additional
   requirements on stable storage, real-time clocks, and identifier
   length can be prohibitive.  UUID-based identifiers are recommended
   for all general purpose uses when MAC addresses are available as
   identifiers.  The device URN defined in this memo is recommended for
   constrained environments.
```

**Comment by kai-chi** [comment]
Ok, I think I got now what you were trying to say from the beginning @sbernard31 :wink: 
Thanks a lot for a comprehensive response!
