### ISSUE TITLE
OMA CP internet/WAP/MMS IPv6 configuration not working

### ISSUE THREAD

**Issue by InvSup** [OpenMobileAlliance/OMA_LwM2M_for_Developers#458]
I was trying to configure the mobile devices for IPv6 internet, WAP and MMS over-the-air (OMA CP). I tried sending the attached OMA CP XMLs to Android and Symbian devices. The OTA settings are successfully installed however the field 'APN Protocol' on Android devices and the field 'Network Type' on Symbian devices remain 'IPv4'. Does it need to be updated to IPv6 to let the device attach to data network? 
I am using the below XML for internet... Is it correct? 
<wap-provisioningdoc>
	<characteristic type="BOOTSTRAP">
		<parm name="NAME" value="gprstest"/>
	</characteristic>
	<characteristic type="NAPDEF">
		<parm name="NAME" value="gprstest"/>
		<parm name="NAPID" value="NIDS162"/>
		<parm name="BEARER" value="GSM-GPRS"/>
		<parm name="NAP-ADDRESS" value="IPV6"/>
		<parm name="NAP-ADDRTYPE" value="fe80::5025:59ac:ec25:ce00"/>
		<parm name="INTERNET"/>
	</characteristic>
</wap-provisioningdoc>

Thx

**Comment by InvSup** [comment]
This is the XML I am using : 

> <wap-provisioningdoc>
	<characteristic type="BOOTSTRAP">
		<parm name="NAME" value="gprstest"/>
	</characteristic>

	<characteristic type="NAPDEF">
		<parm name="NAME" value="gprstest"/>
		<parm name="NAPID" value="NIDS162"/>
		<parm name="BEARER" value="GSM-GPRS"/>
		<parm name="NAP-ADDRESS" value="IPV6"/>
		<parm name="NAP-ADDRTYPE" value="fe80::5025:59ac:ec25:ce00"/>
		<parm name="INTERNET"/>
	</characteristic>

</wap-provisioningdoc>

**Comment by hannestschofenig** [comment]
I fear that nobody is working on OMA CP anymore...

**Comment by homstr** [comment]
Hello. 

> I fear that nobody is working on OMA CP anymore...

Can i ask you to give me some kind of info about the method of sending an APN-settings to the mobile device?
i thought that it is the PUSH SMS... but i did not understood the format yet (((

**Comment by EugeneBogush** [comment]
Hi homstr,
what are you using for sending OMA CP(soft,hard)?
Thanks

**Comment by homstr** [comment]
I tryed to send it by the kannel, but i guess that was wrong... i think there must be another way to tell to mobile phone which AP it should use...
