### ISSUE TITLE
Relation of Binding mode and Security instances in LwM2M 1.1

### ISSUE THREAD

**Issue by sznaider** [OpenMobileAlliance/OMA_LwM2M_for_Developers#459]
This issue affects specification ``OMA-TS-LightweightM2M_Core-V1_1-2018MMDD-A`` /
``v1_1-bug-fix: 26 Feb 2019 15:31:00 rev: 58c49b5``.

Let me start with a little bit of background. In LwM2M 1.0 we only had two transports: UDP and
SMS. Each of which could be pretty much configured within a single Security Instance, because
each transport got dedicated Resources for that purpose. This means that every configured LwM2M
Server needed exactly one Security Instance.

Things got slightly less clear in LwM2M 1.1, as additional binding modes were introduced (TCP,
Non-IP). At the same time, it doesn't seem like more transport-specific resources were added
to Security Object. This somewhat indicates that the whole conception of server configuration
that I have is different from the conception authors of the specification had in mind.

I am, therefore, going to assume that because it is nowhere forbidden, LwM2M 1.1 technically
allows ALL transports (and thus corresponding binding modes T, U, S, N), to be set in Binding
Mode Resource (i.e. literally "NSTU") for a single LwM2M Server. That is, if configured, the
server can potentially be reached by either UDP, TCP, SMS, or some Non-IP protocol.

This leads to the following list of questions:

1. Can LwM2M Server have multiple corresponding Security Instances (i.e. all of them sharing the same Short Server ID)?
    - If that's the case, **3.2. Definitions** defines //LwM2M server account// to be: "LwM2M Security Object Instance with Bootstrap-Server Resource false and associated LwM2M Server Object Instance", and that would require fixup.
    - Or, if one LwM2M Server can have multiple accounts, it would make sense to indicate that somewhere (that Server instance is shared between all LwM2M Server accounts).

2. If multiple Security instances are allowed, how should one map binding mode to specific protocol in LwM2M Server URI?
    - ``coap(s)://`` -> ``U``?
    - ``coap(s)+tcp//`` -> ``T``?
    - what would the protocol look like for `S` and `N` bindings?
    - or maybe the protocol shall be ignored? But in that case I really don't see how the Client is supposed to figure out the connection method.

3. If multiple Security instances are allowed, is it MANDATORY to have exactly one Security instance per specific transport mode? At most? Or at least?
    - That is, if you have Binding Mode in Server instance set to "NSUT", does that mean the correctly configured Client has at least four Security instances, each of it corresponding to exactly one binding for that server?
    - Or maybe, Binding Mode only specifies which bindings are supported by the Server, but that does not necessairly mean the Client can use all of them?

4. If multiple Security instances are present, which one configures SMS transport? What is the purpose of SMS related Resources in Security Instance? What if each Security Instance fills SMS related resources differently?

5. Going back for a moment to LwM2M 1.0. Were multiple Security instances for single server allowed in 1.0?

However, if only one Security instance per server is allowed, then I guess that interpretation is that the Client can communicate with the server through at most two transports (SMS + some other transport as determined by URI)?

Side note: under the table [6.2.1.2.-1 Behaviour with Current Transport Bindings](http://45.56.97.224/docs/58c49b5/TS_Core/OMA-TS-LightweightM2M_Core-V1_1-2018MMDD-A_full.html#Table-6212-1-Behaviour-with-Current-Transport-Bindings) there's a statement:

> The client SHALL assume that the server supports the UDP binding even if the server does not include UDP (“U”) in the "binding" resource of the LwM2M server object (/1/x/7).

How could it assume something like this, if for example the Security Object configures only
Non-IP protocol transport? Or maybe such configuration would be invalid?

If most of my guesses were correct, there remains additional topic of SMS Trigger mechanism,
but I'll leave that to separate ticket to keep things digestable.

**Comment by hannestschofenig** [comment]
Sorry for the late response. 

> Can LwM2M Server have multiple corresponding Security Instances (i.e. all of them sharing the same Short Server ID)?

Multiple Security Object Instances can point to the same LwM2M Server (via the short server id). 

> If multiple Security instances are allowed, how should one map binding mode to specific protocol in LwM2M Server URI? 

The URIs indicate the way how messages are transported (which is mapped to the binding modes).
- U (UDP)	
- T (TCP)	
- S (SMS)	
- N (Non-IP)	

The LwM2M Server URI encodes the binding mode in the URI scheme. 

coap(s):// -> U
coap(s)+tcp// -> T
For S you have a tel URI scheme and for N it depends what non-IP transport you use. 
For example, for LoRaWAN that would translate to lorawan://
I have to check for NB IOT related stuff. 


> If multiple Security instances are allowed, is it MANDATORY to have exactly one Security instance per specific transport mode? At most? Or at least?

If you support multiple transports with different servers then you would use different credentials with these servers. This translates to multiple security instances. Because the URIs in the security object will be different it will always translate to multiple instances of the security object. 


> If multiple Security instances are present, which one configures SMS transport?

Any of them. The way the SMS functionality was defined dates back to the original version of LwM2M and there are unfortunately some design flaws in there. Someone will have to fix it. So far, there just hasn't been enough interest in SMS anymore so that it was fixed. 

> Going back for a moment to LwM2M 1.0. Were multiple Security instances for single server allowed in 1.0?

Yes. This concept hasn't been changed with v1.1.

**Comment by hannestschofenig** [comment]
Did this answer your question?

**Comment by sznaider** [comment]
Yes, thank you for the answers!
