### ISSUE TITLE
LWM2M IPR question.

### ISSUE THREAD

**Issue by softgearko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#46]
Anybody can describe IPR issues when one uses LWMWM?
In IoT world, there are many small companies. Therefore, IPR policy should be changed to more free, I think.
First of all, we need to make the IPR declaration list about LWM2M.

**Comment by softgearko** [comment]
Anybody can describe IPR issues when one uses LWMWM?
In IoT world, there are many small companies. Therefore, IPR policy should be changed to more free, I think.

**Comment by jvermillard** [comment]
http://openmobilealliance.org/about-oma/policies-and-terms-of-use/intellectual-property-rights/ ?

**Comment by ThGarnier** [comment]
To be closed.  If the IPR OMA policy (mentioned by Julien) is questionable, the DM Group is definitively the not the right group to address it  (as said  in the IPR link "For questions regarding the OMA IPR Policy please contact the OMA Membership Manager of the OMA Staff")

**Comment by jvermillard** [comment]
@softgearko please note OMA is running a survey about open-source and therefor IPR implication: https://www.surveymonkey.com/r/OSSPublic

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment regarding IPR. Please contact the OMA staff regarding IPR declarations < http://openmobilealliance.org/contact-us/ > or find out more about IPR here:
http://openmobilealliance.org/about-oma/policies-and-terms-of-use/intellectual-property-rights/
