### ISSUE TITLE
notify in case pmax and pmin attributes alone

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#461]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A
* section: 5.1.2 Attributes Classification:
_Notification Conditions : the notification of a Resource value will be sent when:
₋ valid Change Value Conditions (“Greater Than”, “Less Than”, OR “Step”) - if any is defined - AND the “Minimum Period” Timing Conditions are both fulfilled for that Resource OR
₋ the “Maximum Period” Timing Condition is fulfilled._

Clarification about Notify is requested:

### a) if only pmax is set (i.e 60 seconds):
.  a1) if the resource **doesn't change within 60 seconds**, the notify must be sent when pmax expires (60). for me this is clear.

.  a2) if the resource **changes before 60 seconds** (i.e. 45 seconds), should the notify be sent as soon as possible (45) or when pmax expires (60)?

### b) if only pmin is set (i.e 10 seconds):
.  b1) if the resource **doesn't change within 10 seconds**, for me no notify is needed until the resource will change. do you confirm?

.  b2) can pmin **be set alone without "Change Value Conditions"** (“Greater Than”, “Less Than”, “Step”)?

**Comment by dnav** [comment]
Disclaimer: these answers are mine only.

a1: yes

a2: as soon as possible

b1: yes

b2: yes

**Comment by hannestschofenig** [comment]
This is a question that should be asked to the IETF CORE mailing list because they are supposed to work on https://tools.ietf.org/html/draft-ietf-core-dynlink

My answers would, however, be the same as those provided by David.

**Comment by asoloway64** [comment]
I also agree with David's answers.

**Comment by bsilverajan** [comment]
I'm coming in from the CoRE Working Group as the editor of draft-ietf-core-dynlink.

Informally, this is what pmax and pmin mean, from a client's perspective that it wishes the server to do:

"Regardless of whether the value of the resource changes or not,  I would always like to know its value at the very latest, once pmax expires".

"Regardless of whether the value of the resource changes or not, do not send me its value any quicker than what I have specified for pmin".

These attributes can be used independently, without other attributes present. If other attributes are present in an observe request, then section 3.2 of draft-ietf-core-dynlink-08 explains how server processing of these attributes proceed.

Hope that helps.

**Comment by giuseppe-melis** [comment]
@bsilverajan 
reading deeply your statement:
_"Regardless of whether the value of the resource changes or not, I would always like to know its value at the very latest, once pmax expires"._
what about my question a2?
as soon as possible (45) or when pmax expires (60)?

**Comment by bsilverajan** [comment]
@giuseppe-melis In the case of a2, if the implementation of the server's sampling rate is set to be shorter than pmax, then it can be sent as soon as a change is detected.
