### ISSUE TITLE
Can the LWM2M Client change the ServerURI resource when it act as a DTLS Client role before the Server Initiated Bootstrap?

### ISSUE THREAD

**Issue by lanyuflying** [OpenMobileAlliance/OMA_LwM2M_for_Developers#462]
When submitting an issue please indicate the following information:
* OMA-TS-LightweightM2M-V1_0-20170208-A``:
* 7.1.6 LwM2M and DTLS Roles``:
* Server Initiated Bootstrap: 
* the specification need the four is equal:
When the LwM2M Client acts in the role of a DTLS server then care has to be taken that the following four values are equal:
(1) Value in the Server Name Indication (SNI) extension used in the DTLS exchange,
(2) Endpoint Client Name,
(3) Identifier used with the credential, such as the identifier contained in the DTLS server certificate, and
(4) Value in the LwM2M Server URI Resource.

but the  LwM2M Server URI  is used for the LWM2M Client to access the LWM2MServer,and before cmpleted the  Server Initiated Bootstrap,the LWM2M Server URI couldn‘t be changed?

So,it cann't equal to the Endpoint Client Name?

**Comment by lanyuflying** [comment]
and I also think the LWM2M ServerURI is  no need to the Endpoint Client Name at anytime. Because after
the Server Initiated Bootstrap,the LWM2M ServerURI resource should be changed to the new LWM2MServer URI,so it's impossible to keep the LWM2MServer URI be equal to the Endpoint Client Name.

**Comment by hannestschofenig** [comment]
The server-initiated bootstrapping procedure in LwM2M v1.0 contained bugs that have been resolved in later versions of the spec. Please consult version 1.1 where we changed the server-initiated bootstrapping procedure into a server-triggered exchange followed by client-initiated bootstrapping instead.

**Comment by hannestschofenig** [comment]
Did this answer your question?
