### ISSUE TITLE
Is it OK for a client to De-Register during Firmware package download?

### ISSUE THREAD

**Issue by fdur** [OpenMobileAlliance/OMA_LwM2M_for_Developers#465]
* Specification OMA-TS-LightweightM2M-V1_0-20160802-C)
Related to https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/300

When a package is downloaded by the LwM2M client in alternate mode (package URI and pull mode), does it make sense that the LwM2M client sends a de-register message to the LwM2M server during the package download?

**Comment by hannestschofenig** [comment]
What purpose would the deregistration of the LwM2M Client have?
