### ISSUE TITLE
Package URI in Software Management Object

### ISSUE THREAD

**Issue by cavenaghi9** [OpenMobileAlliance/OMA_LwM2M_for_Developers#466]
* OMA-TS-LWM2M_SwMgmt-V1_0-20180301-A.pdf
* Section: 6.

There is no delivery method resource defined in Object 9, like /5/0/9
There is no software install protocol support defined in Object 9, like /5/0/8

Can consider /9/x/3 only support HTTP, and HTTP(s), or it can support any kind of protocol, like FTP, etc..

**Comment by hannestschofenig** [comment]
Thanks for noting these limitations. We are planning to produce an updated version of the enabler/object description to improve its quality.

**Comment by hannestschofenig** [comment]
The software management package defines the Package URI resource, which gives the LwM2M Client enough information about the protocols being used for downloading software packages. (The protocol can be inferred from the URI scheme itself.)

If you believe it would be valuable for the LwM2M client to inform the LwM2M Server what other protocols it supports for software download, which is what the "Firmware Update Protocol Support"
resource from the Firmware Update object provides, then you have to submit a pull request for adding this feature. 

Regarding your second question: "Can consider /9/x/3 only support HTTP, and HTTP(s), or it can support any kind of protocol, like FTP, etc.."?

Resource 3 "Package URI" supports any protocol as long as you can express it via a URI schema. This means that ftp would also be supported. A list of registered URI schemes is available here: https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

**Comment by cavenaghi9** [comment]
thank for your answer.
