### ISSUE TITLE
Documentation Update Suggestion - LOCATION object

### ISSUE THREAD

**Issue by rbadrinath** [OpenMobileAlliance/OMA_LwM2M_for_Developers#468]
* This is a request to minor update documentation 
* where the error appears: http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#omalabel
* Item in error is documentation of urn:oma:lwm2m:oma:6 
* Detail: I believe that the Description string should appropriately say this object is for the location related information of the device such as its lat/long position and velocity.

**Comment by hannestschofenig** [comment]
Thanks for pointing the inconsistency of the location object out. I have reached out to staff to fix the text on the website.

**Comment by jmudge** [comment]
Thank you both for highlighting this.

When publishing objects I understand it is normal practice to populate the LwM2M Object and Resource Registry description field with the description text from the corresponding ERELD/README document OMNA Considerations section.

The ERELD OMNA Considerations description text (from http://openmobilealliance.org/release/ObjLwM2M_Location/V1_0_2-20190617-A/OMA-ERELD-LWM2M_Location-V1_0_2-20190617-A.txt) is "It provides a range of device related information which can be queried by the LwM2M Server, and a device reboot and factory reset function.". This matches the corresponding text in the LwM2M Object and Resource Registry.

It is suggested that a consistent source be used for the description field for all the OMA objects in the LwM2M Object and Resource Registry. I will check with the DMSE WG on how to proceed.
