### ISSUE TITLE
Optional Endpoint Client Name

### ISSUE THREAD

**Issue by mateusz-olczyk** [OpenMobileAlliance/OMA_LwM2M_for_Developers#470]
In _OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A_, section 7.3.1. Endpoint Client Name it is stated that:

> This parameter MAY be omitted when the security protocol provides to the server an authenticated identifier that is identical to this parameter.

What exactly is _authenticated identifier_? What should the client compare its endpoint-name to, before determining that it can be safely omitted in Register message?

**Comment by sbernard31** [comment]
This is the identifier found at secure layer level.
E.g. when using DTLS there is always something like a kind of identifier.

If you are using PSK this will be psk ID, if you are using RPK this will be the Public Key, if you are using X509 the CN must be the endpoint-name (if I remember well)

Even if endpoint-name is sent by the device, server should ensure that the endpoint-name match (directly or indirectly using lookup table) the secure layer identity.  If server don't do that, it's very easy to usurp any device with only 1 valid credentials.

(If you read java fluently, you could have a look at https://github.com/eclipse/leshan/blob/leshan-1.0.0-M12/leshan-server-core/src/main/java/org/eclipse/leshan/server/security/SecurityChecker.java#L27)

Here is maybe a part of the specification, you missed [§5.2.6-Endpoint Client Name](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.html#5-2-6-0-526-Endpoint-Client-Name)

So, my understanding is "when using DTLS you can always omit endpoint client name." (but if you do that LWM2M v1.0.0 server will don't really like this :p)

**Comment by hannestschofenig** [comment]
Very useful response, @sbernard31
