### ISSUE TITLE
Module object definition

### ISSUE THREAD

**Issue by kbonset** [OpenMobileAlliance/OMA_LwM2M_for_Developers#471]
Is anyone aware of object definitions of sensor modules? For example, I would expect a Modbus module to have a firmware version, serial number, name, measurement interval, etc. I'm looking for objects with definitions analogous to the WLAN Connectivity object (12).

Maybe this information is too vendor specific for such a generic definition. Any pointers appreciated though.

**Comment by sbernard31** [comment]
You probably already know this but you can find [here](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) the LWM2M registry with current registered object definition.

**Comment by jpradocueva** [comment]
@kbonset Please note that the WLAN Connectivity object has received a some changes. The Object is now in version v1.1, which is not public yet.

Un officially, I can make it available here. The DM Working Group has approved the latest changes, but this object together with the rest of Connectivity Management Objects are awaiting for Board ratification, scheduled for October 10th.

**Comment by kbonset** [comment]
Thanks, but not necessary to make available the latest version of the WLAN Connectivity object. My interest is in sensor modules. If it doesn't exist, I can create it. I just didn't want to reinvent one. :-)

**Comment by hannestschofenig** [comment]
@kbonset If you cannot find the sensor definition you are looking for please consider registering one with the LwM2M registry.

**Comment by kbonset** [comment]
Thanks @hannestschofenig, will do.
