### ISSUE TITLE
Format of execute arguments in SenML JSON / SenML CBOR

### ISSUE THREAD

**Issue by panekk** [OpenMobileAlliance/OMA_LwM2M_for_Developers#472]
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* Section 6.3.5
* Table 6.3.5.-1

What should be the format of execute arguments sent as SenML JSON or SenML CBOR?
It's a new feature introduced in 1.1.1, but it's not defined which labels should be used (existing, or LwM2M-specific, like "vlo"?).

**Comment by hannestschofenig** [comment]
We will discuss this topic next week at our face-to-face meeting.

**Comment by hannestschofenig** [comment]
We discussed the topic and concluded that it does not make sense to offer three different encoding options for conveying execute arguments. Hence, we will change the text and remove the option for SenML JSON and SenML CBOR. 

Thanks for spotting this issue.

**Comment by akeranen** [comment]
Why not allow different encoding options? Wouldn't this depend on the resource? Some could allows just text, some, for example CBOR.
