### ISSUE TITLE
Bootstrap-Discover on object instance information

### ISSUE THREAD

**Issue by cjacquinot** [OpenMobileAlliance/OMA_LwM2M_for_Developers#474]
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* Section 6.1.7.3

In the example of the Bootstrap-Discover on Security object (/0) why are there attributes relative to "/"?

`</>;lwm2m=1.1,</0/0>;ssid=101;uri="coaps://server_1.example.com", </0/1/>,</0/2>;ssid=102;uri="coaps://server_2.example.com"`

**Comment by hannestschofenig** [comment]
Section 6.1.7.3 says: 

> The returned payload is a list of application/link-format CoRE Links [RFC6690] containing the LwM2M Enabler Version and for each targeted Object - in addition to the Object Version, see Section 7.2. Object Versioning and Table: 5.1.2.-1 Class Attributes - a sub-list of the Instances of such an Object Instance.

Core Link Format requires us to include the path </> in addition to the version lwm2m=1.1 info

**Comment by cjacquinot** [comment]
Do we really need the LwM2M Enabler Version information for a Bootstrap-Discover on an object?
