### ISSUE TITLE
Problems with Object 10 definition in version 1.0 of it

### ISSUE THREAD

**Issue by panekk** [OpenMobileAlliance/OMA_LwM2M_for_Developers#475]
* Name, version and date of the document: OMA-ETS-LightweightM2M-V1_0_2-20180815-A, OMA-ETS-LightweightM2M_INT-V1_1-20190912-D
* Section of the document: 6.3.3.1

We encountered two problem with specification of Cellular connectivity object:
1. There are resources with ID up to 11, but the both ETSes say about resources 13 (Power Saving Modes) and 14 (Active Power Saving Modes).
2. Activated Profile Names resource (ID 11) has a type of String, but the description says it contains "links".

There is a draft of this object in version 1.1: http://member.openmobilealliance.org/ftp/Public_documents/DM/LightweightM2M/Permanent_documents/OMA-TS-LWM2M_ConnMgmt-V1_1-20180314-D.zip
Maybe it should be released officially, since there are test cases for it.

**Comment by seanmcilroy29** [comment]
Aware of the problem and the new objects are due to be approved this week
