### ISSUE TITLE
Invalid Event Log test specification

### ISSUE THREAD

**Issue by panekk** [OpenMobileAlliance/OMA_LwM2M_for_Developers#476]
* Name, version and date of the document: OMA-ETS-LightweightM2M_INT-V1_1-20190912-D, 
* Section of the document: 6.3.7.1

In both ETSes, there is:

> 1. A WRITE (CoAP PUT) operation with a valid value is performed by the Server on the LogStart Resource (/20/0/4011) of the Event Log Object
> 2. The Server READs (CoAP GET) the Event Log Object to get the values of the  LogStart (/20/0/4011)

And we believe there should be:

> 1. An Execute (CoAP POST) operation with a valid arguments is performed by the Server on the LogStart Resource (/20/0/4011) of the Event Log Object
> 2. The Server READs (CoAP GET) the Event Log Object to get the values of the LogStatus (/20/0/4013)

Resource 4011 has only Execute operation defined, so Reads and Writes on it are invalid.

Pass criteria should be updated as well. LogStatus should indicate that log collecting is in progress.

**Comment by hannestschofenig** [comment]
Can you also provide me an updated version of this test case, please?

**Comment by Spongman** [comment]
I don't believe this is fixed. The most recent ETS document https://openmobilealliance.org/release/LightweightM2M/ETS/OMA-ETS-LightweightM2M_INT-V1_2-20231003-A.pdf is still wrong as described above.
