### ISSUE TITLE
Attribute attachment in Discover operation

### ISSUE THREAD

**Issue by cjacquinot** [OpenMobileAlliance/OMA_LwM2M_for_Developers#477]
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* section 5.1.1 Attributes Definitions and Rules
* section 6.3.2 Discover

In the specification it says that:
- an attribute on Object level is extended to Object Instance, Resource and Resource Instance level
- an attribute on Object Instance level is extended to Resource and Resource Instance level
- an attribute on Resource level is extended to Resource Instance level
- It is the closest attribute level existing which prevail

For the next example:
- /3?pmax=5&pmin=1
- /3/0?pmax=3
- /3/0/11?epmin=3
- /3/0/11/0?epmin=6

Is the next discover answer are correct?
- Discover on /3: `< /3>;pmax=5;pmin=1,</3/0>,</3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>,</3/0/6> </3/0/7>,</3/0/8>,</3/0/9>,</3/0/11>,</3/0/16>`
- Discover on /3/0: `</3/0>;pmax=3;pmin=1,</3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>,</3/0/6> </3/0/7>,</3/0/8>,</3/0/9>,</3/0/11>;epmin=3,</3/0/16>`
- Discover on /3/0/11: `</3/0/11>;dim=1;pmax=3;pmin=1;epmin=3,</3/0/11/0>;epmin=6 `

Or should it be:
- Discover on /3: `< /3>;pmax=5;pmin=1,</3/0>,</3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>,</3/0/6> </3/0/7>,</3/0/8>,</3/0/9>,</3/0/11>,</3/0/16>`
- Discover on /3/0: `</3/0>;pmax=3,</3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>,</3/0/6> </3/0/7>,</3/0/8>,</3/0/9>,</3/0/11>,</3/0/16>`
- Discover on /3/0/11: `</3/0/11>;dim=1;epmin=3,</3/0/11/0>;epmin=6 `

Or something else?

**Comment by hannestschofenig** [comment]
This aspect was clarified in the latest specification, v1.2.
