### ISSUE TITLE
Effect of attributes on different assignment levels

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#478]
This is an issue that generated disagreement during the 2019 TestFest in Korea. I believe it applies to both the 1.0 and 1.1 specifications.

Consider the following situation:
1. The DM server executes a Write-Attributes operation on a Resource Path (e.g. `/19/0/0`), setting the `pmin` and `pmax` attributes.
2. The DM server initiates an Observation on the whole Object Instance (e.g. `/19/0`).
3. Let's assume that the contents of the observed Instance does not change through any other means than the same server actually writing the values.

Should any notifications actually be sent in this case? I.e., should the `pmax` attribute set on the Resource be respected when the observation is issued on the whole Object Instance? How would that change if `pmin` and `pmax` attributes would also be set on the Object Instance level, as well as on the Resource level?

**Comment by asoloway64** [comment]
The simple answer to this question "Should any notifications actually be sent in this case?" is no. Reporting criteria can be attached to a resource when that reporting criteria is assigned to the object instance. Reporting criteria assigned to a resource cannot be attached to an object instance. Only those reporting criteria assigned to the observation level will be evaluated when determining whether to generate a notification report.

**Comment by asoloway64** [comment]
For your follow-on conditions of setting the pmin and pmax on the object instance level, yes, a notification would be generated. That is completely independent of the attributes set at the resource instance.

**Comment by kFYatek** [comment]
The test case during which this issue has been discovered:  LightweightM2M-1.0-int-1900 and LightweightM2M-1.1-int-1900
Some of the server teams issued the Observe command on the whole Object Instance (/19/0), so just lowering pmin and pmax attributes was not enough to trigger the notification, the value had to actually change.

**Comment by hannestschofenig** [comment]
Can you send me an updated, corrected version of the test case description?

**Comment by victormsc** [comment]
I apologize if it is the result of a misunderstanding on my part, but I have not managed to understand the conditions that must be met to generate notifications of an "Observe" operation when that operation specifies an object or object instance.

I have read the main documents for the specification, the transport bindings documents, and the Enabler Test Specification documents available for the last and/or previous versions of the specification but I have not been able to reach a firm conclusion.

My first doubt refers to the "Observe" operation (not the "Observe-Composite") and more specifically to the case where the operation does not specify its own observation attributes but depends on notification attributes specified by "Write-Attributes" operations or default values ​(in the case of `pmin` and/or `pmax`).

In the first paragraph of section 6.4.2 (Notify Operation) of the 1.2 version of the specification one can be read:

> "The "Notify" operation is sent from the LwM2M Client to the LwM2M Server during a valid observation on an Object, Object Instance or Resource. The "Notify" operation MUST be sent when all conditions (i.e. Minimum Period, Maximum Period, Greater Than, Less Than, Step) are met. Those conditions are either "Observation Attributes" sent as parameters or attributes attached at the level of the "Observe" operation."

But the notification attributes can't be attached at the level of object or object instance but only at the level of resource (or resource instance). Maybe, in the case of an "Observe" without "Observation Attributes" parameters, the meaning of this paragraph is:

**S1:**
If an "Observe"  does not include "Observation Attributes" parameters, the "Notify" operation MUST be sent when all the conditions defined by attributes attached to any resource observed by the "Observe" operation are met.

However, the responses from @asoloway64 say:

**S2:** 
> "... Only those reporting criteria assigned to the observation level will be evaluated when determining whether to generate a notification report." 
...
> "For your follow-on conditions of setting the `pmin` and `pmax` on the object instance level, yes, a notification would be generated. That is completely independent of the attributes set at the resource level."

 (To compare S1 and S2, I have supposed that the terms "conditions" and "reporting criteria" are equivalent).

In the first, the attributes attached at the resource level define the conditions that must be satisfied to send a "Notify"  while in the second are those assigned at the observation level.

Please, could you tell me which of these two statements (S1 or S2) is true, if any?

Thank you very much.

**Comment by sbernard31** [comment]
We get a pretty much similar question on Wakaama project : https://github.com/eclipse/wakaama/issues/636.

And so I fall on this old issue.

I must confess that I'm confused by the answer. 

> The simple answer to this question "Should any notifications actually be sent in this case?" is no. Reporting criteria can be attached to a resource when that reporting criteria is assigned to the object instance. Reporting criteria assigned to a resource cannot be attached to an object instance. Only those reporting criteria assigned to the observation level will be evaluated when determining whether to generate a notification report.

When a Observation relation is established at object instance, if 1 of its resources changes then  a notification is send. 
```
resource changed --> object instance changed --> object instance notification sent.
```
With reporting criteria this could looks like : 
```
resource changed --> apply reporting criteria at resource level --> object instance changed --> object instance notification sent.
```
(At least some have understood it like that : https://github.com/eclipse/wakaama/issues/636#issuecomment-1031240868)

With your answer I understand the reporting criteria is only used when the attachment level matches observation level. 
I mean if the reporting criteria is attached to resource level it is only applied to observation relation at resource level.
So this is more : 
```
resource changed --> object instance changed --> apply criteria at object instance level --> object instance notification sent.
```

As all reporting criteria can only be attached to resource (See [Table: 5.1.2.-2 <NOTIFICATION> class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes))

That means that attribute will only be used for Observation established at Resource level ? 
So pmin/pmax/greater/ ... can not be used on object or object instance observe relation? 

> For your follow-on conditions of setting the pmin and pmax on the object instance level, yes, a notification would be generated. That is completely independent of the attributes set at the resource level.

This time I'm confused because it seems that you are using the assignation level as it was an attachment level (the level where the criteria is applied)

I probably totally missed something but could you clarify this ?

**Comment by dnav** [comment]
**Disclaimer:** This is my personal view, not an OMA one as the matter was not yet discussed in an OMA WG meeting.

> So this is more :
>
> ```
> resource changed --> object instance changed --> apply criteria at object instance level --> object instance notification sent.
> ```

We have the same understanding.

> As all reporting criteria can only be attached to resource (See [Table: 5.1.2.-2 class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes))
>
> That means that attribute will only be used for Observation established at Resource level ?  
> So pmin/pmax/greater/ ... can not be used on object or object instance observe relation?

Actually, there are two "types" of attributes:
1. `gt`, `lt`, `step`, and `egde` which can be attached only at the Resource or Resource Instance level
2. `pmin`, `pmax`, `epmin`, `epmax`, `con`, and `hqmax` which can be attached at any level

You can the second "type" of attributes for Observations at the Object or Object instance level. I think this is what you missed.

In the original question, you have:
```
19
 +- 0
     +- 0   pmin=10, pmax =60
     +- 1
```

An Observation on `/19/0` does not have any attribute to consider.

In the follow-up question, you have:
```
19
 +- 0       pmin=30
     +- 0   pmin=10, pmax =60
     +- 1
```

An Observation on `/19/0` must consider a 30 seconds minimum period.

Regards,

**Comment by sbernard31** [comment]
@dnav thx very much for the answer :pray: 

> Actually, there are two "types" of attributes:
>
>    gt, lt, step, and egde which can be attached only at the Resource or Resource Instance level
>    pmin, pmax, epmin, epmax, con, and hqmax which can be attached at any level
>
> You can use the second "type" of attributes for Observations at the Object or Object instance level. I think this is what you missed.

I maybe missed that but I didn't find any version of the specification where `pmin`, `pmax`, `epmin`, `epmax`, `con`, and `hqmax` can be attached to any level :
- [LWM2M-v1.2§Table: 5.1.2.-2 <NOTIFICATION> class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes)
- [LWM2M-v1.1.1§Table: 5.1.2.-2 <NOTIFICATION> class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-512-2-lessNOTIFICATIONgreater-class-Attributes)
- [LWM2M-v.1.0.2§Table 4: <NOTIFICATION> class Attributes](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf)

Unless there is a confusion between assignability and attachment ? 
For now, I understand that : 
-   observation level : is the level (object/object instance / ...) where the notification relationship is established.
-   assignation level : is the level (object/object instance / ...) on which the write attribute is done.
-   attachment level : is the level (object/object instance / ...) on which the attribute is really applied.
Do you understand it in a same way ?

**Comment by dnav** [comment]
I'm so used to these tables that I totally forgot about this "attachment" column. Now I understand your confusion. And I'm no longer sure of the correct intent.

Let's wait for the OMA WG clarification...

**Comment by sbernard31** [comment]
@hannestschofenig, I don't get why this is closed.

Could you clarify this point ? or give a link to this clarification ? :pray:

**Comment by kFYatek** [comment]
@sbernard31 The [latest (1.2) spec says in section 6.4.2](https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#6-4-2-0-642-Notify-Operation) that:

> The "Notify" operation is sent from the LwM2M Client to the LwM2M Server during a valid observation on an Object, Object Instance or Resource. The "Notify" operation MUST be sent when all conditions (i.e. Minimum Period, Maximum Period, Greater Than, Less Than, Step) are met. Those conditions are either "Observation Attributes" sent as parameters or **attributes attached at the level of the "Observe" operation.**

This (but this is just my personal opinion, not approved by the working group at the moment) seems to strongly suggest that all the attributes below the level for which the Observe operation is issued shall be ignored.

**Comment by sbernard31** [comment]
Some news about how we decide to implement write attributes behavior on classic observe (ObserveComposite not yet implemented) in Leshan 2.x (LWM2M v1.1.x) : 


**We chose to implement :** 
```
resource changed --> object instance changed --> apply criteria at object instance level --> object instance notification sent.
```
Because : 
 - far most easier to implement 
 - match @asoloway64's  comment :  https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/478#issuecomment-539779037
 - match @dnav's  comment: https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/478#issuecomment-1031562570
 - match @kFYatek's comment : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/478#issuecomment-1268595463

**Confusion about :** 
> That means that attribute will only be used for Observation established at Resource level ?
> So pmin/pmax/greater/ ... can not be used on object or object instance observe relation?
>
>>    For your follow-on conditions of setting the pmin and pmax on the object instance level, yes, a notification would be generated. That is completely independent of the attributes set at the resource level.
>
> This time I'm confused because it seems that you are using the assignation level as it was an attachment level (the level where > the criteria is applied)

:point_up:  is solved by https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/539#issuecomment-1973246531
