### ISSUE TITLE
Create or Bootstrap-Write operation with Optional Executable resources

### ISSUE THREAD

**Issue by cjacquinot** [OpenMobileAlliance/OMA_LwM2M_for_Developers#479]
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* 6.3.6 Create Operation
* 6.1.7.5 Bootstrap-Write Operation

Specification says that:
- Payload of create operation should be in TLV, senML CBOR or senML JSON
- To set optional resources on the object created, server must provide value of those resources
- If optional resources are not in the Create operation payload, they should not be set
The same behaviour is explain for Bootstrap-Write operation

I can not see possibility to add Optional Executable resources during the Create / Bootstrap-Write operation in TLV, senML CBOR or senML JSON.
So, how could we set Optional Executable resources when we created an object?

Tests case:
* The bootstrap-server wants provide a Server with Disable (/1/x/4) optional executable resource.
* The server wants create a new Software component with Activate (/14/x/3) and Deactivate (/14/x/4) optional executable resources

**Comment by hannestschofenig** [comment]
You cannot create an executable resource. Why would you like to create an executable resource?

**Comment by hannestschofenig** [comment]
The question is: Should I be able to create an executable resource (as a Server)? 
Our answer would be: No, because you don't know what value to put in there.

**Comment by cjacquinot** [comment]
I don't want put a value in an executable resource (except if the resource can have parameters). I would like to be able to use it after the creation of the object. Like when I make a Bootstrap-Write on a server, I would like to be able to use the Disable (/1/x/4) optional executable resource.

**Comment by sbernard31** [comment]
This is no really the job of a Bootstrap-Server to do that. :thinking: 

> The LwM2M Bootstrap-Server is used to provision the LwM2M Client with the information required to contact the LwM2M Server(s).

But for the particular case of /1/x/4 at bootstrap time, what would be the purpose ? delay the registration after the bootstrap ?
If yes, you could maybe consider `Initial Registration Delay Timer` resource (1/x/14) ?

About the software component, as previously said it sounds not really a job for a bootstrap server.

**Comment by hannestschofenig** [comment]
Executable resources are never created. There is no default value. Whether you report it in a discovery, it is up to the client.
