### ISSUE TITLE
URI scheme for NB-IoT Non-IP Data Delivery

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#482]
In `OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A`, several URI schemes are defined as normative for various transports:

* `coap://` and `coaps://` for UDP
* `coap+tcp://` and `coaps+tcp://` for TCP
* `lorawan://` for LoRaWAN

Additionally, in issue #459, @hannestschofenig suggested usage of the [`tel:` scheme](https://tools.ietf.org/html/rfc3966) for SMS binding, even though this is not explicitly mentioned in any LwM2M-related specification.

This leaves the NIDD over 3GPP CIoT the only transport without an URI scheme specified in any way. And this seems to be necessary - the Security object does not specify any resource that specifies the binding, and according to answers in issue #459, multiple Security object instances may correspond to a single Server object instance.

### Solution proposal

What we are provisionally using in the AVSystem client, is `coap+nidd://` or `coaps+nidd://`, by extension of the `coap[s]+tcp://` / `coap[s]+ws://` convention. Since there are no hosts in the 3GPP CIoT NIDD architecture, the host portion is optional. For example:

* `coap+nidd:///` - empty Uri-Path and Uri-Query
* `coap+nidd:///uri/path` - two Uri-Path options will be sent, `uri` and `path`
* `coap+nidd:///?uri=query` - one Uri-Query option will be sent, `uri=query`

Sections D.2 and D.3 of the Transport TS seem to suggest using Uri-Host for routing information, so optionally it might be a good idea to also support it:
* `coap+nidd://example.com/` - Uri-Host will be set to `example.com`
* `coaps+nidd://example.com/hello?oma=lwm2m`, Uri-Host = `example.com`, Uri-Path = `hello`, Uri-Query = `oma=lwm2m`, additional DTLS encryption

**Comment by hannestschofenig** [comment]
This is a very good point and I believe we discussed this in OMA at some point in time. I will ask around to see what others have been doing. Clearly, we have to register a URI scheme -- we cannot just make something up.

**Comment by jaimejim** [comment]
Adding `nidd` might be something to be taken back to CoRE WG? @chrysn 
https://datatracker.ietf.org/doc/html/draft-amsuess-core-transport-indication-03

**Comment by cabo** [comment]
A discussion has started at https://mailarchive.ietf.org/arch/browse/core/?gbt=1&q=NIDD

**Comment by hannestschofenig** [comment]
The registrations of these identifiers is still pending...
