### ISSUE TITLE
Conflict between resources /3/0/11 and /3/0/12 description

### ISSUE THREAD

**Issue by AButenko** [OpenMobileAlliance/OMA_LwM2M_for_Developers#483]
Document: OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
Section: E.4 LwM2M Object: Device

For me, there is conflict between resources /3/0/11 and /3/0/12 description.
Description for /3/0/11:
...
 When an error associated with a Resource Instance is no longer present, that Resource Instance is deleted. When the single existing error is no longer present, theLwM2M Client returns to the original no error state where Instance 0 has value 0.
...
Description for /3/0/12:
Delete all error code Resource Instances and create only one zero-value error code that implies no error, then re-evaluate all error conditions and update and create Resources Instances to capture all current error conditions.

Description of /3/0/11 already requires to have actual error code in any moment of the device lifetime. What is the sense in existence of /3/0/12 resource?

**Comment by hannestschofenig** [comment]
Resource "Reset Error Code" (12) allows you to manually reset the error indication in resource "Error Code" (11). 

As you correctly cite, if the error goes away for whatever reason that the code indicated in resource 11 may disappear automatically. 

A completely separate question is obviously: Does it make sense to clear the error codes without fixing the underlying problem? Hard to say. Depends on what you are doing to address the problems overall.

**Comment by AButenko** [comment]
Thanks for clarification

**Comment by AButenko** [comment]
Client can just exclude /3/0/12 as this resource is optional.
