### ISSUE TITLE
Add example for Object Link encoded in SenML CBOR in the LwM2M-Specification

### ISSUE THREAD

**Issue by ZeTo12** [OpenMobileAlliance/OMA_LwM2M_for_Developers#484]
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* Section 7.4.6 SenML CBOR

In this section the specification defines how the payload of "Read" and "Write" requests are encoded in SenML CBOR. There is currently only one example that shows how the response looks like for the Device Object Read-Request.
Please add another example that shows how a Object Link is encoded in SenML CBOR. Maybe you can use the example in
* Section 7.4.5 SenML JSON
* Table 7.4.5. -4 SenML JSON payload returned from example request to Object 65 of the LwM2M example seen on Figure: C.-1 Object link Resource simple illustration (Read /65/0)

In this section there is currently only one sentence about Object Links.

> The object links use a string map key "vlo" also in SenML CBOR representation.

Can you specify the use of Object Links more precise?

Thank you.

**Comment by dnav** [comment]
The following SenML JSON payload:

```json
[{"n":"/65/0/0/0","vlo":"66:0"}]
```

would be in SenML CBOR:

```
81                          # array(1)
   A2                       # map(2)
      00                    # unsigned(0)
      69                    # text(9)
         2F36352F302F302F30 # "/65/0/0/0"
      63                    # text(3)
         766C6F             # "vlo"
      64                    # text(4)
         36363A30           # "66:0"
```

or in diagnostic notation:

```
[{0: "/65/0/0/0", "vlo": "66:0"}]
```

Regards,
