### ISSUE TITLE
Was the request for a SenML Label for Object Links ('vlo') answered?

### ISSUE THREAD

**Issue by ZeTo12** [OpenMobileAlliance/OMA_LwM2M_for_Developers#485]
* OMA-ERELD-LightweightM2M-V1_1_1-20190617-A_full
* 5.2 IANA Considerations

The document OMA-ERELD-LightweightM2M-V1_1_1-20190617-A_full states in section 5.2 IANA Considerations the following:

> For LwM2M v1.1: OMA is requesting IANA to register a new SenML Label for LwM2M object links in the "Sensor Measurement Lists (SenML) Parameters" registry, "SenML Labels" sub-registry:
* Name: Object Link Value
* Label: vlo
* JSON type: String
* XML type: string
* Reference: LwM2M TS v1.1
No additional considerations for v1.1.1 were identified.

How far is this request? Is there a number that corresponds to a 'vlo' in SenML CBOR?

**Comment by dnav** [comment]
FYI, "vlo" is now registered.

https://www.iana.org/assignments/senml/senml.xhtml#senml-labels

**Comment by akeranen** [comment]
FYI; there is no "vlo" CBOR number but a string key is used for that instead (see [SenML RFC Sec 6](https://www.rfc-editor.org/rfc/rfc8428#section-6) for details)
