### ISSUE TITLE
Arguments for "Execution" operation allow include empty spaces?

### ISSUE THREAD

**Issue by esheyuq** [OpenMobileAlliance/OMA_LwM2M_for_Developers#487]
LwM2M Specification: OMA-TS-LightweightM2M-V1_0_2

In 5.4.5 Excetion section,

In using ABNF, the syntax of the arguments, and arguments list is given as follows:
 
```
arglist = arg *( "," arg )
arg = DIGIT / DIGIT "=" "'" *CHAR "'"
DIGIT = "0" / "1" / "2" / "3" / "4" / "5" / "6" / "7" / "8" / "9"
CHAR = "!" / %x23-26 / %x28-5B / %x5D-7E
```
This ABNF not define empty space.

My question is does empty space allow in "arguments" like below,
```
0, 1, 2
7, 0='https://www.omaspecworks.org'
7,0 = 'https://www.omaspecworks.org'
```

**Comment by sbernard31** [comment]
My understanding is : "empty space are not allowed".
Meaning that some examples would be incorrect. (This is also true for the specification 1.1)

If I'm right, this is not limited to "Execute arguments".  There are "white spaces error" in several examples of the spec where ABNF is used (mainly Core Link format exemples). 
(e.g : **§5.4.2 Discover** `</3/0>;pmax=60,</3/0/1>, <3/0/2>, </3/0/3>, </3/0/4>,`)

This leshan issue talk about that : https://github.com/eclipse/leshan/issues/775#issuecomment-556007727

(I'm a Leshan committer but I'm not part of the OMA working group, so you should wait for OMA confirmation)

**Comment by dnav** [comment]
We discussed this issue in the OMA DMSE group, @sbernard31 's answer is correct: white spaces are not allowed in the Execute arguments encoding.
