### ISSUE TITLE
"Send" may be a Non-Confirmable CoAP message

### ISSUE THREAD

**Issue by higebu** [OpenMobileAlliance/OMA_LwM2M_for_Developers#488]
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``: OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A
* Section of the document, ``(e.g. section: 6.2)``: 6.4. URI Identifier & Operation Mapping

"Send" may be a Non-Confirmable CoAP message like "Notify". Because "Send" is used by the LwM2M Client to send data to the LwM2M Server without explicit request by that Server. If we have very large number of "Send" messages, we don't want to ack to the messages to save our service.

References:
* OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A 6.4.6 Send Operation:
 >The "Send" operation is used by the LwM2M Client to send data to the LwM2M Server without explicit request by that Server.

* OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A 6.4. URI Identifier & Operation Mapping:
>All the LwM2M operations using CoAP layer MUST be Confirmable CoAP messages, except as follows:
>* "Notify" which may be a Non-Confirmable CoAP message
>* Triggering an execution on a resource can be a Non-Confirmable CoAP message

**Comment by hannestschofenig** [comment]
Thanks for raising this issue. We will add the "Send" message to the list of messages that can be send as non-confirmable messages in the next bugfix release.

**Comment by higebu** [comment]
Thank you!
