### ISSUE TITLE
Clarification about ”singular Resouces“ in data format sections

### ISSUE THREAD

**Issue by ezhaboy** [OpenMobileAlliance/OMA_LwM2M_for_Developers#489]
* Name, version and date of the document: OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A
* Section of the document: 7.4.1. Plain Text, 7.4.2. Opaque, 7.4.3. CBOR

> The plain text format is used for "Read" and "Write" operations on singular Resources.
> The opaque format is used for "Read" and "Write" operations on singular Resources.
> The Concise Binary Object Representation format is used for "Read" and "Write" operations on singular Resources.

7.4.1. Plain Text, 7.4.2. Opaque, 7.4.3. CBOR describes these formats are used for "Read" and "Write" operations on **singular** Resources. 

From LwM2M TS 1.1.x, Resource Instance ID can be a part of request path, are plain text, opaque and CBOR formats applicable for "Read" and "Write" operations on Resource Instance of multiple Resource, for example READ /3/0/7/0, not limited on Single Resource.

**Comment by sbernard31** [comment]
I think you're correct.

Maybe the same wording as [SenML JSON](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#7-4-5-0-745-SenML-JSON) could be used ? 

> This format MAY be used ... for transporting **a single value of a Resource.**

**Comment by dnav** [comment]
We discussed this issue in the OMA DMSE group. Indeed "plain text", "opaque", and "CBOR" formats are applicable for operations targeting a Single Resource or a Resource Instance.

Note that this was clarified in the LwM2M v1.2 TS. We are in the last stages of finalizing the release of the specification and the objects.
