### ISSUE TITLE
Read object with opaque type resources

### ISSUE THREAD

**Issue by janis-mt** [OpenMobileAlliance/OMA_LwM2M_for_Developers#491]
TS version: OMA-TS-LightweightM2M-V1_0_2-20180209-A

I'm interested about handling of case where server reads whole object that has multiple resources, one of which has type opaque.

Lets say you have object with resources:
1. Type: "Integer", name: "counter"
2. Type: "Opaque", name: "binary data"
3. Type: "Time", name: "event_time" 

Now if server issues a "Read" operation and sets only "Object ID" to read all instances and all resources, what data format could client use to reply?

Could client reply and use TLV?

Paragraph 6.4.2 Opaque states: "The opaque format is used for “Read” and “Write” operations on singular Resources". This would imply that you can't use opaque data format, but we have resource type "Opaque". As I understand the two are different concepts.

Paragraph 6.4.3 TLV has many examples, but none with resource type "Opaque". Is it correct to just put binary data or resource with type "Opaque" into TLV data element?

**Comment by sbernard31** [comment]
As I understand the specification :

- **Plan text** can only be used for any single resource.
- **Opaque** can only be used for opaque single resource.
- **TLV**(only format which MUST be supported by client) can be used for everything. (except for historical notification)
- **JSON** can be used for everything.

To better understand you should have a look at **§Appendix C.Data Types**

> Could client reply and use TLV?

It MUST reply with TLV or JSON. (the CoAP Content-Format option which MUST be specified)

**Comment by hannestschofenig** [comment]
The answer provided by Simon is correct.
