### ISSUE TITLE
Firefox Add-On

### ISSUE THREAD

**Issue by chrmel** [OpenMobileAlliance/OMA_LwM2M_for_Developers#492]
Since it is still online and being promoted on the Wiki, are there plans to update the Firefox-Extension for the devKit?
If not is there any replacement or similar tool?

Thank you, 
Christian

**Comment by jpradocueva** [comment]
Hi Christian, good point.
Let me allocate to Hannes and Matt the chairs of DMSE (develop LwM2M specs) and IPSO (own the LwM2M Registry) your question,

**Comment by jaimejim** [comment]
Checking with @mkovatsc on this.

**Comment by hannestschofenig** [comment]
Mathias Kovatsch, the developer of the extension, indicated that the code has to be re-worked given the changes Firefox and other browser vendors made in their treatment of apps. As a possible design, Mathias suggests to use Postman (using a JavaScript framework called Electron).

We currently do not have a volunteer to work on such a code update but if you have time and interest, Mathias would be happy to help you. Please drop us a note, if you are interested.

**Comment by mkovatsc** [comment]
Just FYI: A first step would be to create a custom tool based on Electron, which should provide an easy transition (given there is some Electron dev experience). A Postman integration would be an ultimate goal, but more suitable for the generic Copper CoAP user-agent, on which the OMA DevKit is based.
