### ISSUE TITLE
Add "KB" units for "Memory Total" with ID 21 in LWM2M_Device-v<all>.xml

### ISSUE THREAD

**Issue by wangju1111** [OpenMobileAlliance/OMA_LwM2M_for_Developers#493]
Add "KB" units for "Memory Total" with ID 21, for LWM2M_Device-v1_0.xml, LWM2M_Device-v1_0_1.xml, LWM2M_Device-v1_0_2.xml LWM2M_Device-v1_0_3.xml, and LWM2M_Device-v1_1.xml.

Reason: it is specified in "Description" the unit is based on KB.

**Comment by hannestschofenig** [comment]
KB is not a registered unit in the SenML registtry and hence we didn't use it. Here is the SenML registry: https://www.iana.org/assignments/senml/senml.xhtml

Instead, we indicated the unit in the description field. Note that one kilobyte is 1000 bytes whereas KiB (kibibyte) is 1024 bytes. We will add a note to the object that the kilobyte here refers to 1000 bytes to improve clarity.
