### ISSUE TITLE
Clarification of Multiple-Instance Resources with no instances

### ISSUE THREAD

**Issue by sbertin-telular** [OpenMobileAlliance/OMA_LwM2M_for_Developers#494]
In OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A table 5.1.2.-1 the Dimension attribute has a range of 0-255. A value of 0 implies that a resource exists, but has no instances.

Section 7.4 states:
The LwM2M Client MUST support plain text, opaque, and CoRE Link data formats and it SHOULD support at least one of SenML CBOR or SenML JSON data formats. In addition, a LwM2M Client MAY choose to support other data formats. LwM2M Clients supporting LwM2M TS 1.1 or newer SHOULD NOT use the legacy TLV or JSON formats.

SenML (RFC8428) section 4.2 requires a Value or Sum. Values are represented using basic data types, no arrays or maps.

For a Bootstrap-Read, Bootstrap-Write, Read, Write, Create, Read-Composite, or Write-Composite using the SenML CBOR or SenML JSON formats it does not appear possible to represent a Multiple-Instance Resources with no instances as there is no value to provide.

I would like clarification as to how this should be handled. I see three options.
1. Multiple-Instance Resources must have at least one instance.
2. TLV format must be used for such resources with no instances.
3. An example showing how a Multiple-Instance Resources with no instances should be represented.

**Comment by dnav** [comment]
We discussed this issue in the OMA DMSE group.

The operations Bootstrap-Read, Read, Write, Read-Composite, and Write-Composite are conveying Resource values. Thus the Multiple Resource with no instance is not part of the payloads and there is no need to represent it.

For the Bootstrap-Write and the Create operations, it is indeed not possible to request the creation of an optional Multiple-Instance Resource with no instance. Note that there is the same limitation for optional Executable Resources. However we did not have an usecase for this.

Note that the LwM2M v1.2 TS clarifies the behavior of the LwM2M Client regarding the optional Resources during a Bootstrap-Write or Create operation. We are in the last stages of finalizing the release of the specification and the objects.

**Comment by sbertin-telular** [comment]
If I am understanding your response correctly, a Read of a Multiple Resource with no instance would return a response code of 2.05 Content with no payload. If it was a Read of the entire Object Instance, nothing would be included in the response for the Multiple Resource. Is that correct?

**Comment by sbernard31** [comment]
>  If I am understanding your response correctly, a Read of a Multiple Resource with no instance would return a response code of 2.05 Content with no payload.

For SenML JSON you mean : an empty string or an empty array ?  (or both ?)

**Comment by sbertin-telular** [comment]
> > If I am understanding your response correctly, a Read of a Multiple Resource with no instance would return a response code of 2.05 Content with no payload.
> 
> For SenML JSON you mean : an empty string or an empty array ? (or both ?)

I mean no content in the payload, although your interpretation might be correct also. I'm trying to get clarification on what it should be.

**Comment by sbernard31** [comment]
@mkgillmore, I guess if you close this issue that means that OMA clarify this ? could you share what should be the right behavior ?
