### ISSUE TITLE
Different pmax attribute definitions in 1.1 and 1.0.2

### ISSUE THREAD

**Issue by reenlam** [OpenMobileAlliance/OMA_LwM2M_for_Developers#495]
LwM2M 1.1 specification introduced ``pmax`` attribute definition change comparing to previous LwM2M specifications. This change remains until the latest version: ``OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A``.

The change I mean occurred in the ``<NOTIFICATION> class Attributes`` table.
In ``Notes`` under the ``Maximum Period`` row, there had been a sentence (in ``OMA-TS-LightweightM2M-V1_0_2-20180209-A`` version):
The maximum period parameter MUST be not smaller than the minimum period parameter otherwise it will be ignored for the Resource to which such inconsistent Timing Conditions applied.

In all newer versions from ``OMA-TS-LightweightM2M_Core-V1_1-20180612-C`` to ``OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A``:
The maximum period parameter MUST be greater than the minimum period parameter otherwise pmax will be ignored for the Resource to which such inconsistent timing conditions are applied.

In my opinion, this change is bad, because it unables a server to order a client that notifications must be sent exactly every N seconds.
What is more, all LwM2M 1.1 clients I have used still support setting pmax equals to pmin.

I hope it will be changed back to:
The maximum period parameter **MUST be not smaller** than the minimum period parameter...

Alternatively, I suggest to write:
MUST NOT be smaller than the minimum period...
or:
MUST be greater than or equal to the minimum period...

**Comment by hannestschofenig** [comment]
We updated the definition of the pmax attribute in the v1.2 specification, which will be released soon. I believe it will address.
