### ISSUE TITLE
Import of OEditor does not work

### ISSUE THREAD

**Issue by wwadepohl** [OpenMobileAlliance/OMA_LwM2M_for_Developers#497]
The import of a previous sexported object from https://devtoolkit.openmobilealliance.org/OEditor/MOUpload results in an error:
System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\!Websites\devtoolkit.openmobilealliance.org\Apps\OEditor\Log\DDF\20200714_104045-38915179-e224-4ff0-be30-67dc5426103e.xml'.

**Comment by seanmcilroy29** [comment]
@wwadepohl - Could you outline the steps you took to create the error

**Comment by wwadepohl** [comment]
I created a new object, exported it into the zipped xml, unzipped it and tried to import the unzipped xml

**Comment by SvanteAlnas** [comment]
Thanks for reporting the issue. There was an change of the folder structure on the server that was incorrect but now it has been fixed. Now it should work again.

**Comment by jpradocueva** [comment]
@wwadepohl please feel free to close the issue if it has been resolved for you. Thanks for reporting the problem.

**Comment by wwadepohl** [comment]
Thank you for quick response
