### ISSUE TITLE
lwM2M Objcet 12 WLAN Connectivity Error

### ISSUE THREAD

**Issue by wwadepohl** [OpenMobileAlliance/OMA_LwM2M_for_Developers#498]
http://www.openmobilealliance.org/tech/profiles/LWM2M_WLAN_connectivity4_V1_0_1.xml

The Names of the resources 41 and 42 are not correct. I assume that name of resource 41 must be "Multicast Packets Received" according to the Description

**Comment by wwadepohl** [comment]
Also thers is in resource 44 the resource number doubled in the name field

**Comment by wwadepohl** [comment]
Also thers is in resource 44 the resource number doubled in the name field
In Resource 9 Channel the description is nonsense

**Comment by wwadepohl** [comment]
Also thers is in resource 44 the resource number doubled in the name field
In Resource 9 Channel the description is nonsense

**Comment by seanmcilroy29** [comment]
@wwadepohl - These issues have been resolved in v1.1, which will be published in due course

**Comment by hannestschofenig** [comment]
Object will be released at the time of the LwM2M v1.2 specifications even though it is not part of the LwM2M v1.2 TS. 
The release of the corrected objects will happen any day now.
