### ISSUE TITLE
Question about Network Bearer in Connectivity Monitoring Network

### ISSUE THREAD

**Issue by wwadepohl** [OpenMobileAlliance/OMA_LwM2M_for_Developers#499]
http://www.openmobilealliance.org/tech/profiles/LWM2M_Connectivity_Monitoring-v1_2.xml

Is ther an identifier for LTE-M bearer?

**Comment by mojanm** [comment]
Resource 0, Network Bearer, identifies the type of bearer used for LwM2M connection. As from 3GPP perspective Cat-M1and M2 are LTE categories this resource value should be 5 or 6 when LTE Cat-M is used

**Comment by hannestschofenig** [comment]
We discussed this issue in the OMA DMSE group and decided that there is no need to differentiate between categories of LTE bearers.
