### ISSUE TITLE
Empty <Operations> values for Server object resources /1/X/13 .. 1/X/20 

### ISSUE THREAD

**Issue by pelya** [OpenMobileAlliance/OMA_LwM2M_for_Developers#500]
The definition of Server object /1 at OMA-SUP-XML_LWM2M_Server-V1_1_1-20190617-A.xml has empty \<Operations\> tags for resources from /1/X/13 to /1/X/20. I suppose they all should have "RW" permissions, but you at least have to specify "R" permission, otherwise the only command the server is allowed to do to these resources is Discover.

Just look what this broken object definition did to Leshan:
![92030875-58ca6280-ed70-11ea-9dcb-9296cef4f37f](https://user-images.githubusercontent.com/155328/92270009-ef705e00-eeed-11ea-8a42-db4359900564.png)

Wakaama developers assume these resources have "RW" permissions:
https://github.com/eclipse/wakaama/blob/master/examples/client/object_server.c#L36

Attaching fixed .xml file
[LWM2M_Server-v1_1_1.xml.zip](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/files/5176215/LWM2M_Server-v1_1_1.xml.zip)

**Comment by hannestschofenig** [comment]
Thanks for bringing this topic to our attention. This bug has been fixed with LwM2M v1.2 where the object definition has been updated. We are in the last stages of finalizing the release of the specification and the objects. You will see the corrected files very soon
