### ISSUE TITLE
FOTA PUSH - Data-format & Data-type confusion

### ISSUE THREAD

**Issue by attkat** [OpenMobileAlliance/OMA_LwM2M_for_Developers#501]
Hi,

in the last couple of months, we have been trying to implement FOTA PUSH method with Zephyr LWM2M stack. Unfortunately, we have been facing a confusion regarding different data-formats and data-types. Our goal is to clarify, what is the correct implementation FOTA PUSH based on LWM2M technical specification 1.0. Please allow me to describe our understanding of the problem.

Data-format is the way, how LWM2M clients and LWM2M servers exchange data. It can be plain text, Opaque, TLV and JSON.

Data-type is the type of a specific resource. It can be a String, Integer, Opaque, etc. Data-type is defined in the XML format of the resource, for instance in http://www.openmobilealliance.org/tech/profiles/LWM2M_Firmware_Update-v1_0_3.xml .

According to LWM2M technical specification 1.0 an LWM2M client must support only TLV data-format. All other formats are not obligatory. ( http://www.openmobilealliance.org/release/LightweightM2M/V1_0_1-20170704-A/OMA-TS-LightweightM2M-V1_0_1-20170704-A.pdf )

On one hand, our used LWM2M Server offers for the Resource 5/0/0 exclusively opaque data-format and opaque data-type.

On the other hand, Zephyr LWM2M stack offers for the Resource 5/0/0 exclusively TLV data-format and opaque data-type.

We would like to clarify, which of the above implementations is compliant with LWM2M technical specification 1.0?

Thank you and best regards,
Attila

**Comment by sbernard31** [comment]
AFAIK, LWM2M v1.0.x specification says  : 
>The LwM2MServer MUST support all dataformats. The LwM2MClient MUST support the TLV data format.In addition a LwM2MClient MAY choose to support other dataformats in the table below i.e., JSON, plain text and opaque

So my understanding : 
 - your LWM2M server is not compliant because it should be able to use all format for this resource. (in practice for interoperability it should at least support TLV)
- your client support TLV and so is compliant.

**Comment by hannestschofenig** [comment]
Simon is correct regarding the interoperability requirements.
