### ISSUE TITLE
Error about Certificate Usage Resource ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#503]
I'm not sure but reading [LightweightM2M_Core#E1-LwM2M-Object-LwM2M-Security](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.html#13-1-0-E1-LwM2M-Object-LwM2M-Security) says : 
> The Certificate Usage Resource specifies the semantic of the certificate or raw public key stored in the Server Public Key Resource

But in [LightweightM2M_Transport-V1_1#5-2-8-3-0-5283-X509-Certificates](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.html#5-2-8-3-0-5283-X509-Certificates) : 
> The information stored in the "Public Key or Identity" Resource depends on the Certificate Usage Resource, as discussed in Section 5.2.8.7. Certificate Usage Field. If the Certificate Usage Resource is missing this Resource MUST be used to store the X.509 certificate of the TLS/DTLS client in a DER encoded binary format. This backwards compatibility mode matches the semantic of value 3 ("domain-issued certificate") in the Certificate Usage Resource.

One say it's about  **Server Public Key Resource**, the other seems to says it's about **Public Key or Identity** resource ?
Is it a bug or I didn't  understand something ?

**Comment by hannestschofenig** [comment]
This is a bug, as mentioned in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/502

**Comment by hannestschofenig** [comment]
This issue has been resolved by LwM2M v1.2: 
http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/
