### ISSUE TITLE
Missing resources in Software management XML

### ISSUE THREAD

**Issue by DunderRoffe** [OpenMobileAlliance/OMA_LwM2M_for_Developers#504]
Hi,

While implementing support for Object 9 i found a possible issue:

In the release http://openmobilealliance.org/release/LWM2M_SWMGMT/V1_0_1-20200616-A/
These resources are specified in the PDF but **not** in the XML:
* 16 Status Reason
* 17 Software Component Link
* 18 Software Component tree length

Link to PDF http://openmobilealliance.org/release/LWM2M_SWMGMT/V1_0_1-20200616-A/OMA-TS-LWM2M_SwMgmt-V1_0_1-20200616-A.pdf
Specifically in Section 6.LwM2MObject: Software Management 

Link to XML (TXT) http://openmobilealliance.org/release/LWM2M_SWMGMT/V1_0_1-20200616-A/OMA-SUP-XML_LWM2M_Software_Management-V1_0_1-20200616-A.txt

**Comment by sbernard31** [comment]
The XML file seems also incomplete in [**lwm2m-registry**](https://github.com/OpenMobileAlliance/lwm2m-registry) : see [9.xml](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/9.xml).

**Comment by sbernard31** [comment]
@DunderRoffe, by the past for model issue I get more success by opening an issue directly at : https://github.com/OpenMobileAlliance/lwm2m-registry/issues.

Maybe it's worth to open the issue there (and eventually linked this one)

**Comment by seanmcilroy29** [comment]
@sbernard31 See PR - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/475 that relates to this issue

**Comment by hannestschofenig** [comment]
Problem is known and David has been assigned to update the specification as well as the object definition

**Comment by dnav** [comment]
The XML files and the TS for the Software Management related Objects are indeed not in sync. We are addressing this issues in a future release of the TS.

The 2020-06-16 release was an editorial one due to the OMA internal process of converting the source files to a new format.

**Comment by DunderRoffe** [comment]
Thank you. I'll keep to the XML in the registry for now and wait for the next release :)
