### ISSUE TITLE
Registration tie to DTLS state

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#506]
In [LWM2M 1.0.2 §8.2.4 Registration Interface](http://openmobilealliance.org/release/LightweightM2M/V1_0_2-20180209-A/OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf) : 
> When a new DTLS Session is started, or in NoSec mode when the LwM2MClient IP address changes, the Client MUST register again to the LwM2MServer.

In [LWM2M 1.1 § 6.4.3. Registration Interface](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.html#6-4-3-0-643-Registration-Interface) : 
> When a new TLS/DTLS handshake is started, or in NoSec mode when the LwM2M Client IP address changes, the Client MUST register again to the LwM2M Server.

In [LWM2M 1.1.1 § 6.4.3. Registration Interface](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-4-3-0-643-Registration-Interface) : 
> When a new security context is created (e.g. TLS/DTLS), the Client MUST register again to the LwM2M Server.
> When the LwM2M Client IP address changes in NoSec mode, the Client MUST register again to the LwM2M Server.

This is not clear to me what is "security context", (is it the session or the connection ?)
I guess it still means new handshake. So new connection NEEDS  new registration.

The specification seems to tie more and more registration lifetime to TLS/DTLS state.
Regarding this old discussion #177, I would expect another direction.
I would like to understand the rational behind this ?

Is this still just about this CoAP-Observation specification issue ?

**Comment by sbernard31** [comment]
Maybe one example which show kind of troubles brought by this coupling : 

Reading [6.2.1.2. Behaviour with Current Transport Binding and Modes](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-2-1-2-0-6212-Behaviour-with-Current-Transport-Binding-and-Modes)

> "Registration Update Trigger" is a mandatory resource in the LwM2M Server Object (/1/x/8). The client SHALL use the argument when the "Registration Update Trigger" resource is executed unless not supported by the client or not indicated as supported by the server in the "binding" resource of the LwM2M Server Object (/1/x/7). When that argument indicates an overriding binding that is supported by the client, the client SHALL immediately release the existing transport connection and establish a new transport connection using the overriding binding if that overriding binding is different than the current transport connection.

As changing transport means probably new connection/handshake, "Registration Update Trigger" will be "New Registration Trigger" :thinking:

**Comment by sbernard31** [comment]
Maybe another example(B), Imagine a client behind a NAT using Queue Mode.

Reading [6.3. NAT Traversal](http://www.openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1-20180710-A.html#6-3-0-63-NAT-Traversal): 
> Queue Mode may help with NAT traversal by allowing a LwM2M Server to send messages to the LwM2M Client only after the LwM2M Client has initiated the communication to the LwM2M server first. This ensures that NAT bindings exist that allow incoming packets to the LwM2M Client.

(I know Queue mode is not mainly for NAT, it is for sleepy devices but at Sierra it is mainly used to traverse NAT)

In our case, device initiates an handshake and do a REGISTER, then server sends commands. Then there is no more exchange and  few time ago (few seconds) NAT expires.

Periodically device contacts the server. As it supposes its IP changes (NAT expires), it always starts by a resume handshake (which sometime turn into full handshake if session expired at server side) and do an UPDATE, then server sends commands. Then there is no more exchange and  few time ago (few seconds) NAT expires... etc etc ...

Now with coupling, device is not allowed to do an UPDATE so it must do a REGISTER each time it contact server. This sounds pretty strange. (knowing that often at server side a REGISTER is costly than an UPDATE)
(I know [connection Id](https://tools.ietf.org/html/draft-ietf-tls-dtls-connection-id-07) can be used to solved that and it seems a really good solution but it is not so available for now)

**Comment by sbernard31** [comment]
I'm pretty sure we can find more examples where this coupling sounds not so good.

If the reason is still this [coap-observe](https://mailarchive.ietf.org/arch/msg/core/16SNjbTg8pnDaXonYUwR6M2Xguo/) issue, I'm not sure this is worth to impact as much the specification just for this.
If there is another reason please share ? :pray: 

(We really don't like to do that but at Leshan we did not [follow this constraint for LWM2M 1.0](https://github.com/eclipse/leshan/wiki/LWM2M-Observe#requestnotifications-matching) and we will probably not follow it for LWM2M 1.1 too :disappointed:)

**Comment by hannestschofenig** [comment]
This issue is still about the CoAP Observe, as you correctly reference. 

In v1.2 we have "adopted" the Connection ID solution and hence the problem is either gone or smaller now.
If you use Mbed TLS then the Connection ID extension is available for DTLS 1.2.

**Comment by sbernard31** [comment]
The Observe feature is probably the one which brings much trouble since the beginning and mainly because of those 2 problems : 
 - CoAP observe does not really matches the LWM2M observe use case. OR at least in my experience user expectations who want a kind of reliable historical reporting mechanism ([more detals](https://github.com/eclipse/leshan/wiki/LWM2M-Observe))
 -  This [request/response matching issue](https://mailarchive.ietf.org/arch/msg/core/16SNjbTg8pnDaXonYUwR6M2Xguo/).
  
  With LWM2M 1.1 and 1.2 : 
 -   A new send command was introduce which allow less usage of Observe feature.
 -   Connection Id help for the request/response matching issue.
 
  I consider those go to the right direction. :+1: 
  
  **But** I still don't understand the choice to tie DTLS connection and  LWM2M registration.
  1. We try to fix this request/response matching issue as IETF core level but without success ...really too bad. (personally I don't know what to do more on this point)
  2. You don't want to violate the **rfc7641 -   Observing Resources in the Constrained Application Protocol (CoAP)**, I understand.
  
 But why adding a so impacting constraint just because of one feature. Why not keeping this limitation to observe feature scope.
 Just remind the limitation of CoAP observe in the LWM2M specification and warning that if you are in a dynamic IP environment you probably need reestablished the observe relation if DTLS connection changed.
    
Is there something I missed ?

**Comment by hannestschofenig** [comment]
The bugfix release of the LwM2M specification will remove the sentence about the "security context" since it is indeed unclear what conditions need to be met in order to trigger the re-registration.

**Comment by sbernard31** [comment]
I really hope   :crossed_fingers: you will consider to untie Registration and DTLS state for reasons explained at https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/506#issuecomment-766902712

**Comment by sbernard31** [comment]
It sounds good to me :+1: 

Thx @hannestschofenig  :pray:

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023
