### ISSUE TITLE
Location object (ID 6): new resources requested for UTC time of fix and Validity

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#507]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf
* Section E.7 LwM2M Object: Location 

I would need an additional resource to Location object related to the validity of the data.
in GPGLL nmea sentence there are 2 useful parameters:
UTC time of fix and validity of data
they are very useful to understand if the position is good or not, if the fix is done or in progress, and so on.
Requested new resources:
UTC time of fix= integer, Read Only
Validity= boolean, Read Only

$--GLL,lll.ll,a,yyyyy.yy,a,hhmmss.ss,A llll.ll = Latitude of position
a = N or S
yyyyy.yy = Longitude of position
a = E or W
hhmmss.ss = UTC of position
A = status: A = valid data

example from https://www.gpsinformation.org/dale/nmea.htm 
$GPGLL,4916.45,N,12311.12,W,225444,A,*1D
Where:
     GLL:___________ Geographic position, Latitude and Longitude
     4916.46,N:_____Latitude 49 deg. 16.45 min. North
     12311.12,W:___Longitude 123 deg. 11.12 min. West
     **225444:_______Fix taken at 22:54:44 UTC
     A:______________Data Active or V (void)**
     *iD:____________checksum data

**Comment by ezhaboy** [comment]
Except of GPGLL, information also can be found in GGA, and ZDA sentence. 

By referring definition of LwM2M Resource 5 Timestamp: it states that 'The timestamp of when the location measurement was performed.'. Are you proposing additional Resource to represent timestamp of fix taken? If yes, additionally, from week number rollover consideration, not sure whether using Time as data type is a good choice.

**Comment by giuseppe-melis** [comment]
Sorry all,
I've discussed with my GNSS colleagues more experts than me about positioning:
the time in GLL is already present in 6/0/5 OMA resource, so no need to request a new resource for time (thanks @ezhaboy ).
Furthermore, they say that is better referring to RMC sentences, because GLL could be obsolete.

![image](https://user-images.githubusercontent.com/33488995/96424070-7d807980-11fa-11eb-8022-8cd287ebb7cf.png)


On the other hand, I would really have a **new resource for Validity/Status** of data with the following meaning:
A: Data Valid
V: Void, Navigation receiver warning
To be more clear and near to GNSS meaning, I thing that the resource should be String type to indicate "A" and "V" values, instead of Boolean, that was my first choise.
Furthermore, using the String type there is no need to convert TRUE/FALSE to Valid/Invalid, and in future there could be more status values.
Amount of data transmitted is quite the same between string and boolean.

The scenario is this:
a lwm2m server is observing or requesting the location object periodically;
a GNSS receiver provides the location info to the lwm2m client according to the application logic;
**in some cases, the GNSS signal could not be good/valid** (i.e. enter into a tunnel/garage, fix not yet achieved): in these cases the lwm2m location resources are filled with not valid values, so the lwm2m server should manage them accordingly: it could ignore it, it could raise an alarm, etc.
This management is not available using current location object definition, so I'm asking a new resource for that.

Since I wrote some inconsistent and incoerent info on the description, I'm going to close this case and open a new one more clear: do you agree?

**Comment by giuseppe-melis** [comment]
Close this issue because re-wrote in a new clearer case https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/508
