### ISSUE TITLE
Connectivity Monitoring object (ID 4): description of resources 9 and 10 to be improved

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#509]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf
* Section E.5 LwM2M Object: Connectivity Monitoring

Resources 9 and 10:
these resources are valid for all cellular bearers, not only in case of GSM cellular network.
So I suggest to modify the description from:
"In case Network Bearer Resource has 0(cellular network)"
to
"In case Network Bearer Resource has value **0~20 (any cellular bearer**)"

**Comment by hannestschofenig** [comment]
You are looking at an old version of the specification, namely version 1.0.2. In the meanwhile the "Connectivity Monitoring" object has been updated. You can always find the most recent objects in the registry at https://openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

If you look at the most recent version of the object ("urn:oma:lwm2m:oma:4:1.3") , does the description fit your needs. Here is the full object:
https://raw.githubusercontent.com/OpenMobileAlliance/lwm2m-registry/prod/4.xml

**Comment by giuseppe-melis** [comment]
thanks @hannestschofenig 
the case is closed
