### ISSUE TITLE
Connectivity Monitoring object (ID 4): new resource requested for network operator name

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#510]
* OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf
* Section E.5 LwM2M Object: Connectivity Monitoring

It would be nice to have a new resource in object 4: the network operator name.
Although the meaning of this info is the same of SMCC+SMNC, at user level the info is different:
i.e.:
my device is camped on a cell of TIM network,
so the lwm2m client fill in the info about SMCC=222 and SMNC=01 into resources 9 and 10.
At server side, the user can retrieved for sure the network operator name from any public database (i.e. https://www.mcc-mnc.com/).
Since at cellular device side/lwm2m client side, the network operator name is easily available through AT+COPS? command (https://m2msupport.net/m2msupport/atcops-plmn-selection/),
it would be nice to put the network operator name into a String type resource of object 4.

Examples of different network operator name strings according to the selected format (second parameter)

at+cops=0,0
at+cops?
+COPS: 0,0,"**I TIM**",9
OK

at+cops=0,1
OK
at+cops?
+COPS: 0,1,"**TIM**",9
OK

at+cops=0,2
OK
at+cops?
+COPS: 0,2,"**22201**",9
OK

**Comment by hannestschofenig** [comment]
You can create your own version of the Connectivity Monitoring object, which includes this new resource.

**Comment by hannestschofenig** [comment]
Thank you for your proposal. Since Telit is a member of OMA SpecWorks it would be great to see a PR from you adding this feature to the object.

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023
