### ISSUE TITLE
Number representation in SenML format

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#511]
Probably not an issue but I prefer to report this little concern.

The [RFC 8428 - Sensor Measurement Lists (SenML)](https://tools.ietf.org/html/rfc8428) says that  [`value`](https://tools.ietf.org/html/rfc8428#section-4.3) label is of Type `Number` ([floating-point numbers](https://tools.ietf.org/html/rfc8428#section-4.2)).
[Section 5](https://tools.ietf.org/html/rfc8428#section-5) says : 
>  Systems receiving measurements MUST be able to process the range of
   floating-point numbers that are representable as IEEE double-
   precision, floating-point numbers [IEEE.754]...

The [RFC 8428](https://tools.ietf.org/html/rfc8428#section-6) (senML) also says : 
> For JSON Numbers, the CBOR representation can use integers,
      floating-point numbers, or decimal fractions (CBOR Tag 4);
      however, a representation SHOULD be chosen such that when the CBOR
      value is converted to an IEEE double-precision, floating-point
      value, it has exactly the same value as the original JSON Number
      converted to that form.  For the version number, only an unsigned
      integer is allowed.

So, I'm not sure if using number like 18446744073709551615 (2^64-1 : max unsigned 64bit integer) is a valid number knowing [it has not exact IEEE double precision representation](https://baseconvert.com/ieee-754-floating-point) ?

More details about this concern at : https://github.com/eclipse/leshan/issues/916

**Comment by hannestschofenig** [comment]
This is a question for the IETF CORE group, who has defined SenML.

**Comment by cabo** [comment]
While JSON numbers in theory have unlimited (really: unspecified) precision, in practice most implementations turn JSON numbers into binary64 (double precision floating point).  Trying to be interoperable in JSON therefore means limiting oneself to the numbers that can be represented that way.  See also RFC 7493 for more details.

Since SenML tries to be somewhat independent of the representation format, the recommendation is to stick to the lowest common denominator defined by I-JSON, even if CBOR (and theoretically JSON) have a larger gamut they could cover.

**Comment by sbernard31** [comment]
@cabo, If I understand you a valid Number in SenML must be a "double precision floating point number", right ? 

If I well understand then this could be an issue for LWM2M specification because it is said that [Integer and Unsigned Integer Resource should be store as Number in SenML](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#Table-C-2-Data-Type-Mapping) (. So what happens for some of this Integer / Unsigned Integer which can not be stored in  "double precision floating point number" ?  e.g. 18446744073709551615 (2^64-1 : max unsigned 64bit integer) can not fit in double.

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ? 

Just to be clear the remaining issue is : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/511#issuecomment-1533294308
