### ISSUE TITLE
Connectivity Monitoring object (ID 4): clarification request about resource 4

### ISSUE THREAD

**Issue by Enrico-Massari** [OpenMobileAlliance/OMA_LwM2M_for_Developers#512]
OMA-TS-LightweightM2M-V1_0_2-20180209-A.pdf
Section E.5 LwM2M Object: Connectivity Monitoring
Resources 4:
Reading the specs, it's not clear to me which IP Addresses have to be reported in this resource instances.
Could it be the IPV4 and IPV6 addresses related only to connectivity interface used by LwM2M client, or all the IP addresses assigned to all opened PDP context in a IoT modem for example?

**Comment by mojanm** [comment]
LwM2M clients can have multiple APN connections and consequently multiple IP addresses assigned. Resource 4 if populated is expected to list all assigned IP addresses, be they IPv4 or IPv6. In case of multiple IP addresses, if Resource 7, APN connection, is also present the list of APN connections and IP addresses should logically appear in the same order and correspond to each other.

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ?
