### ISSUE TITLE
Test failing  for connectivity monitoring object sometimes 

### ISSUE THREAD

**Issue by sheetal-gupta** [OpenMobileAlliance/OMA_LwM2M_for_Developers#513]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``:
* Section of the document, ``(e.g. section: 6.2)``:
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

**Comment by sheetal-gupta** [comment]
Test failing  for connectivity monitoring object sometimes with Error "updates were not within defined pmax". Where do I need to change the pmax to make the test pass?

**Comment by sheetal-gupta** [comment]
Test failing for connectivity monitoring object sometimes with Error "updates were not within defined pmax". Where do I need to change the pmax to make the test pass?

**Comment by giuseppe-melis** [comment]
Sorry @sheetal-gupta,
are you referring to any well-known setup/scenario?
Maybe you posted the question to the wrong place: this is a forum to discuss OMA specification issues and items.
@hannestschofenig : do you agree?

**Comment by sheetal-gupta** [comment]
ok thanks ,will close it
