### ISSUE TITLE
content format for bootstrap

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#515]
In **LWM2M v1.0**, TLV is a mandatory content format and so it can be used by bootstrap server without any risks, which is good for easy interoperability.

For **LWM2M v1.1**, there is a new parameter on `Bootstrap Request` called "preferred content format" which let know to the server which content format must be used which is also OK for interoperability.

The little issue is that : 
- this parameter is not mandatory.
- there is not default value when parameter is not present.

Server could try to guess depending of the LWM2M version but version is not known.
Even if it was known : 
-  if version was 1.0, we could use TLV 
- but if version was 1.1 we still don't know which format to use as there is not mandatory format usable for bootstrap.  (see #514)

So, if there is no preferred content format, the only solution I see in this case is to try content format until one is accepted. (It sounds not so good :confused:)

(I think this concern LWM2M 1.2 too)

**Comment by hannestschofenig** [comment]
We couldn't make the new parameter mandatory since this would break backwards compatibility. 

In an enviornment where no prior knowledge about the client and server configuration exist I would use the TLV encoding. 

We will make this more clearn in a bugfix release.

**Comment by sbernard31** [comment]
About backwards compatibility rules, I must confess I don't understand what are the current OMA rules ?
I mean what is considered as a break and what is not ?(E.g. https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/490) This is a bit out of topic but maybe a documentation could help to clarify that. (e.g. of kind of documentation for Java Language : https://wiki.eclipse.org/Evolving_Java-based_APIs_2).
(Easy to rise this kind of idea, probably less easy to do)

Anyway, for this particular point IF making the option mandatory is not an option,  I think clearly define that no option means TLV could be a good idea :)

**Comment by mkgillmore** [comment]
Resolved in 1.2x release

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ?
