### ISSUE TITLE
Is "context aware parsing"  really removed by senml-etch ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#516]
In **LWM2M v1.1**, SenML media types can be used for composite operation.
But for encoding paths of ReadComposite operaiton, the SenML standard is not really respected because value is not present where rfc8428 says it is mandatory. (https://tools.ietf.org/html/rfc8428#section-4.2)

In **LWM2M v1.2**, a new media type (SenML-ETCH) which allows do not set a value for record and so fixes this issue.
But the LWM2M v1.2, specification says : 
> As shown above, SenML records used with a Read-Composite operation do not contain any value field while the responses will. Prior to [RFC8790], this implied the need for SenML parsers to be context aware, i.e. to distinguish between SenML records received in Read-Composite operations and responses to such requests. However, media types, application/senml-etch+json and application/senml-etch+cbor, defined in [RFC8790] have removed the requirement for context aware parsing.

I don't understand why "context aware parsing" is considered as removed ? As SenML+ETCH is context aware as SenML format for FETCH and PATCH are different. So we still need a context aware parser or I missed something ?

**Comment by mojanm** [comment]
Strictly speaking the parser still has to know the context, i.e. the operation for which the SenML record is received. So the wording of the Note paragraph in section 7.4.6 of spec, SenML JSON, is not quite right and should instead indicate that prior to RFC8790 there was no clear definition for SenML record matching, use of null to remove a record or absence of Value field for FETCH operations.
Given the notes are only informative this one should not cause any immediate problem and the fix to it could wait till the next release.

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ?
