### ISSUE TITLE
serializer/deserializer for MLP is required in C#

### ISSUE THREAD

**Issue by mabubakarriaz** [OpenMobileAlliance/OMA_LwM2M_for_Developers#517]
A serializer & deserializer to and from POCO classes is required for MLP API. Implementation is required in c#.

For Example:
//Serializer 
MLP_SVC_INIT myObject = new MLP_SVC_INIT();
XmlDocument myXml = myObject.SerializeToXML();

//Deserializer 
XmlDocument myXml =  mlp_svc_result_xml_Object;
MLP_SVC_RESULT myObject = myXml.DeserializeToObject();

Name, version and date of the document: 
OMA-LIF-MLP-V3_1-20040316-C.pdf
OMA-ERELD-MLP-V3_1-20040316-C.pdf

**Comment by hannestschofenig** [comment]
This is an implementation-specific question and it is not related to the LwM2M protocol.
