### ISSUE TITLE
Disable Server indefinitely

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#519]
Object Server 1 has a resource which allow to disable a Server : 

ID | Name | Operations | Instances | Mandatory | Type |  Units | Description
-- | -- | -- | -- | -- | -- | -- | -- 
4 | Disable | E | Single | Optional |   |   | If this Resource is executed, this LwM2M Server Object is disabled for a certain period defined in the Disabled Timeout Resource. After receiving "Execute" operation, LwM2M Client MUST send response of the operation and perform de-registration process, and underlying network connection between the Client and Server MUST be disconnected to disable the LwM2M Server account. After the above process, the LwM2M Client MUST NOT send any message to the Server and ignore all the messages from the LwM2M Server for the period.
5 | Disable Timeout | RW | Single | Optional | Integer | s | A period to disable the Server. After this period, the LwM2M Client MUST perform registration process to the Server. If this Resource is not set, a default timeout value is 86400 (1 day).

It seems that  the idea is to disable a server temporary, but is there a way to disable it indefinitely ? Maybe setting **Disable Timeout** to `0` or `-1`.

I guess the answer is "no" as I can not find anything specified about it.
And I suppose if there was something like this, it should be define how to re-enable a server :-/
So I guess the answer is to disable it, just remove the instance ? 
I ask just in case I missed something ?

**Comment by hannestschofenig** [comment]
If you are interested to disable a LwM2M server indefinitely then it might be better to remove the LwM2M Server resource altogether. 

Alternatively, (if this approach is too brutal) I would suggest to register a new resource that offers this functionality.

In general, most devices are not connected to multiple LwM2M Servers due the additional resource requirements. The currently defined resource also demands the underlying network connectivity to be cut, which is only relevant if there are multiple network interfaces and each LwM2M Server is connected via a different network interface. This is a rare case...

**Comment by mkgillmore** [comment]
Group agrees that this issue is resolved and can be closed 10/31/2023
