### ISSUE TITLE
LwM2M Gateway object example

### ISSUE THREAD

**Issue by giuseppe-melis** [OpenMobileAlliance/OMA_LwM2M_for_Developers#535]
* OMA-TS-LWM2M_Gateway-V1_1-20210518-A :
* Section 10. Example, page 17 (20):

there is mistake in the example:
current:
LwM2M Firmware Update (OID 6)

expected:
LwM2M Firmware Update (OID **5**)

Please modify it also in other points of the same example

**Comment by hannestschofenig** [comment]
You correctly observed a bug. We will fix it with the next bugfix release of the gateway specification
