### ISSUE TITLE
Should digit from Execute arguments appear only once ? 

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#536]
Said differently is : `0='arg1',0='arg2',0='arg3'`  allowed as Arguments of Execute request ?

This sounds very strange to me as I guess a more intuitive way should looks like `0='arg1,arg2,arg3'` but I see nothing in the specification which forbids this.
See [LWM2M-v1.1@core§6.3.5-Execute-Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#6-3-5-0-635-Execute-Operation)

There is maybe just a hint that digit is unique at [Table: D.1-3 Executable Resource Arguments Definition](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#Table-D1-3-Executable-Resource-Arguments-Definition) as the column named is called **Key**.

Could you clarify this ? :pray:

**Comment by mojanm** [comment]
The digits used to identify arguments should be unique as the order they can appear in any order. If they were not unique, then the order would become important and would also not be possible to support optional arguments that may be present or absent. Object 16, Portfoli Object, Specification provides example of executable resource that can receive multiple arguments, each having a unique identifying number.
Maybe we should consider adding a note to indicate argument digits should be unique, or  modify ABNF to rule out possibility of duplication. The former will probably be more obvious and clearer to the reader??

**Comment by sbernard31** [comment]
Thx for the answer :pray:
That's really help. 

About adding it to the specification I agree it would be better.
About note or ABNF modification I haven't strong opinion.

**Comment by mkgillmore** [comment]
Resolved in 1.2x release
