### ISSUE TITLE
Attribute Assignation Level inconsistency ? 

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#539]
The specification (v1.1 and v1.2) says : 

> Assignation Level :  The Level (Object, Object Instance, Resource, Resource Instance) where the value of the Attribute is set **(by WRITE-ATTRIBUTES)**. 

(from [Table: 5.1.1.-1 Attribute Characteristics](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-511-1-Attribute-Characteristics))

But Attribute table  seems to define a assignation level for some attribute which can not be written with WRITE-ATTRIBUTES : 
See [Table: 5.1.2.-1 <PROPERTIES> Class Attributes](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#Table-512-1-lessPROPERTIESgreater-Class-Attributes)

This looks like a little inconsistency or I missed something ?

**Comment by mojanm** [comment]
Assignation level column in Table: 5.1.2.-1 Class Attributes is redundant and somewhat misleading. I propose to remove it as the attributes listed in this table are all Read only.

**Comment by sbernard31** [comment]
It could make sense.

But I have just a little concern.

When I have a CoRE Link Format, I don't know how to determine  which level is allowed.

E.g  (from the lwm2m specification): 
```</3/0>;pmin=10;pmax=60, </3/0/1>, </3/0/2>, </3/0/3>, </3/0/4>, </3/0/6>;dim=2, </3/0/6/0>, </3/0/6/3>, </3/0/7>;dim=2;gt=50;lt=42.2, </3/0/7/0>, </3/0/7/1>;lt=45, </3/0/8>;dim=2, </3/0/8/1>, </3/0/8/2>, </3/0/11>, </3/0/16>```


Here you have :
</3/0>;pmin=10
So it seems that I should look the assignation (and not attachment)  to know that pmin attribute can be used on object instance.

For </3/0/7>;dim=2; which is read only **IF** we remove the assignation level that means that I need to look at the attachment to know that dim can be used with a resource.

So maybe this is better to change the description of assignation level ? :thinking: 
OR I missed something ?

**Comment by mkgillmore** [comment]
Resolved in 1.2x release

**Comment by sbernard31** [comment]
@mkgillmore can you elaborate ?

Resolved by what ? and in which version of the specification ? 

Especially about : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/539#issuecomment-1039278672

**Comment by sbernard31** [comment]
> Resolved by what ? and in which version of the specification ?

I guess this is resolved by : [LWM2M-v1.2.1@core§7.3. Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#7-3-0-73-Attributes)

> When I have a CoRE Link Format, I don't know how to determine which level is allowed.

What we finally did in Leshan.

**For LWM2M v1.1.x :** 
We are using `Assignation level` column to know to which kind of LWM2M node an attribute can be attached and we don't use `Attachment` column at all. 

**For LWM2M v1.2.x :** 
We will use `Attachment` column.

**Comment by mkgillmore** [comment]
I believe it was resolved in 1.2.1

If not lets revisit,  we are preparing a 1.2.2 bug fix release that will be released in the next month or two.

Thanks

Matt

From: Simon ***@***.***>
Sent: Friday, March 1, 2024 8:54 AM
To: OpenMobileAlliance/OMA_LwM2M_for_Developers ***@***.***>
Cc: Gillmore, Matthew ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenMobileAlliance/OMA_LwM2M_for_Developers] Attribute Assignation Level inconsistency ? (Issue #539)

Resolved by what ? and in which version of the specification ? I guess this is resolved by : LWM2M-v1. 2. 1@ core§7. 3. Attributes When I have a CoRE Link Format, I don't know how to determine which level is allowed. What we finally did in Leshan. 
ZjQcmQRYFpfptBannerStart
Warning! This email comes from outside the company.
This message came from outside of Itron, if you suspect it to be spam, please delete it or if you suspect a phishing attempt, please report it using the Phish Alert Report button. Be careful and think before you click.
ZjQcmQRYFpfptBannerEnd

Resolved by what ? and in which version of the specification ?

I guess this is resolved by : ***@***.***§7.3. Attributes<https://urldefense.com/v3/__https:/www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html*7-3-0-73-Attributes__;Iw!!F7jv3iA!z1lI3fVvPZG4NCVTcaucAqVBDmIIrDKkMcNyPkcUa7V39lDtrgVaRjw983M50pNhMRJttJvRkX9J2x8vBgrvqUZrjC-o2g$>

When I have a CoRE Link Format, I don't know how to determine which level is allowed.

What we finally did in Leshan.

For LWM2M v1.1.x :
We are using Assignation level column to know to which kind of LWM2M node an attribute can be attached and we don't use Attachment column at all.

For LWM2M v1.2.x :
We will use Attachment column.
