### ISSUE TITLE
Lwm2m CBOR format - specify Create operation payload

### ISSUE THREAD

**Issue by wodomierz** [OpenMobileAlliance/OMA_LwM2M_for_Developers#541]
## Document info

Document: OMA-TS-LightweightM2M_Core-V1_2-20201110-A
Sections: 7.4.4. LwM2M CBOR, 6.3.6. Create Operation

## Problem description

According to the specification OMA-TS-LightweightM2M_Core-V1_2-20201110-A (section 6.3.6. Create Operation), Lwm2m CBOR is one of the formats, which could be used in Create operation with or without Object Instance ID. However, there is some ambiguity in the format. 

### Ambiguity description 

What we know is that the payload in Create operation doesn’t have to start with object id (from section 7.4.4. LwM2M CBOR):
`Except when used for a Write or Create operation, the IDs inside the top-level payload MUST start with the Object ID.`

According to the specification, Create with target /3 (object id 3 ) and payload (in cbor diagnostic notation): 
```
{3 : { 3 : {3 : 3} } }
```
could be interpreted as creation of object instance with id 3 and multiresource 3/3 : 3
or creation of object instance with id 3 and resource 3: 3, because we don’t know if the top level payload starts with an object id,  or an object instance id ( /3/3/3/3: 3 or /3/3/3 : 3 ).
Moreover if we send Create with target /3 and payload:
```
{ 3 : {3 : 3} } 
```
we don't know if it is Create with Object Instance ID 3 in the payload, and resource 3 : 3, or Create without Object Instance ID and with multiresource 3/3 : 3.

## Suggestion of the solution:

I suggest adding one of the following restrictions, to resolve the ambiguity:

1.  In the Create top level payload MUST start from Object ID XOR Resource ID (we cannot mix them in one payload)

2. The payload always start from Object ID and Lwm2m CBOR format is forbidden for Create operation without Object Instance Id

**Comment by hannestschofenig** [comment]
The bugfix release of the LwM2M v1.2 specification will be published in Q4 2022, according to the plans of the OMA DMSE/IPSO working group and it will contain this fix.
