### ISSUE TITLE
Error: Cannot find module 'azure-iothub'

### ISSUE THREAD

**Issue by SAMBHAV1997** [OpenMobileAlliance/OMA_LwM2M_for_Developers#542]
In [iot-hub-lwm2m-bridge](https://github.com/Azure-Samples/iot-hub-lwm2m-bridge) 
when we are executed "node iotbackend/backend.js iothubDevice1" command , and getting "Cannot find module 'azure-iothub'" error.

We have installed npm dependencies successfully:
 ```npm install lwm2m-node-lib```
  ```npm install async```
  ```npm install azure-iot-device-mqtt```
  ```npm install azure-iot-device```
  
Strated the lwm2m server through :
node gateway/lwm2mgw.js

Created resource through:
node lwm2mdevice/device.js lwm2mDevice1
![Screenshot (114)](https://user-images.githubusercontent.com/30692300/157810496-d7cc4ba0-75c7-4a9b-b000-e1b272ee5a33.png)

**Comment by sbernard31** [comment]
Maybe I missed something but I think this repo is about LWM2M specification itself.
I'm not sure but I understand your question is about  [iot-hub-lwm2m-bridge](https://github.com/Azure-Samples/iot-hub-lwm2m-bridge), so why not asking it at https://github.com/Azure-Samples/iot-hub-lwm2m-bridge/issues ?

**Comment by hannestschofenig** [comment]
This question is indeed directed to the wrong group.
