### ISSUE TITLE
Clarification about multiple use of some attributes. 

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#544]
Leshan does not allow to use the attributes twice (e.g.  `</>;ct=110;ct=112 `)

And we get some question about that from Leshan user.

We have an interesting discussion about this at https://github.com/eclipse/leshan/issues/1229#issuecomment-1086111310
(Note the very interesting answer of @weinholt)

I know this is probably more a IETF question, but maybe you have some hint or clarification about it ? 
Maybe It could pay-off to also clarify this for other attributes  (especially the LWM2M one) ?

**Comment by dnav** [comment]
My personnal opinion on this specific example, not the general question:

To indicate the support of multiple optional content formats, the LwM2M TS 1.2 indicates to use the following payload:
> Another example if the LwM2M Client supports the SenML JSON format, the CBOR format, and the SenML CBOR
format:
>
> </>;ct="110 112 60", </1/0>,</1/1>,</2/0>,</2/1>,</2/2>,</2/3>,</2/4>,</3/0>,</4/0>,</5>

This example is based on the ABNF for the ct attribute in [RFC 7252](https://www.rfc-editor.org/rfc/rfc7252.html#section-7.2.1):
```
      ct-value =  cardinal
               /  DQUOTE cardinal *( 1*SP cardinal ) DQUOTE
```

This is not linked to a particular LwM2M version. The example was added for clarification.

**Comment by hannestschofenig** [comment]
We discussed this issue in the OMA DMSE/IPSO working group and we agree with David.

**Comment by sbernard31** [comment]
(It could be clarified in rfc7252  : https://github.com/core-wg/corrclar/issues/4)
