### ISSUE TITLE
BootstrapPack - discovering Boostrap LwM2M Security instance

### ISSUE THREAD

**Issue by michalm86** [OpenMobileAlliance/OMA_LwM2M_for_Developers#547]
For Bootstrap-Discover operation the spec says:

> The "Bootstrap-Discover" operation on the Bootstrap Interface is used to discover which LwM2M Objects and Object
Instances are supported by a certain LwM2M Client. In particular, the list of Security Object Instances (ID:0) is reported,
while it is not accessible in Device Management and Service Enablement Interface.

https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf#__WKANCHOR_2c

What is the right way to achieve the same for Bootstrap-Pack operation?
According to Figure 6.1.3.3.-2 in section: https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf#__WKANCHOR_1w
we are supposed to have just request and response - nothing between.

How can we discover Bootstrap LwM2M Security instance, then?

**Comment by sbernard31** [comment]
(:warning: I'm not an OMA member and not one of LWM2M specification writer, so better to wait get answer from them)

### Current understanding :

Reading [LWM2M-v1.2@core$6.1.7.7. Bootstrap-Pack-Request Operation](http://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.html#6-1-7-7-0-6177-Bootstrap-Pack-Request-Operation), **my current understanding is that you can not**.

I guess the idea is that  the bootstrap server should already know some information about the client like : 
- the lwm2m version of the client
- the bootstrap config (like object to write and/or delete)
- and so also probably the object versions.
- Security(0) and OSCORE(21) instance ID of bootstrap server (see #522)

I guess we can consider this as a limitation of Boostrap-Pack-Request. Another one : there is no way to delete a object that you will not write again. (E.g. you stop using OSCORE and want to remove all OSCORE instances)

Considering this limitation maybe, the right sequence should be : 
- Client send Bootstrap-Pack-Request,
- if Server has all information it needs, it send 205 with Payload,
- else Server answers with 405 (or another better code ?),
   - Client tries a classic Bootstrap-Request,
   - server send discover,
   - continue normal bootstrap ... 

### Future Improvement  ?

Personally, I feel that it could eventually makes sense that Client gives lwm2m version and object versions in `Bootstrap-Request` or `Bootstrap-Request-Pack`. (pretty much like the Register request)

I guess someone could argue for cases where server already know those information this is useless and so this consumes some extra bandwidth !
 :thinking:  I guess this is true (but also true for registration) and eventually this could be optional, the specification could define the behavior in case those information are absent and bootstap server don't know it.

E.g : 
- Client send Bootstrap-Pack-Request **without** information,
- if Server has all information it needs, it send 205 with Payload,
- else Server answers with ??TBD?? error code,
   - Client tries  Bootstrap-Pack-Request **with** information,
   - Server send 205 with Payload.

**Comment by michalm86** [comment]
Interesting input, thank you.

You mentioned 405 response - regarding the Bootstrap-Pack Operation I am also wondering what is the real case for it. The spec:

> If the LwM2M Server supports the
"Bootstrap-Pack-Request" but wishes the LwM2M Client not to use "Bootstrap-Pack" for bootstrapping, it MUST
return an error code indicating that the method is not allowed to the LwM2M Client.

https://www.openmobilealliance.org/release/LightweightM2M/V1_2-20201110-A/OMA-TS-LightweightM2M_Core-V1_2-20201110-A.pdf#__WKANCHOR_2k

**What is the real case for the server to wish the client not to use BS Pack and respond with MethodNotAllowed?** (Missing BS Security instance information seems to be a good reason.)
