### ISSUE TITLE
typo in RSSI (object 4) definition

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA_LwM2M_for_Developers#56]
> This node contains the average value of the received signal strength indication used in the current network bearer in case Network Bearer Resource indicates a Cellular Network (RXLEV range 0…64) 0 is < 110dBm, 64 is >-48 dBm).

Should be -110dBm

**Comment by ThGarnier** [comment]
Yes, correct (so your fix has been integrated in TS 1.0).
In fact these values and range present in LWM2M spec are related to the GSM standard only. for other cellular network (e.g. LTE)  of course other parameters apply ; so LWM2M spec has to be more precise  (e.g. .....) related to  the  RSS resource description.
Also in GSM, the RXLEV range is not [0..64] but [0..63]; so the description has to be revisited again. MAY2016  release of TS 1.0 will fix that points.

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's latest comment
