### ISSUE TITLE
Using negative value in write attributes ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#563]
Is it possible to use negative value in write attribute, especially for **Greater Than** and **Less Than** ?

The specification [LWM2M-v1.2.1@core§Table: 7.3.2.-1 <NOTIFICATION> class Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#Table-732-1-lessNOTIFICATIONgreater-class-Attributes) says this is not possible : 

Attribute Name | CoRE Link param | Attachment | Access Mode | Value Type | Default Value | Applicability
-- | -- | -- | -- | -- | -- | --
Greater Than | **"gt" "=" 1*DIGIT ["." 1*DIGIT]** | ResourceResource Instance | RW | Float | - | Numerical & Readable Resource
Less Than | **"lt" "=" 1*DIGIT ["." 1*DIGIT]** | ResourceResource Instance | RW | Float | - | Numerical & Readable Resource

Is it intended or is it a bug ?

**Comment by sbernard31** [comment]
Note that [LWM2M-v1.2.1@core§Table: 7.3.2.-1 <NOTIFICATION> class Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#Table-732-1-lessNOTIFICATIONgreater-class-Attributes) also says : 
> The behaviour of Notification class attributes MUST follow [[Cond_Attr](https://datatracker.ietf.org/doc/html/draft-ietf-core-conditional-attributes)] unless stated otherwise in this specification.

And [[Cond_Attr§ 3.1. Conditional Notification Attributes ](https://datatracker.ietf.org/doc/html/draft-ietf-core-conditional-attributes#section-3.1)]  says : 


Attribute | Name | Value
-- | -- | --
Greater Than | c.gt | xs:decimal
Less Than | c.lt | xs:decimal
Change Step | c.st | xs:decimal (>0)


So it seems there is a contradiction between both specification.

**Comment by sbernard31** [comment]
Note there also a difference with `pmin`, `pmax`, `epmin` and `epmax`.
In **LWM2M** they are considered as Integer and in **Cond_attr** there are decimal.

**Comment by mojanm** [comment]
As "c.gt" and "c.lt" IETF core conditional attributes that are supposed to be aligned with LWM2M attributes can be less than 0, can assume Table 7.3.2.1 in LwM2M spec needs to be updated to reflect this.

**Comment by sbernard31** [comment]
@mojanm thx for the answer, this really helps. :pray: 
I will be able to update Leshan behavior. 

What about  `pmin`, `pmax`, `epmin` and `epmax` ?

Attribute Name | CoRE Link param 
-- | -- 
Minimum Period | "pmin" "=" 1*DIGIT 
Maximum Period | "pmax" "=" 1*DIGIT 
Minimum Evaluation Period | "epmin" "=" 1*DIGIT 
Maximum Evaluation Period | "epmax" "=" 1*DIGIT 

(from [LWM2M-v1.2.1@core§Table: 7.3.2.-1 <NOTIFICATION> class Attributes](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html#Table-732-1-lessNOTIFICATIONgreater-class-Attributes))


 I guess it should be adapted too?  Replacing `1*DIGIT` by `1*DIGIT ["." 1*DIGIT]` ? 

**because :** 

Attribute | Name | Value
-- | -- | --
Minimum Period (s) | c.pmin | xs:decimal (>0)
Maximum Period (s) | c.pmax | xs:decimal (>0)
Minimum Evaluation Period (s) | c.epmin | xs:decimal (>0)
Maximum Evaluation Period (s) | c.epmax | xs:decimal (>0)

(from [[Cond_Attr§ 3.2. Conditional Control Attributes ]](https://datatracker.ietf.org/doc/html/draft-ietf-core-conditional-attributes#section-3.2))

**Comment by mkgillmore** [comment]
Yes you can use negative values for greater than and less than

**Comment by sbernard31** [comment]
> Yes you can use negative values for greater than and less than

@mkgillmore thx to confirm about **greater than** and **less than** but my last [comment](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/563#issuecomment-1790424430) was about `pmin`, `pmax`, `epmin` and `epmax`

I guess it should be adapted too? 
- Replacing integer by float
- Replacing 1*DIGIT by 1*DIGIT ["." 1*DIGIT] ?

**Comment by sbernard31** [comment]
@mkgillmore just a ping to try to get confirmation from you 🙏
