### ISSUE TITLE
Does alternatePath be present in payload for SenML ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#564]
In LWM2M 1.2, it seems that alternate path should be used in payload for `SenML JSON`, `SenML CBOR`,` SenML-ETCH JSON`, or the `SenML-ETCH CBOR `. See : https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_2_1-20221209-A.html#6-4-1-0-641-Alternate-Path

but in LWM2M 1.1, there is nothing about it : 
http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Transport-V1_1_1-20190617-A.html#6-4-1-0-641-Alternate-Path

What is the recommended way for LWM2M v1.1 ?

**Comment by mkgillmore** [comment]
We do not back port changes in LwM2M 1.2 to 1.1.  The best approach is to use clarification introduced in the newer versions of the standard when they apply.  v1.2 is the best practice for how LwM2M is implemented with experience and clarifications from v1.1.  We have a goal to stay backwards compatible.  Please note,  we do not maintain v1.1 and move forward with future versions.
