### ISSUE TITLE
Proposition for more advanced notification class attributes gt and lt

### ISSUE THREAD

**Issue by trickydicky** [OpenMobileAlliance/OMA_LwM2M_for_Developers#569]
Document: OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A, Approved Version: 1.2.1 - 2022-12-09
Section: 7.3.2. <NOTIFICATION> Class Attributes

This issue is to propose more advanced notification class attributes. For each resource, we can have only one "greater than" (gt) and "less than" (lt) attribute. But for our use case, and I think it is not an exceptional use case, we would like to have multiple gt's and lt's per resource. 

In general we would like to be able to configure upper and lower thresholds at various levels, for instance "threshold passing warning" at temperatures above 50ºC and below 0ºC and "threshold passing emergency" at temperatures above 60ºC and below -10ºC. 

Also we would like to introduce the concept of hysteresis, see figure below.
![Screen Shot 2023-08-01 at 11 06 41](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/assets/347091/a945e652-2dca-422d-93d0-c71899a25786)

Thanks in advance,

**Comment by mojanm** [comment]
Write-Attribute operation cannot be used to attach multiple attributes of the same type to the same resource or resource instance. Although not explicitly stated in the specification, this requirement could potentially be met by using observation attribute parameters with Observe operation as per section 6.4.1 of TS v1.2.x; this is obviously somewhat implementation dependent.

**Comment by cw8466** [comment]
Isn't hysteresis already covered by "st" (step)? If I'm not mistaking, along with attributes associated with different severity levels, you would also need an attribute for the severity level itself. The purpose would be to be able to change the severity level on the fly through a single attribute?

**Comment by mkgillmore** [comment]
@trickydicky Thanks for your idea/contribution.  Unfortunately,  you must be a member of OMA to contribute new ideas into our specifications.  Ping me if you need information about how to join OMA
