### ISSUE TITLE
how to get the source code of version 1.2

### ISSUE THREAD

**Issue by zhaoxxbmd** [OpenMobileAlliance/OMA_LwM2M_for_Developers#571]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``:
* Section of the document, ``(e.g. section: 6.2)``:
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``

**Comment by mkgillmore** [comment]
@zhaoxxbmd Can you been more specific about what you need?  OMA doesn't publish source code for LwM2M.
