### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by Shivi1771** [OpenMobileAlliance/OMA_LwM2M_for_Developers#576]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``:OMA LightWeight M2M 1.0
* Section of the document, ``(e.g. section: 6.2)``:
* Sequence of exchanges between Client and Server ``(if any)``: NA
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``
**There's an issue while installing this DevKit because when I try to manually add_on it after giving the path in the extension file of the default profile it says the file is corrupted. Neither is there any prompt from firefox side for the installation of the extension. Please kindly help for its smooth installation.**

**Comment by mkgillmore** [comment]
Group had decided that their will be no further support for this plug-in and it is deprecated
