### ISSUE TITLE
Why would you guys have this structure on my device. 

### ISSUE THREAD

**Issue by ghost** [OpenMobileAlliance/OMA_LwM2M_for_Developers#586]
When submitting an issue please indicate the following information:
* Name, version and date of the document, ``(e.g. OMA-TS-LightweightM2M-V1_0-20160802-C)``:
* Section of the document, ``(e.g. section: 6.2)``:
* Sequence of exchanges between Client and Server ``(if any)``: 
* Illustrations which may help to visualize the problem, ``(e.g. attach a file or image)``:

``Note: please submit problems separately, it is difficult to handle multiple problems in the same issue.``
I'm not able to receive incoming messages via the web. None of my notifications are coming to my device. My location is showing extremely off in web and on maps. My third party apps aren't working. I want all text calls and notifications 
![Screenshot_20240926-070726](https://github.com/user-attachments/assets/91d8470c-1d90-4ff8-a200-822edbd4b23b)
![Screenshot_20240926-070848](https://github.com/user-attachments/assets/c000c734-5a84-4708-b431-2bfa58566494)

**Comment by sbernard31** [comment]
Following the [wiki of this repository](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/wiki) : 

> **OMA LwM2M Issues in GitHub**
>
>    - The [Bugs/Issues](https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/wiki/Issues-in-GitHub) tab in this repository is used by the industry to submit bugs against OMA LwM2M specifications.

At first sight, I'm not sure your question is related to that ? or I missed something ?

**Comment by ghost** [comment]
There is a conflict

**Comment by sbernard31** [comment]
![what?](https://media.tenor.com/RQbOvuBgEDIAAAAC/what.gif)

**Comment by ghost** [comment]
Why aren't I receiving messages to my device

**Comment by sbernard31** [comment]
@Jayhelp you are writing message/comment at a place where we discuss about Lightweight M2M protocol.
This is a internet standard use to make communication between device and server more interoperable. 

Here you should ask question about the LWM2M protocol specification, [you can find the last version here](https://www.openmobilealliance.org/release/LightweightM2M/V1_2_1-20221209-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A.html). 

Reading your comment, I understand that you don't have an issue with the specification but you face a technical issue with your device. (I don't get if you are a user or developer or ? )

IF I'm true THEN you should ask question to your  device reseller or manufacturer. 
IF I'm wrong AND you really ask question about LWM2M THEN sorry but I didn't understand, could you please better describe your issue and maybe provide : 
- Name, version and date of the document, (e.g. OMA-TS-LightweightM2M-V1_0-20160802-C):
- Section of the document, (e.g. section: 6.2):
- Sequence of exchanges between Client and Server (if any):
- Illustrations which may help to visualize the problem, (e.g. attach a file or image):

HTH

**Comment by sbernard31** [comment]
@mkgillmore, the user who ask this question has been delete. So I think can close this issue.

**Comment by mkgillmore** [comment]
@sbernard31 Thanks Simon.   This guy is clearly trolling...

**Comment by jpradocueva** [comment]
@mkgillmore @sbernard31 I blocked him when I saw the comments.
