### ISSUE TITLE
Bootstrap Message Flow

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#62]
During tests we found, that the bootstrap interface in the client initiated mode has the same issue on the message flow then the registration interface:

https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/7

When the client starts its bootstrap (request bootstrap) a write or delete may be received before the ACK for the initiating request.

The solutions are the same:
Either use a separate CON response or silently ignore write/delete before receiving the ACK.

Maybe the specification could be mention those hints.

**Comment by Megan-OMA** [comment]
@ThGarnier will you please provide a final comment on why this issue is to be closed before we close it

**Comment by ThGarnier** [comment]
According to WG (Oct F2F Meeting) Section 8.2.2 section should answer the question => to be closed

**Comment by boaks** [comment]
I still can't see, that a order change in the message flow is covered by the TS.

The sequence in figure 17 shows the assumption about the message flow/order.
But it **ignores** the fact, that UDP doesn't grant the order!
So, even if the server send the `response 2.04 changed`,  before the `request "delete`", there is no garantee that the device will receive the messages in that order.
As for now, I can't see, that the TS chapter 8 realy describes how to handle the "natural" behaviour of CoAP over UDP with exchange message order. There are only very few cases (registration/bootstrap) and there is a proposal from dnav, but I would prefer, if the TS would clarify this. I think, this would then also help, not to rise that "message order" issue again and agin (see #162)
  
Proposal Dnav:

https://github.com/eclipse/wakaama/pull/24

**Comment by dnav** [comment]
Receiving a Bootstrap command before the ACK for the Bootstrap Request should be treated just like a Server Initiated Bootstrap by the Client.
