### ISSUE TITLE
Any alternatives to PKCS#15 being considered

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA_LwM2M_for_Developers#63]
Hello OMA,

OMA-DM and OMA-LwM2M relies on PKCS#15 for bootstratp info storage in UICC. However, support of PKCS#15 is almost non-existent in UEs. Are there any alternatives available and being considered which may have more following than PKCS#15.

Thank you
H. Ali

**Comment by ThGarnier** [comment]
Hum !! the risk of supporting an alternative to PKCS#15, is to be obliged to do similar things and then to re-invent the wheel.   What must be support be the UE is 3 things :  1) support for parsing the EF DIR in the UICC for discovering the application through their AID : USIM, ISIM ... and PKCS#15; so all mobiles even IPhone are supporting this; if you define a new application the AID should be registered; the one of PKCS#15 is already specified  2)  them the UICC parser must be able to walk through the PKCSK#15 arborescence (2 files accesses)  for being able to reach the bootstrap message file: in any case the alternative solution will do also something very similar, especially if some security must be associated to this access; so at the end you will really re-invent the weel. Anyway have you any idea to do the things simpler and things which could be specified ?
Hope its helped you 
Thierry

**Comment by ThGarnier** [comment]
Hi I reformulate my last question : have you, please,  any better alternative in mind ?

**Comment by ThGarnier** [comment]
no new remark => to be closed (can be reopen if someone is submitting alternative)

**Comment by Megan-OMA** [comment]
Issue now closed due to no new responses. (19-April-2016)
