### ISSUE TITLE
DISCOVER and READ all objects?

### ISSUE THREAD

**Issue by mjkoster** [OpenMobileAlliance/OMA_LwM2M_for_Developers#67]
Since it is possible to register the root path, for example from the TS Sec. 5.3.1:

</lwm2m>;rt="oma.lwm2m", < /1/101>, < /1/102>, (...)
</>;ct=1543, </1/0>, (...)

It seems like we should specify DISCOVER (5.4.2) and READ (5.4.1) operations on the root path, to potentially return all object links and return object representations, respectively.

**Comment by jvermillard** [comment]
that would create a massive response for a read, I'm not sure it's compatible with constrained target

**Comment by mjkoster** [comment]
Simply returning links to all objects on a root DISCOVER would be a reasonable amount of data in many cases. It would be approximately the same size as the registration packet.

**Comment by mjkoster** [comment]
I'll provide some example responses so we can get an idea of the data volume

**Comment by ThGarnier** [comment]
According to WG (Oct16 F2F Meeting); such requirement could be consider in the frame of 1.1 only  => To Be Closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above that this is to be addressed in release 1.1
