### ISSUE TITLE
Persistence of downlink requests in queue mode

### ISSUE THREAD

**Issue by alex-ellwein** [OpenMobileAlliance/OMA_LwM2M_for_Developers#69]
I have a question about the server's behavior in queue mode. The LWM2M Spec states, that

> If the LWM2M Client sends a “Register” operation to the LWM2M Server even though the LWM2M Server has registration information of the LWM2M Client, the LWM2M Server removes the existing registration information and performs the new “Register” operation. This situation happens when the LWM2M Client forgets the state of the LWM2M Server (e.g., factory reset).

What happens to the downlink requests in queue mode which have been issued BEFORE a client re-registers - do they persist or should they be dropped upon a new registration?

**Comment by jvermillard** [comment]
if it's the same device keeping the message queue make sense

**Comment by balsmn** [comment]
@jvermillard I am not sure about keeping the message queue. If there was a factory reset, queued requests could bring inconsistencies (for e.x. firmware updates which could be based on the previous state of the client, is now lost due to factory reset). 

Lets start small and simple. How about deleting the messages in the Queue when a client de-registers ?

**Comment by jvermillard** [comment]
IMO queue mode are useless, the way we implemented it, it's more a reaction based on the received message: a registration, read the version, then if the version need to update send the corresponding package, wait for the status, if the status failed, retry one time, etc..
I hardly believe a big queue of messages waiting for the device can be useful for device management

**Comment by hannestschofenig** [comment]
Covered in #80

**Comment by ThGarnier** [comment]
According to the last CR117 included in the Oct16 TS,  issue can be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above re: October 2016 TS
