### ISSUE TITLE
no 4.00 Bad Request for De-Register and Discover ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#70]
Chapter 8.5 :
There is no `Bad Request` response defined for `De-Register` and `Discover` operation, I can not find any reason for that ?
_(This is also the case for `Bootstrap-Delete`)_

**Comment by boaks** [comment]
May be

https://github.com/OpenMobileAlliance/OMA-LwM2M-Public-Review/issues/16

was closed too early.

**Comment by ThGarnier** [comment]
you should be right : short investigation to do

**Comment by ThGarnier** [comment]
Response Codes Table has been significantly  revisited in TS 1.0 (April 2016) 
Bad Request have also been added for Discover & De-Register commands

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment this is covered in TS 1.0 (April 2016)
