### ISSUE TITLE
Very Large Object Observation

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/OMA_LwM2M_for_Developers#76]
### Clarifying the notify payload

  The specification is not really clear about the notify payload, they say:
_The “Notify” operation is sent from the LWM2M Client to the LWM2M Server during a valid observation on an Object Instance or Resource. This operation includes the new value of the Object Instance or Resource._
#### The spec just talk about object instance and resource observation.

  What about object observation ?
#### This is not clear what "new value" means ?

  For a resource this is clear enough, if the value change we return the resource. But for an object or an object instance, we could imagine several solutions. Is it the whole object/object instance or just the resources which changed ? 

  If we want to be compliant with [CoAP observe](https://tools.ietf.org/html/rfc7641#section-1.2), the whole object/object instance should be chosen, but in this case, this is a real limitation for very large object observation...

**Comment by sbernard31** [comment]
I know there is some discussions between Kovatsch Matthias(from [Californium][1]), Carsten Bormann and Klaus Hartke(which work on [CoAP PATCH][2]), about a way to resolve this kind of use cases at CoAP level.

[1]:https://www.eclipse.org/californium/
[2]:https://tools.ietf.org/html/draft-vanderstok-core-patch-02

**Comment by ThGarnier** [comment]
According to WG (Oct16 F2F meeting)  CoAP (OPbserve) compliance must preserved here => To Be Closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above re: CoAP compliance

**Comment by boaks** [comment]
When "WG (Oct16 F2F meeting) CoAP (OPbserve) compliance must preserved here" is true, and
"OMA-TS-LightweightM2M-V1_0-20170208-A", section 5.5.1, says

> The LwM2M Server initiates an observation request for changes of a specific Resource, Resources within an Object Instance or for all the Object Instances of an Object within the LwM2M Client.

Then 5.5.2 

> The “Notify” operation is sent from the LwM2M Client to the LwM2M Server during a valid observation on an Object Instance or Resource. This operation includes the new value of the Object Instance or Resource. 

should be clarified to:

> The “Notify” operation is sent from the LwM2M Client to the LwM2M Server during a valid observation on all the Object Instances, an Object Instance or Resource. This operation includes the new value of all the Object Instances, the Object Instance or Resource. 

This implies, that if the observe is established to the "all objects" (e.g. /oid), not only the changed instance is included in the notify, all instances of the objects must be included.

Otherwise you violate RFC7641.
