### ISSUE TITLE
Software update flow

### ISSUE THREAD

**Issue by msangoi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#8]
In the new draft of the Software Management Object (Draft Version 1.0 – 04 Feb 2015), the software "update" (new version of an installed software) is not mentioned anymore.

Following the existing Package Installation State Machine, there is no way to get back to the INITIAL state (unless an uninstall operation is performed).

Is it possible to clarify this point?
Thanks.

**Comment by msangoi** [comment]
It is now clear in the spec: 
"When the Uninstall resource is executed, the Package InstallationState Machine performs a transition back to the INITIAL State and the Update Result is reset to the initial value 0. When this command is used with an argument “ForUpdate” (argument=1), the LWM2M Client is prepared to receive a new Package which will be used to upgrade the Software already in place".

Can be closed.

**Comment by Megan-OMA** [comment]
Issue closed per Manuel's comment above.
