### ISSUE TITLE
Update Supported Objects feature

### ISSUE THREAD

**Issue by merin1989** [OpenMobileAlliance/OMA_LwM2M_for_Developers#81]
Hi,

I’m referring to the OMA-TS-LightweightM2M-V1_0-20141126-C document, Appendix E. LWM2M OBJECTS DEFINED BY OMA.

In the section, E.6 LWM2M OBJECT: FIRMWARE UPDATE, there is a resource Update Supported Objects. 

Could you please provide me clarity on what this feature does. What are the requirements from the Client and Server side?

**Comment by ThGarnier** [comment]
Regarding the Update Registration, the spec doesn't say when exactly the the update registration will take place (p29 20160407) , so the parameter you are mentionning just say (when True) to the client : hey !! as soon as possible do a Update registration (for objects which have been changed with that firmware update process), not wait until the next periodic Update occurrence.

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
