### ISSUE TITLE
key for device lifetime

### ISSUE THREAD

**Issue by jvermillard** [OpenMobileAlliance/OMA_LwM2M_for_Developers#82]
quote:

> Key that can with high probability be kept secret for the lifetime of the device. This requires that at minimum each key is unique per device, that each key has high entropy, and that each key retains high entropy even given knowledge of keys extracted from other devices.

A key can't be used for the device lifetime (~10years) in 10 year if any flaw is discovered in DTLS impl or in your device key storage, RNG ir if you have a factory IT breach or any security issue you are in deep troubles. 

So a key can't be tied to device lifetime, you need to have a way to replace or upgrade it.

Also this is going against the NIST cryptoperiod recommendations: http://www.keylength.com/en/4/

**Comment by jvermillard** [comment]
refer to #39

**Comment by hannestschofenig** [comment]
The text concerning this issue was rewritten and published with LwM2M v1.0. I consider it closed.
