### ISSUE TITLE
PUT request clarification for Write Attribute vs payload

### ISSUE THREAD

**Issue by yogpan01** [OpenMobileAlliance/OMA_LwM2M_for_Developers#83]
How should a Read Resource handle PUT request which contains Write Attribute values ? Issue is that if its a READ resource then as per the specification the allowed operation is GET but if we want to set some observing attributes then we need PUT request from Server side to achieve this . It means a READ resource should be able to handle both GET and PUT at the same time. This is creating conflicts on the client implementation that should it allow PUT requests (because then it will also mean that resource becomes writable) . We need some clear instructions on this. Whether a PUT request can only contain either payload or Write Attributes and not both.

**Comment by dnav** [comment]
Hi,
I think you are viewing this from CoAP point-of-view, not a LWM2M one.
Per specification, allowed operations on a READ resource are "Read" and "Write Attributes". So a Read resource needs to handle CoAP GET and CoAP PUT with no payload.
As a LWM2M command is either a Write or a Write Attributes, it seems clear to me that a CoAP PUT containing both a payload and atrributes is not a valid LWM2M command.

**Comment by ThGarnier** [comment]
I guess dnav answer is clear (and correct :-) ) .  Could be close this issue ? for me yes !

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
