### ISSUE TITLE
5.3.2 Update / Lifetime-1sec could be used

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#84]
Sorry, my/our experience with that is extremely bad!!!

COAP spec. takes care of package loss using retries. But "-1s" doesn't give you a chance to do that. So if the "update" is retried, it will be in vain, because the server has already deregistered the client.

Also, different "networks" have much larger delays. Therefore the ACK_TIMEOUT may be adjusted.

So my proposal would be:
- lifetime - (4 \* ACK_TIMEOUT) 
- if (lifetime - (4 \* ACK_TIMEOUT)) < 0, then use lifetime / 2.

**Comment by sbernard31** [comment]
Using [CoAP RFC](https://tools.ietf.org/html/rfc7252#section-4.8.2), a better margin formula  could be maybe something like : 
**MARGIN = MAX_TRANSMIT_SPAN** ( or maybe  **MAX_TRANSMIT_WAIT**).

This could be used at client side, in this case client should send `update` each **LIFETIME - MARGIN** seconds

Or this could be used at server side, in this case the server should remove the `registration` after **LIFETIME + MARGIN** seconds

Handling margin at client side means that we can not have a lifetime lower than **MARGIN** without doing something strange.
Handle the margin at server side means that server should know MAX_TRANSMIT_SPAN or MAX_TRANSMIT_WAIT which depends of client configuration.

So I think, this is probably better to handle this at client side but in this case client should not allow lifetime < MARGIN + 1.

**Comment by boaks** [comment]
On RFC base you are sure right.
Short MARGIN will cause deregistrations even if the client just has little problems.
Long MARGIN will delay deregistrations for at least that MARGIN.
Therefore I choose some value in the "middle".

But the most important thing for me seesm to be:
Not onyl +1s!

**Comment by jvermillard** [comment]
We did this comment live to the DM group yesterday.

**Comment by Megan-OMA** [comment]
@ThGarnier, any update on this issue per @jvermillard's comment that this issue has already been brought to the Working Group?

**Comment by dnav** [comment]
The incriminated text was removed from the TS. Implementers should use their best judgement to be sure that the registration update can reach the LwM2M Server before the lifetme expires.
