### ISSUE TITLE
TLV content for multiple-instance objects with one instance

### ISSUE THREAD

**Issue by msangoi** [OpenMobileAlliance/OMA_LwM2M_for_Developers#86]
In 6.3.3: 
> The Object Instance TLV is only required if multiple Object Instances are returned in a request.

It is needed to clarify what is the expected TLV content when requesting a multiple-instance object with only one instance.
Without the Object Instance TLV, there is no way to find out the instance ID.

A simple solution would be to define the Object Instance TLV as mandatory (whatever the number of returned instances).

**Comment by david-antliff-imgtec** [comment]
The similar concern has arisen with regards to the Multiple Instance TLV - the spec is not clear that this should be present in all cases, including multiple-instance resources with a single instance, and multiple-instance resources with no instances.

**Comment by fdur** [comment]
:+1:

**Comment by ThGarnier** [comment]
I think you are raising this issue in the Notify context,  as alex-ellwein suggested it, right ? 
In that context, yes, in case of an Object with multi Instances (msangoi) , the Object Instance TLV should be specified as mandatory in the spec;  the same (DavidAntliff) if a Resource is Multiple, the multi-resource TLV should be specified  as mandatory in the spec .  More general issue is addressed in #105 (alex-ellwein) so #86 & #105 have to be addressed together . Thanks

**Comment by jvermillard** [comment]
So for the spirit of the RFC:
https://tools.ietf.org/html/rfc7641#section-3.2

> Notifications are additional responses sent by the server in reply
> the single extended GET request that created the registration.  Each
> notification includes the token specified by the client in the
> request.  The only difference between a notification and a normal
> response is the presence of the Observe Option.

So it's clear the CoAP observe expect you to produce a notification like you produce a GET response.

But yes it's not really efficient for our usage.

**Comment by msangoi** [comment]
@ThGarnier the issue is about all responses content (read responses and observe notifications).

**Comment by ThGarnier** [comment]
Ok I get it, you are right: the only-one instance of a multi-instances object could have any ID value .

**Comment by ThGarnier** [comment]
@DavidAntliff : regarding the multiple instances resource you mentionned : for me the common sense is the following 
- if there is at least one instance, there is no choice, the multiple Resource TLV is used
- if there is no instance for the multi-instances resource, then possibly nothing could be reported in the TLV : it is consistent with the JSON format, in which there is no entry for such a not existing instance
- if the Multiple-instance resource is a mandatory resource, at least one Instance should be available (!)
however there is no issue if only the multi Resource TLV is used for no instance 
  
Will be addressed in the DM group for fully clarifying the view  . Thanks !

**Comment by ThGarnier** [comment]
During the OMA Interim meeting (Sept 2016) it has been statued - for simplicity -that the multiple Resource TLV MUST be used for multiple Instance resource whatever the number of instances to return
TS 1.0 20160914 => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above 11-Oct-2016
