### ISSUE TITLE
Discover on Object

### ISSUE THREAD

**Issue by sznaider** [OpenMobileAlliance/OMA_LwM2M_for_Developers#89]
In 5.4.1 Read section (of the most up to date draft), we have:
> If Object ID is only specified, the LWM2M Client MUST respond to the
> "Discover" operation with the list of Object Instances (...)

However presented example shows Discover behavior on a Single Instance Object,
and that makes the whole section little unclear.

Imagine we have an Object X with multiple Instances enumerated from 1 to N,
also assume that every Instance has resources 0 and 1. For simplicity let's
ignore Attributes.

In some previous drafts output of the form: `<X/0/1>, <X/0/2>` is said to be correct 
and it was explicitly clarified that such output describes every Object Instance, and 
not just Object Instance of ID 0.

What is the expected output of Discover operation on /X now?

**Comment by sznaider** [comment]
Any news on the issue?

**Comment by ThGarnier** [comment]
Is it really an issue ?  examples are of course not exhaustive and your are right they are mainly focussed on attributes, and resources  discovering. 
However the text says :"If Object ID is only specified, the LWM2M Client MUST respond to the “Discover” operation with the list of Object Instances and the list of their respective Resources implemented by the LWM2M Client for that Object. In addition the list of Attributes which have be assigned to this Object level (see section 5.1.2 Attribute Classification) are also returned"
So clearly in yr example ( for simplicity attributes are ignored :-) )  Discover X  will return  </X/0/0>,</X/0/1>, </X/1/0>,<X/1/1> . agree ?

**Comment by ThGarnier** [comment]
oh sorry the text between '< > ' disappeared ; should be quoted I guess :  so again 
Discover X will return  '</X/0/0>,  </X/0/1>, </X/1/0>, </X/1/1>'

**Comment by ThGarnier** [comment]
:(   Discover X will return  `<X/0/0>`, `<X/0/1>`, `<X/1/0>`, `<X/1/1>`

**Comment by sznaider** [comment]
Thanks for your reply. :-)

After your clarification I think we can close this issue. Thanks again.
