### ISSUE TITLE
Millisecond precision

### ISSUE THREAD

**Issue by TomMettam** [OpenMobileAlliance/OMA_LwM2M_for_Developers#90]
The specification caters for timestamped notifications via application/vnd.oma.lwm2m+json and the "t" and "bt" parameters.

However, there appears to be no allowance for sub-second precision. 

In my usage scenario, there is a requirement for millisecond precision of samples. Is there any mechanism in place to cater for this? What would be the recommended approach for dealing with this in a compliant manner?

**Comment by Megan-OMA** [comment]
@TomMettam - will you please comment the release date of the TS document you are referring to / version of the spec? This helps the Working Group find the issue much quicker.

**Comment by jvermillard** [comment]
Hi @TomMettam,
It's not very clear in the LWM2M TS but if you look at the SenML draft RFC: https://datatracker.ietf.org/doc/draft-jennings-core-senml/?include_text=1

> Time is represented in floating point as seconds

So you can send millisecond precision using floats

**Comment by ThGarnier** [comment]
I agree with Tom remark;  a (small) fix in the TS is currently proposed to solve this issue and to be fully inline with SENML regarding the timing approach (t & bt).

**Comment by ThGarnier** [comment]
The TS 1.0 2016 of August fixed that point (Section 6.4.4) (t & bt are now floating point values) => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above
