### ISSUE TITLE
Interleaved Bootstrap and regular requests

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/OMA_LwM2M_for_Developers#91]
Hello,

I've run into another issue while attempting to write a client-side implementation of the Bootstrap Interface. While Bootstrap is normally expected to occur only at initialization time, section 5.2.3 point 5 seems tu suggest that it may be possible for the Bootstrap Server to issue a command for the Client at _any_ time - in particular, in an environment while regular LWM2M Servers are configured and actively managing the device.

Should the Client accept requests from both the regular servers and the Bootstrap Server in such case? This may lead to unexpected results, for example when the Bootstrap Server deletes all Instances of some Object and creates new Object Instances, assuming that they will be the only ones available, but a Create request is received from a regular server in between.

The alternative would be to put the device in something like a "bootstrap mode" upon receiving a Bootstrap Write or Bootstrap Delete request (signifying the beginning of a Server Initiated Bootstrap procedure) and ignore requests from any regular servers that might come, until receiving a Bootstrap Finish message.

Unfortunately, the specification does not address this issue at all.

**Comment by ThGarnier** [comment]
According to the OMA Aug meeting it has be statued that during the subsequent bootstrap's of the device, the device would ignore and flush all the previous states in the device and starts fresh further to the bootstrap completion. (added in section 5.2 : Oct16  TS)

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above / reference to section 5.2 from October 2016 TS
