### ISSUE TITLE
Binary SMS port number for LWM2M SMS binding

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA_LwM2M_for_Developers#92]
Hello

LWM2M allows SMS binding. What is the port number to be  used for such binding? Specification does not specify any port number. 

The use case uses no sec sms.

Thank you

H. Ali

**Comment by Megan-OMA** [comment]
@HAli786 - will you please comment the release date of the TS document you are referring to / version of the spec? This helps the Working Group find the issue much quicker.

**Comment by HAli786** [comment]
Thank you very much for reply.

I am referring to OMA-TS-LightweightM2M-V1_0-20151214-C.

Thanks again

H. Ali

**Comment by ThGarnier** [comment]
(OMA Interim meeting (Sept 2016)  answer) : please refer to 3GPP TS 23.040, section 9.2.3.24 for details of the port. LWM2M TS is based on this addressing mode, which is described in section 7.2  => to be closed

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's reference / comment above
