### ISSUE TITLE
5.3.1 Register / should the object instances contain instances of LWM2M Securtiy Objects

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#93]
According the TS the registration contains 

    "The list of Objects supported and Object Instances available on the LWM2M Client". 

That list for the example client of Appendix F) is:

    </1/0>, </1/1>, </2/0>, </2/1>, </2/2>, </3/0>, </4/0>, </5>

Appendix F lists 3 instances of LWM2M Security Object (/0/0,/0/1, and /0/2), but they are not contained in that list.
So:
1. should the LWM2M Security Object be included in the registration list?
2.a. if not, could "except the LWM2M Security Object and Instances" be added to the TS to clarify it?   
2.b. if they should be included, could `</0/0>,</0/1>,</0/2>,` added to the list in TS to clarify it?

**Comment by fdur** [comment]
I think that </0/0>,</0/1>,</0/2> list does not need to be included in the list.
Object 0 can be read and write by the bootstrap server and, from my point of view, the DM server does not need to have access to values from object 0

I agree to take into account point 2.a

**Comment by boaks** [comment]
Thanks for your answer and vote for 2.a. (it's also my favorite :-) ).

    "Object 0 can be read and write by the bootstrap server"

Hm a bootstrap server is only able to write something, the read is not specified.

**Comment by fdur** [comment]
You're right ... I answered too quickly :): a bootstrap server is only able to write something
No server could be able to read object 0

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20160407-C

still not clarified.

**Comment by ThGarnier** [comment]
Yes all these aspects have-to/will be fixed soon :-) Thanks

**Comment by ThGarnier** [comment]
The July TS1.0 draft explicitly says Object 0 (Security) must not be part of the registration objects list
(in line with the 2.a proposal) 
=> to be closed

**Comment by boaks** [comment]
Fixed by OMA-TS-LightweightM2M-V1_0-20160711-D.
