### ISSUE TITLE
CoAP mapping of create contains still instance id

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#94]
OMA-TS-LightweightM2M-V1_0-20160202-D:

page 66, table 23.
The create operation still contains a "instance id", though 

page 33, table 14.
doesn't contain it any longer.

**Comment by boaks** [comment]
OMA-TS-LightweightM2M-V1_0-20160407-C, page 67, table 23

still contains the "instance id" for create.

**Comment by ThGarnier** [comment]
Fixed for the May release

**Comment by boaks** [comment]
Fixed with OMA-TS-LightweightM2M-V1_0-20160509-D.
