### ISSUE TITLE
Example URIs in Appendix F of TS does not list coaps

### ISSUE THREAD

**Issue by HAli786** [OpenMobileAlliance/OMA_LwM2M_for_Developers#95]
Hello,

I want to understand the logic behind not listing the server URI with coaps protocol identifier in the appendix F of example security objects supporting pre-shared key security mode. All the security objects listed in this appendix have used coap:// in their URI.

Ts reference: OMA-TS-LightweightM2M-V1_0-20151214-C

Thank you
H. Ali

**Comment by ThGarnier** [comment]
Sorry, could you clarify a bit your question ? Appendix F - regarding the coap protocol identifier use - is correct right ? so ?  maybe part of yr question is missing ?

**Comment by ThGarnier** [comment]
No answer for 2 months => to be closed

**Comment by ThGarnier** [comment]
Ok should be corrected at least in Oct16 TS (examples)

**Comment by Megan-OMA** [comment]
Issue closed per Thierry's comment above
