### ISSUE TITLE
OMA-TS-LightweightM2M-V1_0-20160407-C, 8.5 Response Codes, Bootstrap Finish

### ISSUE THREAD

**Issue by boaks** [OpenMobileAlliance/OMA_LwM2M_for_Developers#99]
Please provide an example for "4.00 Bad URI provided".

Though the `Bootstrap Finish` is specified with a fixed URI `/bs`, a request with a different URI may not be processed as a `Bootstrap Finish` at all.

So, should all `POST` from the LWM2M Server with a URI different than `/bs` result in  `4.00`?

**Comment by jvermillard** [comment]
yup "Bad URI provided" looks like a 4.04

**Comment by ThGarnier** [comment]
On the Bootstrap Interface, all POST must have an URI starting with /bs

**Comment by boaks** [comment]
> On the Bootstrap Interface, all POST must have an URI starting with /bs

So, should all `POST` from a boostrap server endpoint with a URI different then `/bs` be treated as a malformed `bootstrap finish`?

My point is, there is not much indication, that it is a "bootstrap finish'. We have the bootstrap server endpoint, the POST method and the URI. Therefore the most defects may not be recognized as defects of bootstrap finish, they may be recognized as an defect of an other operation.

**Comment by ThGarnier** [comment]
According to the last OMA WG session in Paris, the question seems not so clear. Could you clarify a bit the problem please ? many thanks

**Comment by boaks** [comment]
`Please provide an example for "4.00 Bad URI provided".`

Just try to provide a example for that error! Doing so, it would be clear, that there is not too much indication for the "bootstrap finish" operation, except, that the source is a bootstrap server and its a `POST`. The URI `/bs` could not be taken in account, because that should be the error. So, in my opinion, in many cases, it would not be possible to detect, that the message is related to a "bootstrap finish" operation.

**Comment by dnav** [comment]
If the Bootstrap Server send a POST and the URI does not start with ```/bs``` then the Client returns a 4.00 error.

**Comment by boaks** [comment]
> does not start with `/bs`

Or doesn't match `/bs`.

And, if it's only the URI, why not 4.04 (as julien already mentioned above)

**Comment by dnav** [comment]
Yes sorry it should be "the URI is not ```/bs```".

A bootstrap Server can only send POST commands to the ```/bs``` URI. So I'm not disturbed by the 4.00 error code. 4.04 is tricky since the Bootstrap Server could send the POST on an existing URI.

**Comment by boaks** [comment]
> 4.04 is tricky since the Bootstrap Server could send the POST on an existing URI.

OK, now it's getting more complex:
What should a bootstrap server, which POST with a different, but existing, URI, get as response?

**Comment by dnav** [comment]
> What should a bootstrap server, which POST with a different, but existing, URI, get as response?
4.00

Sorry things got confusing in the length of the discussion. Allow me to summarize:
The Bootstrap Server can only send POST commands to the ```/bs``` URI.
So when receiving a POST from the Boostrap Server, if the URI is ```/bs``` this is a Bootsrap Finish command, otherwise return a 4.00 error code.
